### ISSUE TITLE
Headlines are not shown

### ISSUE THREAD

**Issue by rweickelt** [michaeljones/breathe#116]
Headers from doxygen documentation are not printed in Sphinx/Breathe.

I've tried different markup styles from within a class documentation:

```
/*!
 This is a documentation

<h2>Header</h2>
Text

Header
---------
Text

### Header ###
Text
*/
class Test {};
```

None of them worked. They are simply missing in the output. Everything else is shown normal. I guess that Breathe supports any markup syntax that Doxygen understands. So I consider this to be an error. Or am I missing something?

**Comment by melvinvermeeren** [comment]
In current versions of Breathe the headings are rendered in italic, so I guess this has been implemented in some way.

Closing for now as I think this is okay, please comment if I'm missing something.
