### ISSUE TITLE
Adding a cpp:guess domain

### ISSUE THREAD

**Issue by blastrock** [michaeljones/breathe#117]
Having to specify :cpp:class: in front of every reference is a bit long to write and makes the rst file less readable. One solution is to use

    .. default-role:: cpp:class

But then it would only work for classes, not functions or other things.

It would be nice to have a cpp:guess domain that would just use the correct type. There should be no ambiguity since a class can't have the same name as a function or anything else.

**Comment by vitaut** [comment]
This has been implemented in Sphinx with `:cpp:any:`: https://github.com/sphinx-doc/sphinx/issues/1744.

**Comment by michaeljones** [comment]
:+1:
