### ISSUE TITLE
Objective-C: is it supported?

### ISSUE THREAD

**Issue by biasmv** [michaeljones/breathe#129]
Hi,

We would like to generate documentation for Objective-C using breathe. Is this use-case supported out of the box? We have tried to use it as is, but were running into problems. 
- the method signatures are garbled. For example, foo:(int)a withA:(int)A andB:(int)B; is rendered as foo:withA:andB:(int,int,int). Is this something we have to take care of in our template?
- how does one link to an objective-C class? Or put another way, what is the equivalent of `:cpp:class:` for objective-C classes?

Thank you very much

**Comment by vitaut** [comment]
This will require adding Objective C support in Sphinx (an Objective C domain), so I suggest opening an issue there and closing this one until there is at least minimal support for this language in Sphinx. Currently there is nowhere to map Doxygen constructs.

**Comment by melvinvermeeren** [comment]
As said above this requires an Objective C domain in Sphinx itself, either native or as extension.

For some additional details refer to my recent comment on #249.

Closing for now as there is no support or extension as far as I can find quickly.
