### ISSUE TITLE
breathe exceptions with duplicate 'functions' in C domain

### ISSUE THREAD

**Issue by jwag956** [michaeljones/breathe#138]
If there are 2 identical defines (as doxygen renders) in .h files - that will trigger a:
Warning: Ignoring duplicate 'xxx'. As C does not support overloaded functions. Perhaps you should be using the cpp domain?

which in recent breathe releases causes an exception:
    targets.extend(self.create_domain_target())
TypeError: 'NoneType' object is not iterable

The fix is extremely trivial - in

renderer/rst/doxygen/domain.py::CDomainHandler:

        if self.helper.is_duplicate(name):
            print ("Warning: Ignoring duplicate '%s'. As C does not support overloaded "
                   "functions. Perhaps you should be using the cpp domain?" % name)
            return

change the return to return [] (as is done in the cpp domain handler).

thanks!

**Comment by vitaut** [comment]
@jwag956 We have switched from domain handlers to direct use of Sphinx domain directives. I don't see any issues with using duplicate macros or function declarations:

C:
```c
/** Define 1 */
#define A 1

/** Define 2 */
#define A 1

/** Function 1 */
void f();

/** Function 2 */
void f();
```

RST:
```
.. doxygendefine:: A

.. doxygenfunction:: f
```

Output:
```
A
Define 1.

Define 2.

void f()
Function 1.

Function 2.
```
