### ISSUE TITLE
Incorrect rendering of enumeration constant with explicit value

### ISSUE THREAD

**Issue by vitaut** [michaeljones/breathe#147]
In http://breathe.readthedocs.org/en/latest/#nutshellclass_nutshell_1ae42034231cf912d095d57cbeed6cda79 the enumeration constant `kHammer` is rendered as

```
kHammer = = 0
```
Note extra `=`.

**Comment by michaeljones** [comment]
Hi @vitaut,

Thanks for reporting it and for the fix. I had made a note #139 but not managed to get any further.

I won't make any time promises but I will attempt to merge it in when I get a chance. Shout if you'd like a new release. Also let me know if/when I can use the `mp` docs as another example.

Cheers,
Michael

**Comment by vitaut** [comment]
Hi Michael,

> I had made a note #139 but not managed to get any further.

Didn't see that one, sorry for the duplicate.

> I won't make any time promises but I will attempt to merge it in when I get a chance.

Thanks.

> Also let me know if/when I can use the mp docs as another example.

Will do.

Regards,
Victor

**Comment by michaeljones** [comment]
Merged. Much appreciated.

**Comment by vitaut** [comment]
Thanks, Michael!
