### ISSUE TITLE
Can't link to a typedef

### ISSUE THREAD

**Issue by vitaut** [michaeljones/breathe#149]
Links to typedefs created with `:cpp:type:` role don't seem to work.

C++ code:
```
/**
 Test typedef.
 */
typedef int T;

/**
 Test class.
 */
class C {};
```

RST code:
```
Test
====

.. doxygenclass:: C

Link to class :cpp:class:`C`.

.. doxygentypedef:: T

Link to typedef :cpp:type:`T`.
````

The resulting HTML contains a link to class `C`, but not to typedef `T`.

The complete example that reproduces the problem is also available here: https://github.com/vitaut/breathe-test

**Comment by michaeljones** [comment]
Thanks for highlighting this. The linking functionality is minimal at the moment but it is good to have a reason to try to expand it. I've forgotten what the code even looks like but I'll try to find the time to dive in an have another look.

Cheers,
Michael

**Comment by vitaut** [comment]
Fixed in https://github.com/michaeljones/breathe/commit/7239109af8b558b7597a046c65ca1cfa8b29f07c.
