### ISSUE TITLE
Can't link to nested classes/typedefs

### ISSUE THREAD

**Issue by vitaut** [michaeljones/breathe#151]
Links to nested classes created with `:cpp:class:` role don't seem to work. Same for typedefs defined in class scope (links to top-level typedefs work with https://github.com/michaeljones/breathe/pull/150).

C++ code:
```
/**
 Test class.
 */
class C {
 public:
  /** Test typedef. */
  typedef int U;
  
  /** Nested class. */
  class V {};
};
```

RST code:
```
Test
====

.. doxygenclass:: C
   :members:

Link to class :cpp:class:`C`.

Link to class :cpp:class:`C::V`.

Link to typedef :cpp:type:`C::U`.
````

The resulting HTML contains a link to class `C`, but not to class `C::V` or typedef `C::U`.

The complete example that reproduces the problem is also available here: https://github.com/vitaut/breathe-test/tree/32956f067f5870a0fc29808741af711e0383d029

**Comment by vitaut** [comment]
In case of a typedef, we need to add a qualified name (`C::U`) instead of an unqualified name (`U`) in https://github.com/vitaut/breathe/commit/0651bf495f5100017d055d85ed3fc5da7f7bf507#diff-1e81491a24e9a57cff51cf8e6a2692a7R136. Is there a way to get the container class (or at least its name) from the `memberdefTypeSub` object representing the typedef? Then it can be concatenated with `::` and the typedef name to form the full target name.

Another option is to parse the `definition` field of the `memberdefTypeSub` object which is `typedef int C::U` in this case, but this will require more work.

**Comment by michaeljones** [comment]
I can't answer off the top of my head but I'd be curious to look into it more. There is a context in the render process that we could use to try to pass down the current namespace but I'll need to look closer. Are you keen to have a shot at it? Should I just offer advice? Or would you rather I try to solve it?

Thanks for the helping and motivation as always.

**Comment by vitaut** [comment]
I'd be happy to look into it and would appreciate any advice from you. Thanks!

**Comment by michaeljones** [comment]
So, I've taken a quick look at it. I agree that we should try to avoid parsing the `definition` as C++ is pretty horrible for creating potentially messes for parsing, I feel.

You were right to suggest getting the container classes/nodes. I'd forgotten that the render context that was added actually maintains a node stack which has the node and all its parents. 

I haven't really tested it this and just shout if you'd like me to, as I hope it is pretty much there, but I think these diffs should do it or hopefully get close. 

```diff
     def create_domain_target(self):
 
-        return self.domain_handler.create_typedef_target(self.data_object)
+        return self.domain_handler.create_typedef_target(self.data_object, self.context.node_stack)
```
 
```diff
 class CppDomainHandler(DomainHandler):
 
+    def get_qualifier(self, node_stack):
+
+        qualifier = []
+        for node in node_stack:
+            if node.kind in ['class', 'namespace']:
+                qualifier.append(node.name)
+
+        return '::'.join(qualifier)
+
```

```diff
-    def create_typedef_target(self, data_object):
+    def create_typedef_target(self, data_object, node_stack):
 
         id_ = self.create_class_id(data_object)
+        qualifier = self.get_qualifier(node_stack)
+
         name = data_object.name
+        if qualifier:
+            name = "{0}::{1}".format(qualifier, data_object.name)
 
         return self._create_target(name, "type", id_)
```

So basically, we pass the current `node_stack` (the current node and all its parents) to the `create_type_target` method and then have a helper method to iterate up the stack and figure out which nodes would contribution to the namespace of the typedef.

Does that seem reasonable? I think it is better than my initial thought of maintaining the current namespace in the render context itself. Easier to just grab it on demand and we're unlikely to benefit from caching it, I doubt.

All that said, it'd be ace if I could have easily just added this to this to your pull request for us to play around with. Would you mind if I give you contributor permissions for this repository? Then you could push branches straight to it? You can still make pull requests if you'd like a bit of discussion about the changes but then the branches will be in this repo and we can work on them together. Sorry I have never asked before.

Michael

**Comment by vitaut** [comment]
Thanks a lot for the pointers, `node_stack` was exactly what I needed. I've updated my PR using your diffs with some modifications in https://github.com/vitaut/breathe/commit/d758ba3035ad8e24c5f1073a16501dcc98ba2391 and the links to typedefs defined in class scope work fine now.

Some comments about the modifications:

1. I use `node_type` instead of `kind` because not all nodes have the latter.
2. I build a fully qualified name from the `node_stack` and don't use `data_object` which makes the code slightly simpler.

Please let me know if you are OK with the solution and I'll implement similar changes for classes (perhaps in a separate PR not to delay the current fixes).

>  Would you mind if I give you contributor permissions for this repository? Then you could push branches straight to it?

I wouldn't mind at all, thanks for offering this. I promise to keep my modifications in separate branches =).

**Comment by michaeljones** [comment]
Great, I've added you as a collaborator. Hopefully it all 'just works' as far as access and permissions and the like.

Thanks for the changes. They make sense to me though I'm concerned about just using the `node_type`. You're right that some objects don't have a `kind` but I think we want to talk in terms of classes & namespaces and not just `compounddefs` and `memberdefs`. I might be wrong but I think that if you have a typedef in a file, not in any surrounding namespace & class then its parent `compounddef` is the file itself, so you might end up with `myfile.h::mytypdef` which would be wrong, I guess?

When the filter code needs to check for `kind` it just checks the `node_type` first as all `compounddef` objects have a `kind` attribute and properly the same for `memberdef`. 

That said, I've not had a change to check it properly. This is just from the exploration I did at the weekend. But that is what I'd test before merging.

Thanks again,
Michael

**Comment by vitaut** [comment]
> Great, I've added you as a collaborator. Hopefully it all 'just works' as far as access and permissions and the like.

Thanks!

> I might be wrong but I think that if you have a typedef in a file, not in any surrounding namespace & class then its parent compounddef is the file itself, so you might end up with myfile.h::mytypdef which would be wrong, I guess?

For a top-level typedef, node stack looks as follows:

```
0	memberdefTypeSub: <breathe.parser.doxygen.compound.memberdefTypeSub instance at 0x7f88c3ad9170>	
1	RootDataObject: <breathe.directives.RootDataObject object at 0x7f88c817f750>	
```
As you can see there is no parent `compounddef`.

I was thinking of checking `node_type` first and then `kind` but this looked unnecessarily complicated and fragile as `get_fully_qualified_name` can potentially accept any kind of C++ symbol (currently it is only used for typedefs, but I was going to reuse it for other things). Maybe it's easier to filter out unnecessary stuff like file nodes if they can appear in the stack although I haven't seen a case where it happens yet.

**Comment by michaeljones** [comment]
You sound like you're happy with what you've done so I've got faith in that. I can't quite picture it all myself and I haven't quite got the time this evening. The next step (which I am happy to do but equally happy for you to) is to add some examples in the `examples/specific/typedef.h` file. Preferable some in classes and in namespaces and in classes in namespaces and then extend the `domains.rst` file to include examples of those working. 

Again, more than happy to do that but if you have the time and motivation then you're welcome to as well.

Cheers,
Michael

**Comment by vitaut** [comment]
As you suggested, I've added a few examples in https://github.com/vitaut/breathe/commit/bfe3ee2f95f68a88976f82d39ff7f73b82488aef. The first (top-level typedef) and the third (typedef in a class) example work fine, but the second (typedef in a namespace) doesn't. Here's the problematic case:

```
C++:
namespace testnamespace {
  typedef char *AnotherTypedef;
}

RST:
   .. doxygentypedef:: testnamespace::AnotherTypedef
      :path: ../../examples/specific/typedef/xml

:cpp:type:`testnamespace::AnotherTypedef`
```

The problem is that the node stack here only contains memberdef and root node:

```
0	memberdefTypeSub: <breathe.parser.doxygen.compound.memberdefTypeSub instance at 0x7f6c70e8e638>	
1	RootDataObject: <breathe.directives.RootDataObject object at 0x7f6c7140b750>	
```
and memberdef's name is simply `T` without the namespace. Do you have an idea why the compound node for the namespace is not on the stack?

**Comment by vitaut** [comment]
The problem is that the compound node found in https://github.com/michaeljones/breathe/blob/master/breathe/finder/doxygen/index.py#L15 is discarded and only the member node is returned. One possible solution is to return both compound and member node in results:

```
            if matcher_stack.match("compound", compound):
                compound_finder = self.item_finder_factory.create_finder(compound)
                members = compound_finder.find(matcher_stack)
                for m in members:
                  results.append([m, compound])
```
or something like that, and then propagate the compound to the node stack. What do you think?

**Comment by michaeljones** [comment]
Thanks for tracking it down. Yeah, the `node_stack` stuff came after that finder functionality and I didn't really think in terms of it I'm afraid.

Could return the both in that case but I'd rather something more generic if we can, ie the full node stack if possible. My concern is that it is using the `matcher stack` functionality which I'm very slowly deprecating in favour of the other approach (the `filter_` method on that class rather than the `find` method.) Though honestly I find the filter stuff pretty confusing to get back into.

The steps I'd take are:
- Try to switch over to the `filter` method and have that build and return the full `node_stack`.
- If that doesn't look likely, switch the `find` method that is currently being used to return the `node_stack` and use that.
- If that doesn't work return the `[member, compound]` as you suggest.

That said, I'd only do the first step as a kind of intellectual exercise. I can't really recommend it unless you're curious to dive into the code. Either way, I can try to take a deeper look if you like at some point or you can take a swing at it. 

Thanks again,
Michael

**Comment by vitaut** [comment]
The filter approach does sound like a better solution, I'll look into it. Thanks for the suggestion!

I'm only concerned about further delaying PR #150 which addresses one of the use cases I have in the documentation for https://github.com/ampl/mp. Since this PR is already an improvement over existing situation, would you mind merging it in while I'm working on the new PR that addresses the issue with references to typedefs defined in namespaces? This is not critical though, as I can always use my fork instead of the main repo.

**Comment by vitaut** [comment]
So I managed to replace the matcher stack with filters using function directive code as an example (BTW the filter functionality is really cool). But how does it help to get the full node stack instead of constructing a rudimentary one in https://github.com/michaeljones/breathe/blob/master/breathe/directive/base.py#L89:

```
context = RenderContext([data_object, self.root_data_object], mask_factory)
```
Does the finder/filter keeps a stack of visited nodes somewhere?

**Comment by michaeljones** [comment]
More than happy for you to merge it in, thanks for checking. As you say it only makes things better and the interface isn't going to change even if we end up changing the internals.

Sorry if I was misleading. I was keen to switch over to the filter stuff as I think it is better but it doesn't yet return the full node stack so we'll have to change that too. I haven't looked too closely but I hope it is as easy as:

```diff
         if filter_.allow(node_stack):
-            matches.append(self.data_object)
+            node_stack_copy = node_stack[:]
+            matches.append(node_stack_copy)
```

Or something like that anyway at various points in the `filter_` methods in the `ItemFinder` classes.

The next problem is updating other call sites that use the filter stuff to expect a `node_stack` instead of a single `data_object`. Hopefully not too troublesome but needs to be caught.

From there we might be able to work with that `node_stack`. I haven't really looked too closely though so I'm just hoping that that `node_stack` has the right information in it. If it doesn't we'll have to dig a little deeper!

And, I'm glad you like the filter functionality. I am happy to hear that. I love the design of it all but wonder if it gets a little complicated. At least there is a nice healthy docstring to talk about it :)

**Comment by vitaut** [comment]
OK, I've replaced matcher stack with finder filters in #157. If this looks good to you, I'll try to propagate the node stack and hopefully it will help resolve the issue with linking to typedefs (and other non-class symbols) in namespaces.

**Comment by vitaut** [comment]
Links to typedefs are working with #162, but links to nested classes still need to be fixed.

BTW, what about [DoxygenBaseDirective](https://github.com/michaeljones/breathe/blob/master/breathe/directive/base.py#L96)? Since this class uses `create_matcher_stack` method which doesn't exist any more, it either needs to be updated or removed (if it's something obsolete). AFAICS this class is not used anywhere.

**Comment by michaeljones** [comment]
Thanks for catching that. It looks like in a578eecb5dfe01cdef457e4fcf1dd19e6934a464 I merged the Struct & Class implementation and the Struct directive was the last directive to be inheriting from that class. I should have checked and remove it. Please nuked it if you don't mind taking the time.

**Comment by vitaut** [comment]
Fixed now. Yay!
