### ISSUE TITLE
No link is generated for reference to Doxygen/Breathe generated classes/functions/types

### ISSUE THREAD

**Issue by ereOn** [michaeljones/breathe#153]
I setup breathe according to the documentation and it seems to working great so far.

I have some pretty standard C++ code documented as such:

    /**
     * \file test.h
     */

    /**
     * \brief Some function.
     */
    void foo();

I can generate the Breathe documentation using the following directive in my `.rst` file:

    .. doxygenfunction:: foo

The generation works great but if I try to link this function declaration with a directive like:

    :cpp:func:`foo()`

No link (HTML `<a>`) is generated in the documentation.

The same behavior occurs with class, types, and so on. I tried with/without a namespace but no luck so far.

The documentation states this should work, so  is there anything I'm missing here to make this work ?

Thanks and keep up the good work !

**Comment by vitaut** [comment]
You should add parentheses after `foo`:
```
:cpp:func:`foo()`
```
See http://breathe.readthedocs.org/en/latest/domains.html#c.frob_foos for an example.

**Comment by ereOn** [comment]
@vitaut Nope.

Still doesn't work. Also as I said, it doesn't work for classes (or any type, for that matter) either, so this would have been surprising.

Also, as I mentionned, I followed the documentation (the link you gave, to be specific).

Any other clue ?

**Comment by vitaut** [comment]
Another thing to check is that you have 
```
breathe_domain_by_extension = {"h" : "cpp"}
```
in your `conf.py`.

**Comment by ereOn** [comment]
@vitaut : Indeed !

Works way better now. Thanks !

Is this documented anywhere ? Shouldn't this be a default ?

**Comment by vitaut** [comment]
This is documented in http://breathe.readthedocs.org/en/latest/directives.html#confval-breathe_domain_by_extension, but I guess it could be made more visible by being mentioned in Quick Start or elsewhere.

@michaeljones can probably say more, in particular, whether it makes sense to have it the default. One potential issue is distinguishing between C and C++ code.

**Comment by ereOn** [comment]
@vitaut : The C++ purist in me would agree that C++ header files should be named something else (`.hpp` for instance). However the reality of things is that often a lot of legacy C++ code (and even some new code) use the `.h` extension for both C++ and C.

Is there a way to provide a hint to the user that the wrong domain might be used ? After all, advertising a `class` in the C domain doesn't make much sense, so there must be some way to catch those situations.

At the very least, this may be better advertised in the quick start indeed, as already 3 people tried to do that in my place and missed this configuration value. I suspect it might be the same for other people as well.

Anyway, thanks for the support. I appreciate it.

**Comment by michaeljones** [comment]
Thanks for covering this @vitaut.

And @ereOn thanks for trying Breathe and letting us know of the issue. I can definitely see that it needs to be better covered in the docs. Especially having something on the domains page itself that highlights those config values would be useful.

As for the default value, we could look into it. Doxygen recently added additional data to the xml output which indicates the language being used for particular declarations. We haven't had much chance to work with it but it might make sense to use that by default and provide overrides if needed or a way to disable it entirely, though I'm not sure how. 

We don't have much control when it comes to detecting it being misused as the `:cpp:func:` role comes from Sphinx itself rather than Breathe so we can't really hook into it.

I've made another ticket for the docs (#154) and the domain idea (#155).

Cheers!
Michael

**Comment by xaqq** [comment]
Hello,

I am running into a very similar problem. I added `breathe_domain_by_extension = {"h" : "cpp"}` to the config file just in case (even though my cpp header file are `.hpp`).

```	      
.. doxygenclass:: my_ns::my_class

.. cpp:class:: fake_ns::fake_class

   This is most likely the best class ever ! Also, it's fake.

Hihi :cpp:class:`my_ns::my_class`
Hoho :cpp:class:`fake_ns::fake_class`
````

The link to `fake_class` works while the link to `my_class` doesn't. However, the documentation for `my_class` is correctly generated.

I tried to set `breathe_domain_by_extension = {"hpp" : "cpp"}` but this caused an expection to thrown when building the documentation.

Can you help? 

Thanks

**Comment by vitaut** [comment]
@xaqq Could you post a complete example including `Doxyfile`, `conf.py` and (a relevant part of) the `.hpp` file that reproduces the problem?

**Comment by xaqq** [comment]
Hello @vitaut , 

I created a project from scratch to have the simplest reproductible test case possible.
I created a repository to upload a tarball of this: https://github.com/xaqq/quick_upload/blob/master/mini.tar

my working directory was `/tmp/mini`.

**Comment by vitaut** [comment]
Works fine on the [development version of Breathe](https://github.com/michaeljones/breathe/commits/master). What version do you use?

**Comment by xaqq** [comment]
@vitaut I confirm I got it working using `master`. I was using breathe from `pip install breathe` on debian jessie. I had this file in my system after installing `/usr/local/lib/python2.7/dist-packages/breathe-3.2.0.egg-info` so I guess version `3.2.0`.

**Comment by michaeljones** [comment]
Sorry for the trouble there. @vitaut has asked me to do a new release to PyPI but I've failed to take the time to do it. I'll try to get around to it.

**Comment by michaeljones** [comment]
Done: https://pypi.python.org/pypi/breathe/4.0.0

Sorry for the delay!

**Comment by vitaut** [comment]
Awesome, thanks @michaeljones!

**Comment by michaeljones** [comment]
No trouble mate. Thank you for all your hard work. I've just realised that you're not down as an author on PyPI, I'll try to fix that after Easter. We might consider moving it out of 'Development Status - Beta' as well :)

**Comment by xaqq** [comment]
Hey, thank you for pushing the new version.
