### ISSUE TITLE
Enums are rendered differently from other symbols

### ISSUE THREAD

**Issue by vitaut** [michaeljones/breathe#158]
Enums are rendered as

**NodeType enum**

which is inconsistent with rendering of other C++ symbols such as typedefs which are rendered as

typedef unsigned int **UINT32**

or structs:

struct **StructTest**

I suggest changing the rendering of enums to

enum **NodeType**

(with `enum` keyword first and the name in bold).

**Comment by michaeljones** [comment]
Definitely worth fixing. Not exactly sure when that started happening. It feels like I wouldn't have designed it that way, but perhaps I have been negligent. Hopefully not a big change.

**Comment by vitaut** [comment]
Fixed in https://github.com/michaeljones/breathe/commit/f6a1dcfe04d1f6c12f0cb3936bafdd7de7ac0363.
