### ISSUE TITLE
Reference doesn't work

### ISSUE THREAD

**Issue by dfroger** [michaeljones/breathe#172]
[Documentation](http://breathe.readthedocs.org/en/latest/domains.html) says we can use `:cpp:func:function` to reference a function, but it seems to not work. I can't get any simple example work.

Here is the `.hxx` file:
    https://github.com/dfroger/quickstart/blob/master/breathe/src/spam.hxx

and here is the `.rst` file:
    https://raw.githubusercontent.com/dfroger/quickstart/master/breathe/doc/spam.rst

**Comment by michaeljones** [comment]
Thanks for raising this. Are you using `master` or the latest release on PyPI? I suspect @vitaut is in a better position to comment than I am at the moment but we will definitely look into it.

**Comment by dfroger** [comment]
HI Michael, thanks for the reply. I'm using the lastest release on PypPI. 

However, when I build the breathe documentation, example of referencing functions works.

I'm trying to figure out why...

**Comment by dfroger** [comment]
Adding to **conf.py** :

    breathe_domain_by_extension = {                                                                  
            'hxx': 'cpp'                                                                             
        }

It now works for **class methods**, but not for other functions.

**Comment by dfroger** [comment]
Adding to **conf.py** :

    breathe_domain_by_extension = {                                                                  
            'hxx': 'cpp',
            'cxx': 'cpp',                                                                             
        }

make it work for all function.

There is just a last problem I'm investatigation, if `.. doxygenfunction` and `:cpp:func:` are in different `.rst` files, the links are broken.

**Comment by vitaut** [comment]
The last problem should be already fixed in `master`. Could you please check if it works for you?

**Comment by dfroger** [comment]
I confirm it work for me with `master`. Thanks!

**Comment by vitaut** [comment]
Thanks for the confirmation. Note that the `master` branch will temporary revert to the old handling of functions (which breaks interfile links) soon, due to work on Sphinx 1.3 support so I recommend using specific revision like https://github.com/michaeljones/breathe/commit/38a29571e54b265a7c1f519bb5d27b7907df7a2d.
