### ISSUE TITLE
Is it possible to display inheritance relationship?

### ISSUE THREAD

**Issue by rweickelt** [michaeljones/breathe#174]
Hi,

Is it possible to show base types of a class and to control their visibility (all, public, protected, private, name)?

If not, the doxygen XML output contains the necessary information in the form:

```javascript
<doxygen>
  <compounddef id="xxx" kind="class" prot="public">
    <compoundname>name</compoundname>
    <basecompoundref refid="baseid" prot="public" virt="non-virtual">base-name</basecompoundref>
```
A quick search in the documentation did not bring up a result.

Many thanks.

**Comment by michaeljones** [comment]
Hi @rweickelt 

Thanks for raising this. I don't think Breathe supports this at the moment. 

Could you give a quick text-based example of what you'd expect to see? A list of base classes in the body of the class documentation or a code style `: public BaseClass` after the declaration? (Assuming C++.)

@vitaut is doing some great work which means Breathe is using Sphinx style declarations for class names and other things like that which might make it harder for us to customise them and add base classes and things so it might benefit from being slightly separate from the actual `class MyClass` bit.

Any and all thoughts & suggestions are welcome though,
Michael

**Comment by vitaut** [comment]
Python's [`autoclass` directive](http://sphinx-doc.org/ext/autodoc.html#directive-autoclass) has `show-inheritance` options for this purpose. Perhaps we can add something like that. For now I've been adding links to base classes manually, see http://mp.readthedocs.org/en/latest/nl.html#mp::NLHeader for example.

**Comment by rweickelt** [comment]
Vitaut: Impressive documentation... Hm, I agree that an explicit list of parent classes is a reasonable way to achieve a useful and readable documentation. Just showing any base class is not always wanted, so one would likely have to filter either.

I think I'll stick to hand crafting.


----- Original message -----

**Comment by vitaut** [comment]
Thanks. I'm glad that my suggestion of manually listing base classes works for you.

**Comment by ela34** [comment]
I vote to add support for providing an automatic mode to show base classes.
Maintaining manually such an inheritance tree is quiet complex and defeating the purpose of having all the documentation information extracted from the source code.

**Comment by xaqq** [comment]
On a related note, is it possible to easily include inheritance and/or collaborations diagrams generated by doxygen if the correct option are set (`HAVE_DOT`) ?

**Comment by michaeljones** [comment]
There is some support for this now. More information in #220. Happy to merge it into `master` if people are happy with the output.
