### ISSUE TITLE
sphinx-autogen equivalent

### ISSUE THREAD

**Issue by michaeljones** [michaeljones/breathe#18]
A nice little side project would be to create a sphinx-autogen equivalent. Something that will generated the appropriate rst stub files with breathe directives for different classes/files/functions/etc.

Happy to advise if anyone would like to contribute,
Michael

**Comment by ishitatsuyuki** [comment]
Checkout #241 for a beta implementation.

**Comment by vitaut** [comment]
@michaeljones Perhaps this issue can be closed now since the new `breathe-apidoc` script is exactly

> Something that will generated the appropriate rst stub files with breathe directives for different classes/files/functions/etc.

or is it missing some functionality that you had in mind?

**Comment by melvinvermeeren** [comment]
I do indeed believe that `breathe-apidoc` is what OP describes. Closing for now, comment if you disagree.
