### ISSUE TITLE
Remove entries for undocumented C++ classes

### ISSUE THREAD

**Issue by ela34** [michaeljones/breathe#183]
Currently using breathe undocumented C++ classes are indexed and appear in the generated documentation. I do not know if this is done on purpose, but it will be very useful to have an option to remove undocumented C++ classes from the generated documentation

**Comment by michaeljones** [comment]
Hi,

Thanks for reporting this. I can't look into it until next week but it seems worth investigating! 

My only thought is, as Breathe only documents what is in the XML, is it possible to have doxygen leave undocumented classes out of the XML it produces? Perhaps that is an option and easier than handling it in Breathe? I can't remember clearly though and don't have a set up right now to investigate.

Cheers,
Michael

**Comment by ela34** [comment]
Hi Michael,

I have tried to ask Doxygen to leave undocumented classes out of the XML but based on my experiments doxygen puts everything in the XML. It is only when you use doxygen to generate a specific output (like HTML) that you can specify through a config directive to remove undocumented members and classes. So it seems that it has to be done in Breathe.


Also I have installed Brethe 4.0.0 and I got an error (on Windows) when using it. I had to add a ‘type_’ variable in enumvalueTypeSub function (in bold below) to get it to work. I’m not sure that this is the right thing to do, but it is not crashing anymore.

class enumvalueTypeSub(supermod.enumvalueType):

    node_type = "enumvalue"
    type_ = None
    def __init__(self, prot=None, id=None, name='', initializer=None, briefdescription=None,
                 detaileddescription=None, mixedclass_=None, content_=None):
        supermod.enumvalueType.__init__(self, mixedclass_, content_)

        self.initializer = None


Best regards.

-- Eric

**Comment by michaeljones** [comment]
Thanks for clarifying that and for the other bug. I'm not sure exactly what the best fix is right now but I'll try to look into it and let you know.

**Comment by michaeljones** [comment]
Hi @ela34,

Can I just check your use case? Are you using `doxygenindex` for everything? Or something more specific? The `doxygenclass` output as support for not displaying undocumented members but it seems like we haven't given it much thought else where in the system. 

Cheers,
Michael

**Comment by melvinvermeeren** [comment]
According to
https://www.stack.nl/~dimitri/doxygen/manual/config.html#cfg_extract_all
`EXTRACT_ALL=NO` should prevent Doxygen from extracting undocumented entities.

Perhaps this once was a bug with Doxygen upstream, I don't know. Tagging it as support to be safe.

Closing for now, if the issue still exists please comment.
