### ISSUE TITLE
Automatic source listings?

### ISSUE THREAD

**Issue by mikepurvis** [michaeljones/breathe#202]
I don't have a lot of understanding how much control Breathe has over Sphinx, but would it be possible to have it automatically generate a Sphinx page for each documented source file? With such an option in use, could directives like `doxygenclass` automatically link to the implementation's page and line?

**Comment by vitaut** [comment]
@mikepurvis Does Sphinx itself support dynamically generated pages?

**Comment by mikepurvis** [comment]
I believe so, based on the existence and behaviour of `sphinx.ext.viewcode`:

http://sphinx-doc.org/latest/ext/viewcode.html#module-sphinx.ext.viewcode

The key stuff is `sphinx.addnodes`, I believe:

```
            pagename = '_modules/' + modname.replace('.', '/')
            onlynode = addnodes.only(expr='html')
            onlynode += addnodes.pending_xref(
                '', reftype='viewcode', refdomain='std', refexplicit=False,
                reftarget=pagename, refid=fullname,
                refdoc=env.docname)
```

https://bitbucket.org/birkenfeld/sphinx/src/40bd03003ac6fe274ccf3c80d7727509e00a69ea/sphinx/ext/viewcode.py?at=default#cl-93

**Comment by vitaut** [comment]
I don't see any reason Breathe couldn't do the same, but as always the question is whether there is someone interested in implementing this feature =). Would you be willing to contribute?

**Comment by melvinvermeeren** [comment]
`breathe-apidoc` exists nowadays, which does exactly that.
