### ISSUE TITLE
Template params style kinda dull

### ISSUE THREAD

**Issue by mikepurvis** [michaeljones/breathe#203]
See:

<img src="https://cloud.githubusercontent.com/assets/944666/8164516/8900ce92-1357-11e5-8a4e-cafe011a94fc.png" width="300" />

Not sure what would be best here, but at least `template` and `class` should be in italics, I think.

**Comment by vitaut** [comment]
I agree, `template` and the first `class` keyword should have the same styling as the second `class` keyword. Should be pretty easy to do and I can look into it when time permits (patches are welcome too =)).

**Comment by vitaut** [comment]
`template` and `class` are now rendered as other keywords (italics by default, but this can be changed with CSS). See for example http://breathe.readthedocs.org/en/latest/class.html#template-specialisation-example.
