### ISSUE TITLE
Rename LICENSE file

### ISSUE THREAD

**Issue by daveisfera** [michaeljones/breathe#207]
Currently, the file is name LICENCE (the verb form) and LICENSE (the noun form) is the more common name of the file.

**Comment by michaeljones** [comment]
In my defense, I'm British and I think it is the other way around here :) Happy to change though as I assume American English the language of open source & the internet.

Thanks for pointing it out. I'll adjust it shortly!

**Comment by daveisfera** [comment]
No worries. I went back and forth for like 10 minutes before deciding if this issue was worth even bringing up or not. Thanks for the quick response.

**Comment by michaeljones** [comment]
Renamed :) Thanks for the extra comment. These things can slip mind my sometimes!
