### ISSUE TITLE
Remove Python env in non-executable files

### ISSUE THREAD

**Issue by daveisfera** [michaeljones/breathe#208]
A few of the Python files have a Python env in the shebang line even though they're not executable. The files that need to have this removed is:
parser/doxygen/compound.py
parser/doxygen/compoundsuper.py
parser/doxygen/index.py
parser/doxygen/indexsuper.py

I have a patch to remove the top 2 line from each of these files, but apparently there's no way to attach a patch in github.

**Comment by michaeljones** [comment]
Cheers for the heads up. That is a little embarrassing but harmless I guess. I'll try to remove them shortly :) Thanks again!

**Comment by daveisfera** [comment]
I only noticed because rpmlint noticed it when I was working on packaging everything and I was just trying to be a good citizen and flow the fix I did upstream. Thanks again for the quick response.

**Comment by michaeljones** [comment]
I appreciate you taking the time to give feedback. I've just stripped them out and pushed. Thanks again!
