### ISSUE TITLE
Real life example

### ISSUE THREAD

**Issue by MatthiasKauer** [michaeljones/breathe#209]
Hi,
I'm interested in using sphinx for my C++ project. I've heard good things about it, but I'd like to take a look at a real life example before I  take the plunge. 
If someone could point me to docs that he generated with sphinx+breathe that would be great :)

I hope I'm not coming across as overly demanding here.

Kind regards,
Matthias

**Comment by vitaut** [comment]
C++ Format API reference: http://cppformat.github.io/dev/api.html

**Comment by kirbyfan64** [comment]
https://github.com/michaeljones/breathe/tree/master/examples

Breathe's own docs are written using Sphinx, also.

**Comment by michaeljones** [comment]
It is a good question. We'd love to link out to more examples of it in use but unfortunately we don't have many people sharing them. I'm very grateful for @vitaut example which is looking really awesome in my opinion. Hopefully we'll gather more over time.

**Comment by MatthiasKauer** [comment]
Thanks so much all of you!
C++format as pointed out by @vitaut is indeed a great example!
