### ISSUE TITLE
C++11 using directives are not handled correctly

### ISSUE THREAD

**Issue by kirbyfan64** [michaeljones/breathe#213]
[An example.](https://github.com/kirbyfan64/cppexpat/blob/master/cppexpat.hpp#L59) It gives a warning and outputs:

```
typedef using cppexpat::PinstrCallback = typedef std::function<void(string,string)>
```

**Comment by kirbyfan64** [comment]
Rendered output at
http://cppexpat.readthedocs.org/en/latest/#_CPPv28cppexpat.

**Comment by kirbyfan64** [comment]
That's not the only thing weird about those docs. See the section `file cppexpat.hpp`. All the includes are on one line.

**Comment by kirbyfan64** [comment]
...and half the classes in the `cppexpat` namespace are placed in the global namespace. Except for the broken typedefs. ???

**Comment by Luthaf** [comment]
I also have this bug, in a slightly different context:

```
WARNING: Type must be either just a name or a typedef-like declaration.
Just a name error: Invalid definition: Expected identifier in nested name, got keyword: using [error at 5]
  using chemfiles::Format::file_t =  BasicFile
  -----^
Typedef-like expression error: Invalid definition: Expected identifier in nested name, got keyword: using [error at 5]
  using chemfiles::Format::file_t =  BasicFile
  -----^
```

**Comment by jakobandersen** [comment]
If the 'using' part is stripped before the declaration is sent to Sphinx, then it should work (unless Sphinx has a bug as well).

**Comment by vitaut** [comment]
Fixed in https://github.com/michaeljones/breathe/commit/2a03825187e6919e77c27e1bf531d7f12672b021.
