### ISSUE TITLE
Passing config file options to Doxygen with autodoxygenindex

### ISSUE THREAD

**Issue by kirbyfan64** [michaeljones/breathe#214]
Right now, it is seemingly impossible to pass custom config options to `autodoxygenindex`'s config file template, making it impossible to, for instance, add an [EXCLUDE_SYMBOLS](http://stackoverflow.com/a/3733023/2097780) directive.

My idea is to have something like:

```
.. autodoxygenindex::
   :project: abc
   :config: ABC=124
```

but that might not work. I can try a PR of you'd like.

**Comment by michaeljones** [comment]
Hi,

Thanks for the various issue reports. Kind of you to take the time. 

If you would like to try to tackle this one, we'd be very grateful for the contribution. I would be tempted to suggest that the additional config variables should go into the `conf.py` file somehow? As a dictionary associated with the project name perhaps? Unless you feel there is a strong case for writing them into the reStructuredText?

Thanks again,
Michael

**Comment by kirbyfan64** [comment]
@micaeljones Yeah, `conf.py` would likely be much better. I'll try to tackle it.
