### ISSUE TITLE
Error when parsing function declaration (function signature)

### ISSUE THREAD

**Issue by guyguy333** [michaeljones/breathe#218]
Hi,

Generating documentation using Breathe for the following function:

``` cpp
template<typename F>
void allow(F* f, typename functionSignature<F, B, G!=1>::tt_type tt)
```

result in:

``` bash
WARNING: Error when parsing function declaration:
If no return type {
Invalid definition: Expected identifier in nested name, got keyword: void [error at 4]
  void MyClass< A, B, G, C, D, E >::allow(F * f, typename  functionSignature < F, B, G!=1 >:: tt_type tt)
  ----^
} else if return type {
Invalid definition: Expected ">" or "," in template argument list. [error at 212]
  void MyClass< A, B, G, C, D, E >::allow(F * f, typename  functionSignature < F, B, G!=1 >:: tt_type tt)
  --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------^
}
```

Any ideas ?

Thank you

**Comment by michaeljones** [comment]
Hi, sorry for the slow response. Thanks for trying Breathe and sorry that you've encountered this issue! 

As Breathe hands the function signatures over to Sphinx's C++ handling code for parsing and display, my guess is that is the Sphinx code isn't designed to handle the `G!=1` part of your function signature. I will attempt to investigate further.

Cheers!
Michael

**Comment by r2d2leboss** [comment]
Hi Michael,

No worry and thank you :)
If you need more information, please, let me know.

Guillaume

**Comment by guyguy333** [comment]
Hi Michael,

No worry and thank you :)
If you need more information, please, let me know.

Guillaume

**Comment by vitaut** [comment]
@jakobandersen, I tried 

```rst
.. cpp:function:: template <typename F> \
                  void allow(F* f, typename functionSignature<F, B, G!=1>::tt_type tt)
```

with Sphinx 1.4 but it still gives a warning

```
 WARNING: Index id generation for C++ object "template<typename F> void allow(F *f, typename functionSignature<F, B, G!=1>::tt_type tt)" failed, please report as bug (id=_CPPv2I0E5allowP1FN17functionSignatureI1F1BXG!=1EE7tt_typeE).
```

Shall I open an issue in Sphinx?

**Comment by jakobandersen** [comment]
Thanks for bringing it up. I have opened an issue.

**Comment by jakobandersen** [comment]
This issue is now fixed in Sphinx.

**Comment by melvinvermeeren** [comment]
Fixed upstream according to above comments. Thanks for keeping this issue up-to-date @jakobandersen.
