### ISSUE TITLE
empty function description causes formatting issue in LaTeX output

### ISSUE THREAD

**Issue by EricFromCanada** [michaeljones/breathe#226]
I've found one issue with breathe's latex output when (for example) a function's docstring lists parameters, but no description. This can be seen by modifying breathe's own docs. Here's a demo: 
1. in `examples/dosygen/structcmd.h`, delete the entire brief for `int open`, leaving the two param descriptions.
2. run `make` at the top level. 
3. open the PDF in `documentation/build/latex` and check the output under section 2.2.2. This is what I see: 

![latex output issue](https://cloud.githubusercontent.com/assets/3324775/11305944/339ef148-8f7d-11e5-83b3-cf5d9b1792df.png)

The TeX output for the affected section looks like this: 

```
\begin{fulllineitems}
\pysiglinewithargsret{int \code{}\bfcode{open}}{\strong{const} char *\emph{pathname}, int \emph{flags}}{}
\begin{description}
\item[{\textbf{Parameters}}] \leavevmode\begin{itemize}
\item {} \code{pathname} - 
The name of the descriptor. 
```

This code exposes a long-standing issue in LaTeX where a `{list}` (produced by `{fulllineitems}`) containing an `\item` (produced by `\pysiglinewithargsret`) with a body starting with something other than a paragraph will not be aligned properly. 

Sphinx already has code to deal with this. In latex.py, `visit_desc_content` contains this code:

```
        if node.children and not isinstance(node.children[0], nodes.paragraph):
            # avoid empty desc environment which causes a formatting bug
            self.body.append('~')
```

which would normally append a tilde (for a non-breaking space) to the `\pysiglinewithargsret` line, fixing the issue. However, it isn't run because, as far as I can tell, the original doctree still has a paragraph with no content placed before the list of parameters, despite the lack of text in the source file read by doxygen. 

Ideally, this could be fixed by only adding that paragraph to the doctree if it contained content, allowing Sphinx's code to run when it does not.

**Comment by melvinvermeeren** [comment]
Appears to have been silently fixed.

With `structcmd.h` like this:

![screenshot_20180603_213603](https://user-images.githubusercontent.com/5957454/40890426-1ec289dc-6776-11e8-844a-6d3c6c11d49b.png)

The output is this:

![screenshot_20180603_213459](https://user-images.githubusercontent.com/5957454/40890420-f908bbc6-6775-11e8-8e05-5c98b886b325.png)

Not sure if fixed in LaTeX or Sphinx, but will close this and tag as upstream issue.
