### ISSUE TITLE
Related project: sphinxcontrib.autodoc_doxygen

### ISSUE THREAD

**Issue by rmcgibbo** [michaeljones/breathe#227]
I just started a new project that also bridges between Doxyen XML and Sphinx. The URL is here: https://github.com/rmcgibbo/sphinxcontrib-autodoc_doxygen. It by no means has the complete feature set of Breathe, but it does include an `autosummary` equivalent (cc #186).

**Comment by michaeljones** [comment]
Hi! Thanks for the heads up. I'll add it to the list of alternatives. I'd love it if you could provide some info on why you chose to start a new project? Is the Breathe code too unapproachable? Do you feel there is a better way to tackle the problem? Did you just like the idea of giving it a go yourself? (There is always an appeal to starting from scratch!) No trouble if you don't feel like explaining but it would be interesting to know.

**Comment by rmcgibbo** [comment]
No problem! I guess it's mostly the first. I wanted to try to add a `sphinx.ext.autosummary`-like feature to breathe, but I honestly I couldn't figure out how the code worked or how to hack on it. And then I started reading through the `sphinx.ext.autodoc` and `sphinx.ext.autosummary` code, and it seemed pretty straightforward to extend, so I tried to build off those.

**Comment by michaeljones** [comment]
Thanks for the run down. I'm becoming increasingly aware that the Breathe code base could be more approachable. I will try to take steps over time to improve that.
