### ISSUE TITLE
How to document a class inside a namespace?

### ISSUE THREAD

**Issue by kratsg** [michaeljones/breathe#228]
Example:

```c++
namespace Foo {
  class Bar {}
};
```

and I can't get Breathe to find this at all using the standard concepts

```
.. doxygennamespace:: Foo
   :members:
   :undoc-members:
   :protected-members:
   :private-members:
```

will provide the namespace and treat all of `Bar`'s functions as... functions of the namespace instead... while

```
.. doxygenclass:: Foo::Bar
   :members:
   :undoc-members:
   :protected-members:
   :private-members:
```

has Breathe complaining that it cannot find the class.

**Comment by kratsg** [comment]
Never mind -- it looks like I needed to bump up my doxygen version. For some reason, doxygen was skipping it. I've fixed it on my end. Sorry for the noise!

**Comment by michaeljones** [comment]
Thanks for figuring it out and letting us know. I've been caught out by old Doxygen versions before but I certainly wouldn't have thought to ask about it. Cheers for using Breathe!
