### ISSUE TITLE
Source code documentation showing up?

### ISSUE THREAD

**Issue by kratsg** [michaeljones/breathe#232]
I've tried a lot of variations. Let's say I document my header files correctly and they show up just fine.

I'd like to also add some extra documentation about implementation-specific details in the source code (maybe like a brief snippet or two) -- but I can't get this to show up via Breathe when generating Sphinx documentation?

**Comment by michaeljones** [comment]
Hi,

Breathe ignores implementation files for function documentation otherwise it gets confused between the header and the implementation file. There is some information here: 

http://breathe.readthedocs.org/en/latest/directives.html#confval-breathe_implementation_filename_extensions

But you should see doxygen comments from the implementation file still as doxygen merges them into the header file docs.

The main question here is: do the comments that you're after make it into the doxygen xml files? If they are there then we should find a way to get Breathe to display them. If they aren't there then there isn't much we can do about it in this project.

I'm a little confused as to whether you mean doxygen style comments in the implementation file or just general comments in the main body of functions, etc.

Thanks for raising this and for using Breathe,
Michael

**Comment by kratsg** [comment]
Hi Michael,

So it looks like if I was using really simple comments such as

```
/// Line 1
/// Line 2
/// Line 3
```

these seem to make it into the sphinx documentation at the end... and merged. However, what seems strange is when I want to do something like

```
/**
  @brief Info struct
*/
struct Info {
  int a;
  int b;
  void initialize();
}
```

and then

```
/**
  @var Info::a we search for "foo" when doing this
  @var Info::b we do something with "boo" when doing this
*/
Info::initialize(){
  a = do_something_interesting("foo");
  b = also_something_interesting_too("bar");
}
```

which is supported by Doxygen, and this doesn't seem to make it into breathe -- but I do see it in the XML files. Presumably, this should add the documentation to the `int a` and `int b` variables defined in the header...

No problem!

Giordon

**Comment by michaeljones** [comment]
Cheers for the run down. It sounds like it is something that Breathe should handle. If you have time, please provide a pull request with some example code added to the 'examples/specific' directory. I'll try to take a look when I can.

Thanks!

**Comment by michaeljones** [comment]
ps. Thanks for sharing the link to your project. I always appreciate seeing examples of it in action.

**Comment by vitaut** [comment]
@kratsg XML generated by Doxygen doesn't contain the description of `Info::initialize`, so I suggest reporting it there. Breathe will render it if you add `:undoc-members:`

```rst
.. doxygenstruct:: Info
   :undoc-members:
```
but that's pretty much all we can do without Doxygen generating proper XML.

**Comment by mgiaco** [comment]
Hello,
I have the same problem so I will ask here in this issue I hope it is no problem. 

As an example if I had this function in a C source file.

```C
/*! \fn void theBestFunction(int)
 * I'm the best blah blah blah
 */
 void theBestFunction(int ever)
 {
    doThings();
    /*! Does some more things
     */
    doMoreThings();
    /*! Checks that the things it does are the best
     */
    checkBest();
}
```

and this in my C header file.
```C
/**
 * @param ever param ever is forever
 */
extern void theBestFunction(int ever);
```
I also didn´t get the source code documentation showing up with breathe. On my build process, I always build XML and HTML from doxygen, so everything looks fine in the HTML output.

So I searched for this two strings in the XML output and I can found them so I think there is a problem with breathe or what I am doing wrong here?

thanks

**Comment by vitaut** [comment]
@mgiaco Make sure that the function name in `doxygenfunction` is correct and check for warnings when running sphinx.

**Comment by mgiaco** [comment]
@vitaut So I think everything is correct. So I get an output but do not see the 2 Strings "Dose some more things" and "Checks that the things it does are the best" 
I do not get any build warning and in the HTML out from Doxygen I can see that strings.

**Comment by vitaut** [comment]
Could you post the Doxygen XML output?

**Comment by melvinvermeeren** [comment]
Based upon answers so far and inactivity I will secretly assume this has been resolved.

In case you still have issues please comment or open a new issue.
