### ISSUE TITLE
Breathe and the Sphinx C++ domain

### ISSUE THREAD

**Issue by jakobandersen** [michaeljones/breathe#242]
I just saw that I once again broke Breathe (#239) due to some internal changes of the C++ domain (sorry). If you are interested then maybe I could add some explicit hooks in the C++ domain for the functionality Breathe needs?

**Comment by michaeljones** [comment]
Hi, thanks for the thought. I'm afraid I don't know how significant Breathe is in the Sphinx community. I wouldn't want to impose and I guess we're relying on internal APIs for some of the functionality. @vitaut should probably weigh in here as he is more connected with the current use of Breathe than I am.

We'd certainly be happy if it was a bit more stable but only if everyone is ok with the idea.

**Comment by vitaut** [comment]
Thanks, @jakobandersen. I think it would be great to have some kind of hooks in the C++ domain that we could use instead of the internal APIs. Currently we extend the nodes generated by the Sphinx C++ domain in the following way:

1. Insert a target (anchor) with the ID generated by Doxygen.
2. Modify the main signature node adding qualifiers and keywords like `virtual`, etc.
3. Add description to the content node.

For example:

```python
        node = nodes[1]
        # Templates have multiple signature nodes in recent versions of Sphinx.
        # Insert Doxygen target into the first signature node.
        node.children[0].insert(0, self.create_doxygen_target())
        # Update the last signature node because it contains the actual signature
        # rather than "template <...>".
        self.update_signature(node.children[-2])
        # Add description to the content node.
        node.children[-1].extend(self.description())
```
where `nodes` are Sphinx nodes obtained by running a cpp domain directive. Obviously this is rather fragile. One way to make it more robust is by locating the nodes we need by tags rather than by position, but ideas of how to improve this are welcome.

**Comment by jakobandersen** [comment]
As long as any changes are confined to the C++ domain, then I am happy to help make thing less fragile.
A tag on each line in a signature sounds like a good idea (assuming one is allowed to add new attributes to docutil nodes?). I'll try to add this soon.
Regarding 2: this seems a bit odd. Is this due to previous missing support in Sphinx?

**Comment by vitaut** [comment]
Actually the nodes already have tags and we check them in some places:

```python
        if signode[0].tagname != 'desc_name':
```
Do you think we can rely on these, @jakobandersen?

If yes, then I can try reimplementing the fragile code that relies on node positions with explicit matching of tag names.

As for item 2, this is indeed for compatibility with older version of Sphinx.

**Comment by jakobandersen** [comment]
I'm not familiar with the internals of docutils, but after a quick look at their nodes.py file it seems that ``tagname`` is heavily used for internal logic, so we can't change it. Each line is created the same way so they will have the same tagname (``desc_signature``).

I tried adding a ``sphinx_cpp_tagname`` attribute to the signature nodes in jakobandersen/sphinx@0508d3d5b63f5576d06789ad8b6be1b8c37caccf.
The main line should have 'declarator' as tag, so the code from #239 could become something like the following (I haven't set up to test Breathe changes yet).
```Python
        for signode in node.children:
            try:
                tag = signode.sphinx_cpp_tagname
            except AttributeError:
                continue
            if tag = 'templateParams':
                pass
            elif tag = 'declarator':
                # Insert Doxygen target
                signode.insert(0, self.create_doxygen_target())
                # Update the actual signature
                self.update_signature(signode)
            else:
                # Unknown signature node
                pass
        # Add description to the last node, the content node.
        node.children[-1].extend(self.description())
```

**Comment by vitaut** [comment]
Thanks @jakobandersen, the `declarator` tag should do the trick.

**Comment by jakobandersen** [comment]
Great, I'll merge it into stable Sphinx as soon as possible.

**Comment by jakobandersen** [comment]
In PR #243 @ishitatsuyuki mentions an issue with rendering typedefs and type aliases. Sphinx renders type declaration as follows:
- ``.. cpp:type:: Type``         as   "_type_ Type" (for a type alias of unspecified type)
- ``.. cpp:type:: int Type``    as "_type_ int Type"
- ``.. cpp:type:: Type = int`` as "_type_ Type = int"

I never got around to change it so they use the respective prefixes "_type_", "_typedef_", and "_using_" instead of "_type_". Would such a change incidentally fix the issue in Breathe?
Otherwise, would it help with a ``sphinx_cpp_tagname`` attribute here as well?

**Comment by vitaut** [comment]
> Would such a change incidentally fix the issue in Breathe?

Yes, this should fix the issue. Currently we have to change `type` to `typedef` ourselves.

**Comment by jakobandersen** [comment]
Both the signature line tags and the type declaration rendering changes are in Sphinx stable, so it will be in version 1.4.1. Let me know if the changes don't work as expected.

**Comment by vitaut** [comment]
Awesome, thanks a lot @jakobandersen! I've just checked https://github.com/sphinx-doc/sphinx/commit/c6ba3093fe0dd258c8c8e2ded9af2c9d2d3181b6 and the changes work as expected on our side.

**Comment by vitaut** [comment]
@jakobandersen One more minor thing: is it possible not to strip parentheses in

```rst
.. c:macro:: FOO()
```

**Comment by jakobandersen** [comment]
The C domain is at the moment completely disjoint from the C++ domain, and it seems that the parsing in the C domain could use an overhaul in general. When I find time I will try to make some incremental improvements. There are no tests for the C domain in Sphinx yet, but do you happen to know of any projects using it? (directly or via Breathe).

**Comment by vitaut** [comment]
Thanks. Here's one project that uses the C domain via Breathe: http://lassoguide.com/api/lcapi-reference.html

**Comment by melvinvermeeren** [comment]
I am happy to see many people here are still taking care of Breathe today! :)

Closing for issue tracker cleanup.
