### ISSUE TITLE
Cannot get property type from c# doxygen generated (C# support in general)

### ISSUE THREAD

**Issue by ms92ita** [michaeljones/breathe#249]
Hi all,

i have generated documentation from doxygen and it has been created correctly, but when i create html (with command "make html") from sphinx and i have created a .rst with a doxygenclass directive like this:

.. doxygenclass:: myclass
   :members:
   :undoc-members:

I have noticed that, for properties, it hasn't been included the property type. For example:

`property primarykey`

when it must look like this:

`property int primarykey`.

Am I doing something wrong?

Thanks in advance

**Comment by ms92ita** [comment]
If you need some other infos, when I try to call make, for each property i have this warning:

`D:\appendix\classes.rst:4: WARNING: Error in declarator or parameters and qualifiers
If pointer to member declarator:
  Invalid definition: Expected identifier in nested name. [error at 62]
    Namespace:For::MyClass::MyProperty
    --------------------------------------------------------------^`

The property is declared like this
`public int MyProperty {get; set; }`

**Comment by vitaut** [comment]
[Sphinx](http://www.sphinx-doc.org/en/stable/index.html) doesn't have a C# domain and Breathe falls back to the C++ domain in this case. The latter obviously doesn't know anything about C# properties, thus the error. Fixing this would require adding a new domain or implementing rendering of C# declarations in Breathe which will require substantial amount of work and I don't think it will happen any time soon.

**Comment by ms92ita** [comment]
Ok, so if I implement a domain that "converts" the c# declaration pattern in c++ pattern in breathe or doxygen, can i escape that?
Is it an other solution modifying the doxygen output (after build) to satisfy the c++ domain with a xsl transformation?

**Comment by vitaut** [comment]
The domain doesn't convert a declaration in one language into another. It should parse the declaration and do the necessary processing such as generating a target (anchor) and rendering parts of the declaration. However, converting Doxygen representation (either XML or parsed) into the form that Breathe and Sphinx C++ domain can understand might be a viable workaround.

**Comment by ms92ita** [comment]
It seems that sphinx have some problems parsing the properties becuase, if I declare a single member or function, it takes the type but not for properties. I don't want to modify my source code and I don't know the workflow of sphinx, so is it possible to have a working example with a programming language that supports property type and views the type in breathe or sphinx documentation?

**Comment by noname77** [comment]
second that. has anyone come up with a solution?

**Comment by melvinvermeeren** [comment]
Current Sphinx does not have an official C# domain according to http://www.sphinx-doc.org/en/stable/domains.html.

I do notice @djungelorm has been working on https://github.com/djungelorm/sphinx-csharp. I haven't checked details but perhaps this could be used for the Sphinx side.

Support for the `sphinxcontrib-phpdomain` was recently merged with #351. This might serve as some sort of example for how to add support to Breathe for other domains.

**Comment by cadop** [comment]
Is this closed? In https://github.com/michaeljones/breathe/issues/422 it says this issue will be used to track c# support. 

Also, there are multiple references to the custom C# domain of sphinx. However, I can't find any information relating to how that domain would be used by breathe.  Any guidance here?

**Comment by vermeeren** [comment]
@cadop The only potentially useful thing I know of would be the PHP domain, a link to that PR is in my previous comment here.

**Comment by rogerbarton** [comment]
I've been working on this and I've started a PR #550
