### ISSUE TITLE
breathe ignores <linebreak/> in doxygen xml

### ISSUE THREAD

**Issue by CFGrote** [michaeljones/breathe#253]
hi,
in my doxygen generated xml i have this block:

    ...
    <para>Constructor for the <ref refid="dd/de8/classSimEx_1_1Parameters_1_1PlasmaXRTSCalculatorParameters_1_1PlasmaXRTSCalculatorParameters" kindref="compound">PlasmaXRTSCalculatorParameters</ref>. </para>         </briefdescription>
        <detaileddescription>
    <para><parameterlist kind="param"><parameteritem>
    <parameternamelist>
    <parametername>elements</parametername>
    </parameternamelist>
    <parameterdescription>
    <para>The chemical elements in the scattering target. <linebreak/>
    <bold>type</bold> list [[element symbol, stochiometric number, charge], ...] <linebreak/>

However, my sphinx output (using breathe to render the doxy xml) looks like this:
![screenshot from 2016-04-07 13 20 03](https://cloud.githubusercontent.com/assets/15476807/14349457/7cb6d93c-fcc3-11e5-85ee-fdb90ea6d766.png)

Obviously the xml linebreak is not observed. Same for latexpdf.

I tried replacing the linebreak tag by &#xD; and other symbols (\n br/) to no avail.

Am I missing something obvious or is it really not possible to insert linebreaks?

**Comment by vitaut** [comment]
Should be easy to fix but rendering is being refactored right now, so it's better wait until #252 is resolved.
