### ISSUE TITLE
doxygentodo:: directive

### ISSUE THREAD

**Issue by dnelson86** [michaeljones/breathe#258]
Thanks for this great project, I am just starting to use it. I've just also ran into this issue (see #143) of wanting to have support for the `todo.xml` output of Doxygen.

For me, a `doxygentodo::` directive which simply listed them (all) out would be perfect.

Adding this feature request as its own issue since the previous one was closed.

**Comment by t-b** [comment]
+1

**Comment by OliverEvans96** [comment]
+1

It seems that Sphinx already has its own todo extension: http://www.sphinx-doc.org/en/stable/ext/todo.html. I wonder how straightforward it would be to bridge the two?

**Comment by heitorPB** [comment]
Did you find any workaround for this? Currently I generate the doxygen html only for the TODO list...

**Comment by utzig** [comment]
This was implemented by #596.  To import the todo.xml just use `.. doxygenpage:: todo`. More documentation: https://breathe.readthedocs.io/en/latest/directives.html#doxygenpage
