### ISSUE TITLE
Name of the group is not correct

### ISSUE THREAD

**Issue by mgiaco** [michaeljones/breathe#262]
Hello,

If I use this in my header:

```
/**
 * @defgroup group1 Define Groups
 * @addtogroup group1
 * @{
 */
#define DEF1    1 /**<define 1*/
#define DEF2    2 /**<define 2*/
#define DEF3    3 /**<define 3*/
/**
 * @}
 */
```

I get this Output from Doxygen: 

![issue](https://cloud.githubusercontent.com/assets/4886904/15644445/707b20a6-2653-11e6-8bab-ec02d664dbeb.JPG)

And with sphinx / breathe using this rst:

```
.. doxygengroup:: group1
   :project: test
```

I get this Output:

![issue1](https://cloud.githubusercontent.com/assets/4886904/15644488/ab5565f6-2653-11e6-829e-dd3b764fb6f9.JPG)

Is there a way to get the name " Define Groups" instead of "group1" in the breath output?
Why is there a "Defines" string in this output - is there a way to remove that?

thanks

**Comment by michaeljones** [comment]
Sorry for never replying to this. I'm not sure off the top of my head but I'd hope that it should not be too hard to fix this. It certainly isn't ideal at the moment. I will attempt to look into it to see if it should be an easy fix.

**Comment by mgiaco** [comment]
Hey thanks, no problem :-)

**Comment by melvinvermeeren** [comment]
Confirmed this still exists with current release. Indeed should not be too hard to fix.

**Comment by melvinvermeeren** [comment]
Closing as duplicate in favour of #201, which is older. Some implementation clues have been given in that issue already.
