### ISSUE TITLE
Duplicate ID error

### ISSUE THREAD

**Issue by bluescarni** [michaeljones/breathe#266]
I am trying to adopt breathe for a C++ project which uses modern C++ techniques, and I am running into some issues. The project is here:

https://github.com/bluescarni/piranha

I have created a reduced, self contained test-case exhibiting the issue here:

https://github.com/bluescarni/breathe_bug_00

(first run ``doxygen`` from the doxygen subdir, then ``make html`` from the sphinx subdir)

The issue is the following:

```console
$make html
sphinx-build -b html -d _build/doctrees   . _build/html
Running Sphinx v1.3.5
making output directory...
loading pickled environment... not yet created
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 1 source files that are out of date
updating environment: 1 added, 0 changed, 0 removed
reading sources... [100%] index                                                                                                                                      
/home/yardbird/temp/breathe_bug/sphinx/index.rst:7: SEVERE: Duplicate ID: "add-operator__TCR.UCR".
/home/yardbird/temp/breathe_bug/sphinx/index.rst:7: SEVERE: Duplicate ID: "sub-operator__TCR.UCR".
/home/yardbird/temp/breathe_bug/sphinx/index.rst:7: SEVERE: Duplicate ID: "mul-operator__TCR.UCR".
/home/yardbird/temp/breathe_bug/sphinx/index.rst:7: SEVERE: Duplicate ID: "div-operator__TCR.UCR".
/home/yardbird/temp/breathe_bug/sphinx/index.rst:7: SEVERE: Duplicate ID: "eq-operator__TCR.UCR".
/home/yardbird/temp/breathe_bug/sphinx/index.rst:7: SEVERE: Duplicate ID: "neq-operator__TCR.UCR".
/home/yardbird/temp/breathe_bug/sphinx/index.rst:7: SEVERE: Duplicate ID: "lt-operator__TCR.UCR".
/home/yardbird/temp/breathe_bug/sphinx/index.rst:7: SEVERE: Duplicate ID: "lte-operator__TCR.UCR".
/home/yardbird/temp/breathe_bug/sphinx/index.rst:7: SEVERE: Duplicate ID: "gt-operator__TCR.UCR".
/home/yardbird/temp/breathe_bug/sphinx/index.rst:7: SEVERE: Duplicate ID: "gte-operator__TCR.UCR".
```

All these duplicate IDs refer to overloaded operators in the two classes ``mp_integer`` and ``real``, implemented as inline friend functions. I tried to reproduce the issue with simpler classes, but I could not manage. I have tried with doxygen 1.8.11 in combination with sphinx 1.3 and 1.4, and with the stable and git head of breathe. It does not seem to me like a doxygen problem as even with clang-assisted parsing the breathe issue is still there.

I have other issues popping up in my project, I can keep on submitting new bugreports if you feel like this is worth pursuing.

**Comment by jakobandersen** [comment]
I'm quite sure Breathe is not to blame for this. The duplicates are from an old style of id generation in Sphinx that unfortunately wasn't "unique enough". With the newest Sphinx 'stable' the old ids are skipped if they would be duplicates.

**Comment by bluescarni** [comment]
@jakobandersen Thanks a lot for the reply, I'll give sphinx's master a try.

**Comment by bluescarni** [comment]
@jakobandersen Yes this fixes it, thanks a lot! I will close the issue.
