### ISSUE TITLE
Issue with "using" type definition

### ISSUE THREAD

**Issue by bluescarni** [michaeljones/breathe#268]
Breathe seems unable to deal with certain usages of the ``using`` keyword as a type-definition directive. A self-contained example is available here:

https://github.com/bluescarni/breathe_bug_01

(first run doxygen from the ``doxygen`` subdir, then ``make html`` from the ``sphinx`` subdir)

There is a class template of this form:

```c++
template <int N = 0>
class mp_integer;
```

And a type definition:

```c++
using integer = mp_integer<>;
```

The warnings raised by sphinx:

```console
sphinx-build -b html -d _build/doctrees   . _build/html
Running Sphinx v1.4.4
making output directory...
loading pickled environment... not yet created
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 1 source files that are out of date
updating environment: 1 added, 0 changed, 0 removed
reading sources... [100%] index                                                                                                                               
/home/bluescarni/repos/breathe_bug_01/sphinx/index.rst:12: WARNING: Error in type declaration.
If typedef-like declaration:
  Type must be either just a name or a typedef-like declaration.
  If just a name:
    Error in declarator or parameters and qualifiers
    Invalid definition: Expected identifier in nested name, got keyword: using [error at 5]
      using piranha::integer = typedef mp_integer<>
      -----^
  If typedef-like declaration:
    Invalid definition: Expected identifier in nested name, got keyword: using [error at 5]
      using piranha::integer = typedef mp_integer<>
      -----^
If type alias or template alias:
  Invalid definition: Expected identifier in nested name, got keyword: using [error at 5]
    using piranha::integer = typedef mp_integer<>
    -----^
```

If ``using`` is replaced with a ``typedef``, the warnings go away and the html output is displayed as expected.

**Comment by vitaut** [comment]
Looks like `using integer = mp_integer<>;` is not extracted from Doxygen correctly: `using piranha::integer = typedef mp_integer<>`. At the very least there shouldn't be `typedef`. If you are interested in debugging yourself the typedef processing is here: https://github.com/michaeljones/breathe/blob/c967009da4e9785b274d78aac66793e11c74b2d1/breathe/renderer/sphinxrenderer.py#L938. Otherwise I can have a look myself but it may take a while because I'm rather busy right now.

**Comment by bluescarni** [comment]
@vitaut I am not sure I understand fully. The doxygen XML looks a bit fishy:

```xml
<definition>using piranha::integer = typedef mp_integer&lt;&gt;</definition>
```

The code you pointed me to seems to remove ``using``/``typedef`` from the declaration string, then set an ``obj_type`` variable and finally call ``self.render_declaration()``.

I tried a couple of things like turning the ``using`` into a ``typedef`` (which was just a hack to see if I was getting somewhere :) ) but didn't manage to achieve much. Should I look in ``visit_typedef()`` or elsewhere?

**Comment by vitaut** [comment]
Ah, then it is a Doxygen bug. I recommend trying the latest version of Doxygen and if it still gives this nonsense
```xml
<definition>using piranha::integer = typedef mp_integer&lt;&gt;</definition>
```
report the issue to them.

**Comment by bluescarni** [comment]
@vitaut Thanks for the input, I reported the issue here:

https://bugzilla.gnome.org/show_bug.cgi?id=767825

**Comment by bluescarni** [comment]
@vitaut I am still waiting on that doxygen bug, but in the meantime I tried to replace

```xml
<definition>using piranha::integer = typedef mp_integer&lt;&gt;</definition>
```

with

```xml
<definition>using piranha::integer = mp_integer&lt;&gt;</definition>
```

But I am still getting the warnings:

```console
/home/bluescarni/repos/piranha/doc/sphinx/reference/piranha/integer.rst:6: WARNING: Error in type declaration.
If typedef-like declaration:
  Type must be either just a name or a typedef-like declaration.
  If just a name:
    Error in declarator or parameters and qualifiers
    Invalid definition: Expected identifier in nested name, got keyword: using [error at 5]
      using piranha::integer = mp_integer<>
      -----^
  If typedef-like declaration:
    Invalid definition: Expected identifier in nested name, got keyword: using [error at 5]
      using piranha::integer = mp_integer<>
      -----^
If type alias or template alias:
  Invalid definition: Expected identifier in nested name, got keyword: using [error at 5]
    using piranha::integer = mp_integer<>
    -----^
```

Is this to be expected and, in such a case, what exactly should appear in the XML?

**Comment by vitaut** [comment]
Which version of Breathe are you using? AFAICS `using` is stripped off before passing to Sphinx in the current `master`:

```python
        elif declaration.startswith(using):
            declaration = declaration[len(using):]
            obj_type = "using"
```

**Comment by bluescarni** [comment]
@vitaut I must have had some version mismatch, as now (after updating again doxy/sphinx/breathe to the latest master and making sure they are all installed properly) I get this error message:

```console
rm -rf _build/*
/home/yardbird/.local/bin/sphinx-build -b html -d _build/doctrees   . _build/html
Running Sphinx v1.5a0
making output directory...
loading pickled environment... not yet created
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 1 source files that are out of date
updating environment: 1 added, 0 changed, 0 removed
reading sources... [100%] index                                                                                                                                      
/home/yardbird/repos/breathe_bug_01/sphinx/index.rst:12: WARNING: Error in declarator or parameters and qualifiers
If pointer to member declarator:
  Invalid definition: Expected identifier in nested name. [error at 17]
    piranha::integer = mp_integer<>
    -----------------^
If declarator-id:
  Invalid definition: Expected identifier in nested name. [error at 17]
    piranha::integer = mp_integer<>
    -----------------^
```

Again, this is from the repo:

https://github.com/bluescarni/breathe_bug_01

*after* modifying in the XML

```xml
<definition>using piranha::integer = typedef mp_integer&lt;&gt;</definition>
```

to

```xml
<definition>using piranha::integer = mp_integer&lt;&gt;</definition>
```

**Comment by vitaut** [comment]
Perhaps the Sphinx cpp domain doesn't support qualified names in `cpp:type`?

```rst
.. cpp:type:: piranha::integer = mp_integer<>
```

If this is the case I'd recommend reporting it to Sphinx.

**Comment by jakobandersen** [comment]
As noted in the Sphinx report: It seems that Breathe asks Sphinx to parse this as a variable declaration instead of a type declaration.

**Comment by vitaut** [comment]
Fixed passing of using declarations to Sphinx in https://github.com/michaeljones/breathe/commit/dbb8f7bac60f94ebbc7697f573493352efe07a21.

**Comment by bluescarni** [comment]
@vitaut Thanks, this indeed fixes the issue!
