### ISSUE TITLE
latex output images

### ISSUE THREAD

**Issue by xoorath** [michaeljones/breathe#274]
Hey Michael,

When I build my documentation as doxygen html output, my latex is rendered with static images. When I build it to xml and have breathe build my documentation my latex is rendered as text.

This isn't ideal for my use case as it takes quite a while to render the equations on the client side. There's a noticable, sometimes 2+ second delay before my page renders correctly.

Is there a way to use statically rendered latex in breathe?

Thanks,
Jared

**Comment by xoorath** [comment]
Here's it rendered in doxygen, using static images.
![](https://i.imgur.com/5rbJlig.png)

Here's an example of my page rendering the breathe docs.
![](http://i.imgur.com/QCtR2kj.png)

A few seconds the page will fully load and render my docs correctly.
![](https://i.imgur.com/gxAszGq.png)

**Comment by michaeljones** [comment]
Thank you for taking the time to raise this and to include such clear illustrations of the problem. I've very little idea about static renders of latex though I can appreciate that the situation is less than ideal for you. If doxygen doesn't do it for us then we'd have to do it ourselves. Are you aware of any tools that render latex to images? I'm not familiar with this area I'm afraid.

**Comment by xoorath** [comment]
Since doxygen is doing it simply for HTML I hope that it's available somehow in XML output. I'll try a few things and get back to you.

**Comment by xoorath** [comment]
Good news @michaeljones, has nothing to do with breathe. I was able to get svg or png to render simply by configuring sphinx. 

http://www.sphinx-doc.org/en/stable/ext/math.html#module-sphinx.ext.imgmath

Thanks for the reply none the less.

**Comment by michaeljones** [comment]
Thank you for following up! Happy to know you have a resolution and it is good to know that for the future.

**Comment by xoorath** [comment]
Note to any others reading this:

Although I can get the desired output locally I cannot get imgmath to be used in read the docs. I've reported the issue here, if you would like to follow up: https://github.com/rtfd/readthedocs.org/issues/2418
