### ISSUE TITLE
render_signature issue

### ISSUE THREAD

**Issue by lilithfr** [michaeljones/breathe#278]
I have the following error in my sphinx project.

Exception occurred:
  File ".../myenv27/lib/python2.7/site-packages/breathe/renderer/index.py", line 43, in render_signature
    signode, contentnode = node.children
ValueError: too many values to unpack

**Comment by michaeljones** [comment]
Hi, thanks for trying Breathe and reporting the issue. Do you think you could provide some more context for the problem? It would be great to investigate but hard without a clearer idea of what might be triggering it.

Thanks again,
Michael

**Comment by lilithfr** [comment]
I print some detail and here the information, it's related to C++ template, there is 2 elements desc_signature instead of 1

**NAME**: myspace::admin::action< void(Args...)>
**KIND**: class
**NODE** TYPE(<class 'sphinx.addnodes.desc'>) PPRINT:
<desc: <desc_signature...><desc_signature "myspace::admin::acti ...>
**NODE.CHILDREN** TYPE(<type 'list'>) PPRINT:
[<desc_signature: <#text: 'template<'><#text: '>'>>,
 <desc_signature "myspace::admin::action<void(Args...)>": <desc_annotation...><desc_addname...><desc_name...><#tex ...>,
 <desc_content: >]

**Comment by michaeljones** [comment]
Great! Thanks for the information. Much appreciated! We'll try to replicate it and get a fix. Might be a few days though.

**Comment by Silentd00m** [comment]
Hi, I encountered the same problem.

Minimal example to trigger error:
<pre>
template <typename _Type>
class native_function;

template <typename _Return, typename... _Args>
class native_function<_Return(_Args...)>
{
};
</pre>

Log:
<pre>
# Sphinx version: 1.4.8
# Python version: 3.5.2 (CPython)
# Docutils version: 0.12 release
# Jinja2 version: 2.8
# Last messages:
#   reading sources... [ 11%] API/class/classslvm_1_1function__t
#   reading sources... [ 12%] API/class/classslvm_1_1function__variant
#   reading sources... [ 13%] API/class/classslvm_1_1illegal__converter__alloc
#   reading sources... [ 15%] API/class/classslvm_1_1illegal__variable__override
#   reading sources... [ 16%] API/class/classslvm_1_1invalid__operator
#   reading sources... [ 18%] API/class/classslvm_1_1module
#   reading sources... [ 19%] API/class/classslvm_1_1multiple__function__definition__without__using
#   reading sources... [ 20%] API/class/classslvm_1_1mutex
#   reading sources... [ 22%] API/class/classslvm_1_1native__function
#   reading sources... [ 23%] API/class/classslvm_1_1native__function_3_01___return_07___args_8_8_8_08_4
</pre>

API/class/classslvm_1_1native__function_3_01___return_07___args_8_8_8_08_4.rst:
<pre>
Class slvm::native_function< _Return(_Args...)>
===============================================

.. doxygenclass:: slvm::native_function< _Return(_Args...)>
</pre>

**Comment by ishitatsuyuki** [comment]
I believe this is already fixed in master and it's due to the too slow release cycle. Come on, let's have a release every quarter to keep up.

**Comment by michaeljones** [comment]
Thanks for pointing this out. I've just done a release as 4.3.1. Could this be tested with that release and will tackle any problems from there?

**Comment by ishitatsuyuki** [comment]
Good good. This one is solved with more features coming in.

**Comment by michaeljones** [comment]
Thank you for the prompting. I think I foolishly tend to assume that most of Breathe's users interact with the project so some degree and are aware of any current issues, but that isn't and shouldn't be the case and doing more regular releases would certainly go a long way to making sure that different people don't hit the same issue over and over again.

Thanks again.

**Comment by Silentd00m** [comment]
Problem is gone with the new version, works perfectly now.

Thank you for the quick fix and this awesome tool!
