### ISSUE TITLE
Publish a wheel on pypi

### ISSUE THREAD

**Issue by SylvainCorlay** [michaeljones/breathe#281]
That would be great if wheel was also published as a wheel on pypi.

To do so, you can just check out the release tags and type:

```
python setup.py bdist_wheel upload
```

for each (already published) tag.

In future releases, instead of only doing `python setup.py sdist upload` you can do:

```
python setup.py sdist upload && python setup.py bdist_wheel upload
```

**Comment by SylvainCorlay** [comment]
FYI, I contributed a recipe for breathe on conda-forge. This will be useful for people publishing breathe-based documentation on readthedocs.io with an `environment.yml` instead of `requirements.txt`.

**Comment by michaeljones** [comment]
Hey, thanks for this. I've just attempted that:

https://pypi.python.org/pypi/breathe/4.3.1

Please let me know if there are any issues.

**Comment by SylvainCorlay** [comment]
Awesome thanks! FYI you can also check out the tags for the earlier releases and publish the missing wheels.

I take this occasion to point out that we have been using breathe successfully for the https://github.com/QuantStack/xtensor project. Thank you for this library

**Comment by michaeljones** [comment]
Great :) Thanks for sharing. Happy to hear it being used.

I'll try to do wheel's for future releases but I probably won't do the past ones unless there is a specific request.

**Comment by SylvainCorlay** [comment]
@michaeljones are you ok to be added as a recipe maintainer on the conda-forge conda recipe?
