### ISSUE TITLE
Function pointer typedef is missing return type in C domain

### ISSUE THREAD

**Issue by Tiwalun** [michaeljones/breathe#283]
The documentation of a function pointer typedef in the c domain is missing the return value.

Based on code like this (take from the examples/specific/typedef.h):

``` c
    typedef void* (*voidFuncPtr)(float, int);
```

the resulting documentation in the C domain looks like this:

```
typedef (*voidFuncPtr)(float int)
```

Note that it's missing the `void*` return type.
In the C++ domain (cpp), the tyepdef is document correctly:

```
typedef void *(*voidFuncPtr)(float, int)
```

**Comment by michaeljones** [comment]
Hi, thanks for pointing this out. I don't think it won't be too hard to fix. If you have time to investigate it yourself that would be great. I can try to take a look but I have very little time for this project at the moment.

Cheers,
Michael

**Comment by Tiwalun** [comment]
Hi Michael,

I'll try to fix it myself. Could you give me a hint in which part of the code I would have to do this?
