### ISSUE TITLE
No class names displayed with sphinx 1.5.1

### ISSUE THREAD

**Issue by joerns** [michaeljones/breathe#292]
I posted this already in the google group, but I think this is a bug so I am creating the issue here. I am not sure if the issue is on the sphinx or on the breathe side.

I have a breathe configuration like this:

```
breathe_default_project = 'myproject'
breathe_projects_source = {
     "myproject" : ( "../src", ["../myproject/myproject.hpp"] )
     }
```
and then:
```
.. autodoxygenindex::
   :project: myproject
```
to generate an index page. This works fine, except that the class names are not shown. It simply says "class", followed by the member list. I checked the HTML source. The class name is actually not written, this is not just a CSS issue. It looks like this:

> <dl class="class">
> <dt id="_CPPv2N5myproject10event_loopE">
> <span id="myproject::event_loop"></span><span class="target" id="netioclassmyproject_1_1event__loop"></span><em class="property">class </em></dt>
> <dd><em>#include &lt;myproject.hpp&gt;</em><p>A central event loop. </p>

When I manually generate a class definition like this the class name will be generated normally:
:`.. cpp:class:: MyClass : public MyBase`

The issue appears with **Sphinx 1.5.1**, and also the current i but it works fine with Sphinx 1.4.8.

**Comment by Luthaf** [comment]
Same issue here, using manual importation of items:

```
.. doxygenclass:: foo::Bar
    :members:
```

Using Sphinx 1.4.9 does make the issue go away.

**Comment by eric-wieser** [comment]
This  is due to the line

    finder.declarator[0] = self.node_factory.desc_annotation(kind + ' ', kind + ' ')
