### ISSUE TITLE
updated breathe broke many previously working elements

### ISSUE THREAD

**Issue by svenevs** [michaeljones/breathe#303]
Hi @michaeljones and other developers, thank you very much for `breathe`.  It's quite excellent, and generally very easy to use :)

Last summer I had written something that sits on top of breathe (mentioned in #293), but never fully finished ironing out the bugs.  I'm fairly certain I just fixed the template stuff in my library, but it appears that whatever updates have happened to breathe have had unintended consequences.

Between ~end of august 2016 and now, functionality that used to render as expected does not.  I wish I could say this is just templates as described in #284 but it is more than that.

Please understand, I am not complaining or anything like that.  But I wrote all of the NanoGUI docs myself, and checked by hand that everything rendered as expected.

Some examples of things that used to work but now do not:

- Just your plain old everyday `enum`: [cursor](http://nanogui.readthedocs.io/en/latest/generated_api/exhale_enum_nanogui__Cursor.html)
- Classes subclassed by templates: [textbox](http://nanogui.readthedocs.io/en/latest/generated_api/exhale_class_nanogui__TextBox.html#class-nanogui-TextBox)
- Or maybe just all classes? [arcball](http://nanogui.readthedocs.io/en/latest/generated_api/exhale_struct_nanogui__Arcball.html)

If it is helpful to you, the library I wrote spits out a [dump of everything at the bottom](http://nanogui.readthedocs.io/en/latest/generated_api/library_root.html#full-api).  It appears that only `.. doxygenfunction::` still works.

Has the usage of `breathe` changed in a way that would cause these breaks to be our fault?  E.g. is there a newly introduced config setting or something?

I've tested with multiple different themes and python2 and 3, all with the same results.

Thank you for any help / advice on how to fix things!

**Comment by svenevs** [comment]
Ok I did some back-tracking, things broke between `v4.2.0` and `v4.3.0` if it helps.

| v4.4.0 Docs | v4.2.0 Docs |
| :---: | :---: |
| [cursor](http://nanogui.readthedocs.io/en/latest/generated_api/exhale_enum_nanogui__Cursor.html) | [cursor](http://fake-nanogui.readthedocs.io/en/latest/generated_api/exhale_enum_nanogui__Cursor.html#enum-nanogui-Cursor) |
| [textbox](http://nanogui.readthedocs.io/en/latest/generated_api/exhale_class_nanogui__TextBox.html#class-nanogui-TextBox) | [textbox](http://fake-nanogui.readthedocs.io/en/latest/generated_api/exhale_class_nanogui__TextBox.html#class-nanogui-TextBox) |
| [arcball](http://nanogui.readthedocs.io/en/latest/generated_api/exhale_struct_nanogui__Arcball.html) | [arcball](http://fake-nanogui.readthedocs.io/en/latest/generated_api/exhale_struct_nanogui__Arcball.html) |

The left column might actually be `v4.3.0`, I don't have admin access to the official RTD for NanoGUI though.  It's worth mentioning that the problems with templates at first glance appear to also be fixed by this reversion.  From the **textbox** pages linked above for left / right columns, click on the link to `FloatBox` to see.

I hope this is useful in identifying the actual cause here!

**Comment by Tiwalun** [comment]
The new Sphinx version 1.5 has caused some issues with Breathe (eg #292). 
Do you know which Sphinx version you are using for the examples?

**Comment by svenevs** [comment]
Hmm that's interesting.  According to the [RTD Build Logs](https://readthedocs.org/projects/fake-nanogui/builds/4899790/), it's using `sphinx-1.3.5`.

**Comment by svenevs** [comment]
Hey!!!  The 4.5.0 update seems to have fixed things, people using vanilla `breathe` in a `requirements.txt` and nothing else (aka whatever latest version of sphinx RTD gives) are working.

Nice work to whatever was changed 😄

**Comment by michaeljones** [comment]
Thanks for keeping us updated!
