### ISSUE TITLE
Split node traversal from SphinxRenderer into a base class

### ISSUE THREAD

**Issue by AWhetter** [michaeljones/breathe#310]
I'm using breathe to parse doxygen xml files but I need to generate different types of nodes other than Sphinx nodes. Because `SphinxRenderer` is doing both node traversal and rendering it's difficult to inherit from the class and use it only for traversal. I'm having to copy over so much code that it isn't really worth me inheriting from `SphinxRenderer`.
If node traversal was split out of `SphinxRenderer` and into a class then it would be easier to do other things with a node tree other than render for sphinx.

**Comment by michaeljones** [comment]
Thanks for raising this. I feel like you're asking to start using the Breathe internals as a kind of API, as well as needing it to change slightly. That is a very reasonable request but there is limited support for Breathe as a project so I would rather not extend its uses beyond the current scope. If we start supporting the idea of people using the internals as an API then it makes it harder to change them as needed for Breathe's primary purpose of providing the current rst based API.

I'm going to close the issue for now. If you feel strongly that your use case would be helpful to others then please provide more information about what you're trying to achieve and we can consider it further. Thanks!
