### ISSUE TITLE
Add an option to show the value of a define

### ISSUE THREAD

**Issue by Tiwalun** [michaeljones/breathe#311]
I have some code where it would be very convenient to see the value of a define in the documentation.

E.g. for a simple define like this:

```c
    /**
     * \brief Maximal data length
     */
    #define MAX_LEN 100
```

currently only the name and the description is shown, but not the actual value.

My plan would be to add an option which will cause the value of the define to be shown it is set.

@michaeljones @vitaut what do you think of this? 
I'll make a pull request for this, if it sounds good.

**Comment by michaeljones** [comment]
Thanks for raising this. Do you think an option is necessary? I suspect we could just always show the value?

**Comment by Tiwalun** [comment]
I thought of the option because defines are sometimes also used to declare function-like macros, and in that case I'm not sure it makes sense to show the value of the define.

I think I'll start working on this, and then we can have a look at the output to decide if an option is necessary?

**Comment by michaeljones** [comment]
All sorted, I think, though still requires an official release.
