### ISSUE TITLE
Struct names not displayed in sphinx

### ISSUE THREAD

**Issue by pmichel31415** [michaeljones/breathe#312]
Hi, we use breathe for our documentation pipeline fo DyNet (https://github.com/clab/dynet).

However I have a weird bug where the name of structs is not displayed in the resulting sphinx doc : 

![](https://cloud.githubusercontent.com/assets/10391785/21687985/37f9535e-d339-11e6-9c90-0a8925c16d69.png)

This doesn't seem to be linked to doxygen itself (the doxygen docs has the names), nor to the readthedocs environment (the same happens on my local machine).

Do you have any idea what might cause this?

Relevant links : 

- [DyNet doc folder (with doxyfile and sphinx source)](https://github.com/clab/dynet/tree/master/doc)

- [readthedocs link](http://dynet.readthedocs.io/en/latest/index.html)

- [Relevant issue on DyNet's repo](https://github.com/clab/dynet/issues/231)

Thanks in advance! I've been racking my brains on this issue for a while now.

**Comment by Andne** [comment]
I've seen this as well, it's a conflict between Sphinx 1.5.x and Breathe 4.4.0.  Using a 1.4.x version of Sphinx generally fixes it.  It looks like this and a few other things should have been fixed in Breathe 4.5.0.

See #292 for the previous issue and #296 for the fix.

**Comment by pmichel31415** [comment]
Thanks for the quick response, that fixed it.

Cheers

**Comment by michaeljones** [comment]
Thank you for fielding this one @Andne. I really appreciate it.
