### ISSUE TITLE
make html: error in update_signature

### ISSUE THREAD

**Issue by ax3l** [michaeljones/breathe#313]
### Problem
running `make html` fails with
```
  File "~/.local/lib/python2.7/site-packages/breathe/renderer/sphinxrenderer.py", line 935, in update_signature
    signature.children[1][0] = self.node_factory.strong(text="[anonymous]")
IndexError: list index out of range
```

#### Procedure to reproduce the problem
```
make html
```

#### Error logs / results
[sphinx-err-GYRF0w.log.txt](https://github.com/michaeljones/breathe/files/774842/sphinx-err-GYRF0w.log.txt)

### Reproducible project / your project
- https://github.com/ComputationalRadiationPhysics/picongpu/ branch: `dev`

```
# Doxyfile in doc/
PROJECT_NAME      = "PIConGPU"
XML_OUTPUT        = xml
INPUT             = ../src
GENERATE_LATEX    = NO
GENERATE_MAN      = NO
GENERATE_RTF      = NO
CASE_SENSE_NAMES  = NO
GENERATE_HTML     = NO
GENERATE_XML      = YES
RECURSIVE         = YES
QUIET             = YES
JAVADOC_AUTOBRIEF = YES
```

### Environment info
- OS: Debian 8.6
- Python version: 2.7.9
- Sphinx version: 1.5.2
- Breathe version: 4.4.0
- Doxygen version: 1.8.8

```
# source/index.rst
.. PIConGPU documentation master file, created by
   sphinx-quickstart on Tue Feb 14 17:29:56 2017.
   You can adapt this file completely to your liking, but it should at least
   contain the root `toctree` directive.

Welcome to PIConGPU's documentation!
====================================

.. toctree::
   :maxdepth: 3
   :caption: Contents:

.. doxygenindex::
   :project: PIConGPU
   :path: '../xml'
   :outline:
   :no-link:

Indices and tables
==================

* :ref:`genindex`
* :ref:`modindex`
* :ref:`search`
```

**Comment by ax3l** [comment]
might be a duplicate of #308 and #286

**Comment by michaeljones** [comment]
Thanks for such a comprehensive report. I'm a little out of the loop but you might want to try 4.5.0 which was released recently. Could you let us know if that helps?

**Comment by ax3l** [comment]
thanks for the quick feedback! yes, stupid me. `master` aka tag `v4.5.0` fixes it! thanks! :)
