### ISSUE TITLE
doxygenfile: Glob files?

### ISSUE THREAD

**Issue by ax3l** [michaeljones/breathe#314]
I am relatively new to sphinx and breathe in particular and trying to get my head around globbers.

Is it possible to "glob" for all files inside a directory and create a `doxygenfile` section for it? I would like to avoid writing something like
```rst
.. doxygenfile:: A.myfileEnding
   :project: myProject
   :path: src/param/A.myfileEnding
   :no-link:

.. doxygenfile:: B.myfileEnding
   :project: myProject
   :path: src/param/B.myfileEnding
   :no-link:

.. doxygenfile:: C.myfileEnding
   :project: myProject
   :path: src/param/C.myfileEnding
   :no-link:
```

and would rather prefer a globber to include all files in `src/param/*` or all files named `*.myfileEnding` alternatively.
```rst
.. doxygenfile:: *.myfileEnding
   :project: myProject
   :path: src/param/*.myfileEnding
   :no-link:
```

Is there a way to express that similar to `:glob:` in `:toctree:`? I tried nesting a `doxygenfile::` inside a `toctree::` with a `:glob:` without success.

**Comment by michaeljones** [comment]
Hi, seems like a good idea. Probably quite reasonable. I've entirely forgotten how the matching works and if the directive is in a good place to support multiple files but we can investigate it.

Are you a Python developer? Is it something that you might be able to work on?

**Comment by ax3l** [comment]
Thank you for the feedback! I would love to work on that but am currently quite occupied with my PhD topic, so just adding all twenty-something files by hand did solve it for the meantime :-)

**Comment by michaeljones** [comment]
Anyone interested in exploring this should look at removing this warning:

https://github.com/michaeljones/breathe/blob/d3eae7fac4d2ead062070fd149ec8bf839f74ed5/breathe/directive/file.py#L30-L33

And then working on the code in:

https://github.com/michaeljones/breathe/blob/d3eae7fac4d2ead062070fd149ec8bf839f74ed5/breathe/renderer/filter.py#L448-L466

To make it account for any glob patterns  in the `self.target_file` variable. I think.

**Comment by melvinvermeeren** [comment]
Closing this as a duplicate in favour of #30, which is older. Will comment there that this one contains some useful hints on where to start.
