### ISSUE TITLE
C++11 using typedefs

### ISSUE THREAD

**Issue by ax3l** [michaeljones/breathe#316]
Doxygen annotated `typdef`s in C++11, via the C++11 syntax
```C++
using NewType = OtherType;
```

Are currently false documented as
```
using NewType = typdef OtherType
```

in breathe html docs (grouping under `Typedefs` in the `doxygenfile::` macro is fine).

I am using breathe 4.5.0 and doxygen 1.8.8 (1.8.11 on readthedocs).

**Comment by ax3l** [comment]
@melvinvermeeren checked again. HTML looks good from what I see. Nevertheless, there still seem to be many warnings thrown at `make html` time with the `= typdef OtherType` syntax.

**Comment by melvinvermeeren** [comment]
Since the previous posting further improvements have been made in Sphinx's C++ domain, so I am assuming this is resolved now. Closing to clean up the issue tracker.
