### ISSUE TITLE
template keyword not handled correctly in declaration

### ISSUE THREAD

**Issue by eric-wieser** [michaeljones/breathe#325]
The following code is legal [`C++`](http://ideone.com/cD9mqE):

```c++
class Stop;
class Go;

//! stores a handler for each message type.
template<typename T>
struct messageHandlers {
    typedef std::function<void (const T&)> type;
    static type handler;
};

template <typename T> typename messageHandlers<T>::type messageHandlers<T>::handler;
template messageHandlers<Go>::type messageHandlers<Go>::handler;
template messageHandlers<Stop>::type messageHandlers<Stop>::handler;
```

Note that there are deliberately no `<>` after the word `template`, as this would declare a specialization of some kind. Instead `template` is required here to tell the compiler to parse 

This gives an incorrect warning in breathe:
```
<path>: WARNING: Invalid definition: Expected '<' after 'template' [error at 9]
  template messageHandlers< Go >::type messageHandlers::handler
  ---------^
```

As it turns out, there's a way of expressing this without this syntax, so this isn't an issue for me - but it is still a bug in breathe

**Comment by michaeljones** [comment]
Hi @eric-wieser, I'm not sure that warning is coming from the Breathe code base. Do you feel we're passing the wrong thing to Sphinx or that Sphinx is possibly complaining inappropriately and should support this? Thanks for raising it.

**Comment by eric-wieser** [comment]
You're right, this is sphinx complaining. Presumably breate is doing the equivalent of writing
```
.. cpp:var:: template messageHandlers<Go>::type messageHandlers<Go>::handler
```
for me, which gives the same error.

I don't really want to dig too deep into this, but either:
* Doxygen is outputting the `template` keyword, when it should probably throw it away it stores that data elsewhere (that it is a variable). Solution: Patch doxygen
* Doxygen and sphinx are both working to spec. Solution: Strip this keyword inside breathe
* Sphinx missed a case in its parsing of `:cpp:var:`. Solution: Patch sphinx

So the only real "bug" in breathe here is being a poor middle man between two possibly-broken tools.

**Comment by svenevs** [comment]
1. Did you try `member` instead?  I'm looking [here](http://www.sphinx-doc.org/en/stable/domains.html#directive-cpp:var), but I'm pretty sure that won't fix this.
2. The underlying problem here is that the `var` doesn't have the template, the class does.  The impact is that in the doxygen xml output, `messageHandlers` will have the `templateparamlist`, not the specific variable you are documenting.

So the fix you probably don't want to use is to explicitly specialize the `messageHandlers` class for `Go` and `Stop`, adding documentation to each specialization

```
class Stop;
class Go;

//! stores a handler for each message type.
template<typename T>
struct messageHandlers {
    typedef std::function<void (const T&)> type;
    static type handler;
};

template <>
struct messageHandlers<Stop> {
    typedef std::function<void (const Stop&)> type;
    static type handler;
};
```

Definitely defeats the purpose... but then you can do `.. doxygenclass:: messageHandlers< Stop >`.  This will produce warnings, but I'm here trying to fix those ;)

Alternatively, just add documentation to `messageHandlers` and explicitly state that specializations for `Stop` and `Go` exist?

**Comment by jakobandersen** [comment]
The warning was, as noted, from Sphinx which should be fixed now. There are however a few notes:
- To my understanding the ``template`` prefix is a short hand for "as many ``template<>`` as needed". For example, ``template A<int>::B<float>::var`` is a shorthand for ``template<> template<> A<int>::B<float>::var``. Sphinx will now parse the former as well, but render them both as the latter.
- The line ``template <typename T> typename messageHandlers<T>::type messageHandlers<T>::handler;`` is in C++ terms a definition, but for Sphinx it is just a redeclaration. If this line is given to Sphinx as well as the one inside the class definition, there will be a warning. If Breathe can not in a reasonable way detect this we could try to hammer out some way for Sphinx to tell Breathe about redeclarations so they can be properly ignored.
- The two last lines are also definitions, but also explicit instantiations of template specializations that have not been declared before. No warning will therefore be raised.
- As the specializations have not been declared, they will not be hyperlinked as a prefix of a nested name.
- The two directives ``var`` and ``member`` behave exactly the same. It is mostly a historical artifact that both exist.

**Comment by melvinvermeeren** [comment]
If it safe to assume the issue has been resolved with changes to Sphinx as referenced above?

**Comment by melvinvermeeren** [comment]
Assuming fixed for now, closing.
