### ISSUE TITLE
@headerfile not rendered

### ISSUE THREAD

**Issue by JohanMabille** [michaeljones/breathe#327]
It seems the `@headerfile` command is ignored. The same if the name of the header is added after the name of the class in the `@class` command.

I couldn't find anything in the documentation about this, but maybe it could be a simple configuration problem ?

**Comment by michaeljones** [comment]
Hi @JohanMabille, thanks for raising this. I'm afraid I'm unfamiliar with the `@headerfile`  command and we don't seem to have an example in the `examples` folder. Could you possibly open a pull request with an example in the `examples/specific` folder and then we'd have something to work with to understand it better?

Thanks!

**Comment by melvinvermeeren** [comment]
I see the example was added but I cannot find anything related to implementation changes. Is this still an issue?

**Comment by melvinvermeeren** [comment]
Assuming fixed, closing.
