### ISSUE TITLE
Make crossref rendering consistent with sphinx?

### ISSUE THREAD

**Issue by bluescarni** [michaeljones/breathe#331]
I noticed that in the HTML output of breathe, cross-references between classes, functions etc. appearing in the doxygen markup are rendered in a different way with respect to the cross-references generated by sphinx's C++ domain functionalities. I.e., the cross links coming out from doxygen are rendered with an underline and differently-coloured text, whereas pure sphinx crosslinks (e.g., using ``:cpp:class:`foo` ``) are rendered in bold text without underline.

It's just a minor cosmetic inconsistency, but would it be possible to modify breathe to render cross references in the same way as sphinx does?

**Comment by bluescarni** [comment]
Here's a concrete example of what I mean:

https://bluescarni.github.io/mppp/mp_integer.html#_CPPv23powRK1TRK1U

(compare the links rendering in the ``Note:`` box with the text below it)

**Comment by melvinvermeeren** [comment]
Not a surprise since it has been a year, but the link above 404s. Is this still an issue with the latest version?

**Comment by melvinvermeeren** [comment]
Assuming fixed, closing.
