### ISSUE TITLE
Polymorph functions in c++ break doc build

### ISSUE THREAD

**Issue by awachtler** [michaeljones/breathe#335]
## Issue

When using  breathe==4.6.0 and  Sphinx==1.6.1
the documentation build fails if the statement

    .. doxygenclass:: Foo
        :members:

is used. It generates a Sphinx error:

    File "/home/axel/Work/uracoli-aw/ve_uracoli/local/lib/python2.7/site-packages/docutils/transforms/universal.py", line 294, in apply
    txtnode.parent.replace(txtnode, nodes.Text(newtext))
    AttributeError: 'NoneType' object has no attribute 'replace'

When adding *:outline:*  the doc renders, but does not show the member documentation.

    .. doxygenclass:: Foo
       :outline:
       :members:

## Code that produces the issue

    #ifndef TEST_H
    #define TEST_H (1)
    /** this class implements fooish objects */
    class Foo
    {
        public:
        /** without parameters */
        void poly(void);
        /** with one parameter
         * @param x The x value,
         */
        void poly(int x);
    };
    #endif

## Reproduce the issue

Attached find a example project that shows the issue
[breathe_issue.zip](https://github.com/michaeljones/breathe/files/1030883/breathe_issue.zip)

    $ doxygen && make html
    Running Sphinx v1.6.1
    loading pickled environment... done
    building [mo]: targets for 0 po files that are out of date
    building [html]: targets for 1 source files that are out of date
    updating environment: 0 added, 1 changed, 0 removed
    reading sources... [100%] index
    Exception occurred:
      File "/home/axel/Work/uracoli-aw/ve_uracoli/local/lib/python2.7/site-packages/docutils/transforms/universal.py", line 294, in apply
        txtnode.parent.replace(txtnode, nodes.Text(newtext))
    AttributeError: 'NoneType' object has no attribute 'replace'
    The full traceback has been saved in /tmp/sphinx-err-UKHkFE.log, if you want to report the issue to the developers.
    Please also report this if it was a user error, so that a better error message can be provided next time.
    A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
    Makefile:20: die Regel für Ziel „html“ scheiterte
    make: *** [html] Fehler 1

## Environment

    aafigure==0.5
    alabaster==0.7.10
    appdirs==1.4.3
    argh==0.26.2
    Babel==2.4.0
    backports-abc==0.5
    bottle==0.12.9
    bottle-websocket==0.2.9
    breathe==4.6.0
    certifi==2017.4.17
    cffi==1.7.0
    cryptography==1.4
    docutils==0.13.1
    enum34==1.1.6
    gevent==1.1.2
    gevent-websocket==0.9.5
    greenlet==0.4.10
    idna==2.1
    imagesize==0.7.1
    ipaddress==1.0.16
    Jinja2==2.9.6
    livereload==2.5.1
    MarkupSafe==1.0
    mercurial==4.1.2
    olefile==0.44
    packaging==16.8
    paramiko==2.0.2
    pathtools==0.1.2
    Pillow==4.1.1
    port-for==0.3.1
    pyasn1==0.1.9
    pycparser==2.14
    Pygments==2.2.0
    pyparsing==2.2.0
    pyserial==3.1.1
    pytz==2017.2
    PyYAML==3.12
    radiofaro==0.5.0
    radiofarogw==0.5.0
    reportlab==3.4.0
    requests==2.14.2
    singledispatch==3.4.0.3
    six==1.10.0
    snowballstemmer==1.2.1
    Sphinx==1.6.1
    sphinx-autobuild==0.6.0
    sphinxcontrib-aafig==1.0
    sphinxcontrib-websupport==1.0.1
    svgwrite==1.1.10
    tornado==4.5.1
    typing==3.6.1
    watchdog==0.8.3

**Comment by awachtler** [comment]
Just applied https://github.com/michaeljones/breathe/pull/334 and it fixes the issue. 
So if PR #334 makes it to the next release, this issue can be closed.
Thanks to @arximboldi for fixing the issue, which was a blocker for me :-).

**Comment by arximboldi** [comment]
You're welcome! But most of the credit should go to the Sphinx maintainers that were kind enough to debug into the issue and find the right fix (as opposed to my initial change that just reverted some commits :p)

**Comment by melvinvermeeren** [comment]
It appears this has been fixed some releases ago, closing.
