### ISSUE TITLE
Best way to make Sphinx latexpdf documentation include page breaks between function definitions

### ISSUE THREAD

**Issue by rdeterre** [michaeljones/breathe#337]
Hi,

I'm wondering what would be the best way to make the Latex documentation generated using Sphinx and Breathe include page breaks between functions.

I've seen that rst2pdf has a `pdf_break_level` variable that can be used, but the [best solution](https://stackoverflow.com/a/26127641/1857952) with latexpdf seems to be to add raw latex directives in the source code.

Is there an alternative to this that would allow to get page breaks whenever the `.. doxygenfunction` directive is used?

Thanks

**Comment by melvinvermeeren** [comment]
Hi,

Is there a regular RST/Sphinx directive that will cause `latexpdf` to page break that you can use manually? If not then you should probably take the issue to Sphinx, Breathe can then use that directive once it exists.

**Comment by melvinvermeeren** [comment]
No reply and likely needs work upstream first, closing.
