### ISSUE TITLE
`noexcept` not rendered

### ISSUE THREAD

**Issue by twesterhout** [michaeljones/breathe#338]
I've noticed that `noexcept` specifier is not rendered for member functions. Doxygen XML output contains this info in the `<argsstring>` field, so I figured it should be supported by Breathe. Is this a bug? or a not yet implemented feature?

**Comment by melvinvermeeren** [comment]
If it is listed in the XML but not rendered Breathe is most likely not checking for it. I believe this is not very hard to implement.

**Comment by vermeeren** [comment]
Should be fixed with #512, released in Breathe v4.17.0. Note that you also need Sphinx 3.x for recent Breathe versions.
