### ISSUE TITLE
An example of "Doxygen + Breathe + Sphinx + ReadTheDocs"

### ISSUE THREAD

**Issue by xenigmax** [michaeljones/breathe#343]
Hello.

First of all, thank you for developing this nice extension!

I'm a member of the project named SeqAn (https://github.com/seqan/seqan) and we are trying to use **Doxygen + Breathe + Sphinx + ReadTheDocs**  for our next version of the library.
I just found that one of your example link (http://cppformat.readthedocs.org/en/latest/) is broken, so would like to share ours although it's not completed yet. ;)

* Before
http://docs.seqan.de/seqan/2.3.2/

* After (developing now !)
http://seqan3-api.readthedocs.io

All the scripts or setting files we are using will be share in the separated repository.
https://github.com/seqan/seqan3-doc/.

Thank you again~!

Best regards,
Jongkyu

**Comment by JohanMabille** [comment]
Hi,

Nice example! The chain "Doxygen + Breathe + Sphinx + ReadTheDocs" is something we use a lot at QuantStack, here are some examples:

- [xtensor repo](https://github.com/QuantStack/xtensor) -- [xtensor doc](http://xtensor.readthedocs.io/en/latest/)
- [xtensor-python repo](https://github.com/QuantStack/xtensor-python) -- [xtensor-python doc](http://xtensor-python.readthedocs.io/en/latest/)
- [xsimd repo](https://github.com/QuantStack/xsimd) -- [xsimd doc](http://xsimd.readthedocs.io/en/latest/)

I hope it can help!

Regards,
Johan

**Comment by SylvainCorlay** [comment]
I think that Johan's answer is good enough for closing.

**Comment by siedentop** [comment]
Here is a good resource walking you through the process: https://devblogs.microsoft.com/cppblog/clear-functional-c-documentation-with-sphinx-breathe-doxygen-cmake/ by @tartanllama.

I know this is an old thread but it comes up when searching for this, and I hope this will help others in the same way it helped me.
