### ISSUE TITLE
Incorrect rendering of a struct with union - ‘Expected identifier in nested name’

### ISSUE THREAD

**Issue by krzychb** [michaeljones/breathe#346]
When a header file contains definition of a structure with union as follows:

```c
typedef struct {
    esp_a2d_mct_t type;                        /*!< A2DP media codec type */
#define ESP_A2D_CIE_LEN_SBC          (4)
#define ESP_A2D_CIE_LEN_M12          (4)
#define ESP_A2D_CIE_LEN_M24          (6)
#define ESP_A2D_CIE_LEN_ATRAC        (7)
    union {
        uint8_t sbc[ESP_A2D_CIE_LEN_SBC];
        uint8_t m12[ESP_A2D_CIE_LEN_M12];
        uint8_t m24[ESP_A2D_CIE_LEN_M24];
        uint8_t atrac[ESP_A2D_CIE_LEN_ATRAC];
    } cie;                                     /*!< A2DP codec information element */
} __attribute__((packed)) esp_a2d_mcc_t;
```

Then rendering of union member of this structure is faulty.

![screenshot from 2017-08-12 21-15-12](https://user-images.githubusercontent.com/12953787/29243609-6615dbf6-7fa3-11e7-9aad-fee4a9fd46c9.png)

The following warning is shown during documentation build::

```
(WARNING/2) Invalid definition: Expected identifier in nested name. [error at 21]
union esp_a2d_mcc_t::@0  esp_a2d_mcc_t::cie
---------------------^
```

Header file that contains code causing this issue https://github.com/krzychb/rtd-test-bed/blob/master/headers/esp_a2dp_api.h

Details of packages that cause this issue:
* Sphinx 1.6.3
* Breathe 4.7.0
Previous packages, e.g. Sphinx 1.5.6 and Breathe 4.6.0 have the same issue.

Example documentation - http://rtd-test-bed.readthedocs.io/en/latest/case-struct-union.html

* Have seen this issue before?
* Where to look for resolution?

**Comment by SylvainCorlay** [comment]
Could this be related to https://github.com/sphinx-doc/sphinx/issues/2683?

**Comment by krzychb** [comment]
You are absolutely right!
Closing this one as a duplicate.
