### ISSUE TITLE
Breathe on pypi corrupted?

### ISSUE THREAD

**Issue by Andne** [michaeljones/breathe#348]
I updated my local install of breathe to 4.7.1 in order to get some various fixes.  However, the version on pypi appears to be having some issues - the breathe-apidoc command fails with a syntax error.

Best I can tell, the syntax error is occurring because the line `from __future__ import print_function` is missing from the top of breathe/apidoc.py.  I went back to version 4.6.0 and it's in there as well as existing in the master version, but for some reason 4.7.0 and 4.7.1 are missing that line.  Even after fixing that I get another exception when sphinx is running that does not occur when using a local copy of the GitHub repository where I checked out the specific tag.

Diffing the installed version against the tags from GitHub is showing differences as well, it appears that what was published to pypi wasn't a clean copy at the time, unless pypi has some automatic scripts that run when you publish to it?  It appears most of the differences are related to unicode and some extra casting and such.

**Comment by SylvainCorlay** [comment]
It seems that the creation of the wheel with `python setup.py bdist_wheel --universal` strips the `future` imports. It is the first time that I see this. Asking around.

**Comment by SylvainCorlay** [comment]
PS: while I reproduce the behavior with the breathe package, this does not occur when I build wheels for other packages on the same system. So this is an issue with the breathe setup.py.

**Comment by Andne** [comment]
Given what you've said, on initial inspection I suspect this line in setup.py may be the cause:
[`use_2to3=True,`](https://github.com/michaeljones/breathe/blob/651d7fb8fa8ee7741b30eaac9c624d673bdc390d/setup.py#L79), but it's been there for 6 years now, so not sure why 4.6.0 works properly, different execution of setup.py maybe?

I don't know anything about setuptool and pypi other than installing packages from it, so I'm guessing a lot right now.  What version(s) of python are other people using?  I'm using 2.7 for my stuff still.

**Comment by SylvainCorlay** [comment]
Yes, I also came to the same conclusion.

**Comment by SylvainCorlay** [comment]
apidoc.py was not there.

**Comment by SylvainCorlay** [comment]
I would like to know the implications of removing the use `use_2to3`, and if it is not an issue, we can make a 4.7.2 without that statement.

**Comment by Andne** [comment]
I can't really speak to how it affects the code base, but I found this information on the `use_2to3` option itself - http://setuptools.readthedocs.io/en/latest/python3.html - apparently it's not the recommended approach anymore, they instead recommend developing a compatible codebase (some of the suggested libraries are referenced in the codebase).

`apidoc.py` existed in 4.6.0, it has been modified since then and some of the changes I'm looking for are in it now.

Unless someone has a specific idea how to verify using/not using `use_2to3` my thought is to release without it and see if anyone complains, it appears at a cursory look that the codebase is compatible with both Python 2 and Python 3.

@michaeljones Can you provide any additional insight on your release process and why earlier versions don't appear to have shown this behavior?

**Comment by SylvainCorlay** [comment]
@Andne I opened a PR to test that CI passes without the 2to3 on python 2, and it does.

I will wait a bit before cutting a patch release with that fix to let michael the time comment if he wants

**Comment by SylvainCorlay** [comment]
Breathe 4.7.2 is on pypi.

**Comment by Mekk** [comment]
For the sake of history: I found this PR while bisecting ugly breathe crashes (I developed some docs - with pleasure - using mostly 4.7.3, then it turned out that building the same docs on machine with pip-installed breathe 4.6.0 crashes, then via bisect I found out that 4.7.2 is first working version). Unfortunately can't post examples as this is large pile of closed code (and I am by far unsure what exactly triggers the problem), and the problem is solved so not worth digging int … but this is my 2cents with respect to claims that 4.6.0 works ;-)

**Comment by Mekk** [comment]
And just in case someone is interested: errors aren't the same, but still are there

```
$ pip install breathe==4.6.0
$ make html
…
Exception occurred:
  File "/home/marcink/.virtualenvs/sphinx-old/local/lib/python2.7/site-packages/sphinx/util/nodes.py", line 383, in is_smartquotable
    elif node.parent.get('support_smartquotes', None) is False:
AttributeError: 'NoneType' object has no attribute 'get'

$ pip install breathe==4.7.0
$ make html
…
Exception occurred:
  File "/home/marcink/.virtualenvs/sphinx-old/local/lib/python2.7/site-packages/breathe/renderer/filter.py", line 320, in __call__
    raise e
AttributeError: 'str' object has no attribute 'node_type'

$ pip install breathe==4.7.1
$ make html
…
Exception occurred:
  File "/home/marcink/.virtualenvs/sphinx-old/local/lib/python2.7/site-packages/breathe/renderer/filter.py", line 320, in __call__
    raise e
AttributeError: 'str' object has no attribute 'node_type'

$ pip install breathe==4.7.2
$ make html
…
build succeeded.
```
