### ISSUE TITLE
Rendering @deprecated in breathe

### ISSUE THREAD

**Issue by projectgus** [michaeljones/breathe#355]
I was wondering if anyone had any thoughts/experience having the `@deprecated` Doxygen tag translate through to Breathe.

For example, the TinyXML example has some deprecated functions:
https://github.com/michaeljones/breathe/blob/master/examples/tinyxml/tinyxml.h#L1669

This markup is not rendered by breathe:
http://breathe.readthedocs.io/en/latest/tinyxml.html#_CPPv2NK11TiXmlHandle4NodeEv

Happy to do some implementation work if that's what's necessary, but thought I would ask for tips/pointers/experience first as the breathe implementation is a bit of a black box for me at the moment.

Thanks!

**Comment by AmatanHead** [comment]
Doxygen does not export deprecated tags. Instead, it produces a separate page called `Deprecated List` in which there is a text which contains all deprecated members. You can see 'page deprecated' mentioned at the very end of the [tinyxml documentation](http://breathe.readthedocs.io/en/latest/tinyxml.html).

An example of generated xml follows:

```xml
<?xml version='1.0' encoding='UTF-8' standalone='no'?>
<doxygen xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="compound.xsd"
         version="1.8.14">
    <compounddef id="deprecated" kind="page">
        <compoundname>deprecated</compoundname>
        <title>Deprecated List</title>
        <briefdescription>
        </briefdescription>
        <detaileddescription>
            <para>
                <variablelist>
                    <varlistentry>
                        <term><anchor id="deprecated_1_deprecated000001"/>Class <ref
                                refid="class_n_q_b3_1_1_t_extractor_base" kindref="compound">NQB3::TExtractorBase
                        </ref>
                        </term>
                    </varlistentry>
                    <listitem>
                        <para>
                            <ref refid="class_n_q_b3_1_1_t_extractor_base" kindref="compound">TExtractorBase</ref>
                            is deprecated
                        </para>
                    </listitem>
                </variablelist>
            </para>
        </detaileddescription>
    </compounddef>
</doxygen>
```

As you can see, it is a simple text. So, the choice is to either ask doxygen authors to add this information to the generated xml or parse this page and extract relevant info. The latter approach may be easier and faster to implement, however, it may cause problems if doxygen authors decide to change layout of this page.

There is a somewhat close bug in the doxygen bugtracker: https://bugzilla.gnome.org/show_bug.cgi?id=624495. The bug looks like an abandoned one, however; last change in 2012.

**Comment by melvinvermeeren** [comment]
To me it appears that in order to implement this in Breathe properly Doxygen would indeed need to export it to its XML output.

Having a separate page for deprecated things seems rather pointless, I feel that nobody would look there in practice while using an API.

Taking the tags from from the deprecated list seems to be a very fragile solution, I'd rather not do it that way.

For now I will be closing due to missing input in XML. In case there is another way to fix this please comment.
