### ISSUE TITLE
C/C++ bit field missing.

### ISSUE THREAD

**Issue by ships95** [michaeljones/breathe#358]
`union Wait {
    struct {
        int ready : 1;
        int  flags : 7;
    };
    UINT8 val;
};`

I can not see the bit field information.

**Comment by rhssk** [comment]
Stumbled upon the same issue. Played around with declaration rendering and was stopped by Sphinx `cpp` domain validator which seems to think that `uint8_t foo : 3` is not a valid declaration. Also there doesn't seem to be any references to bit fields in Sphinx's source/[issues](https://github.com/sphinx-doc/sphinx/issues).

Right now I see 2 solutions:
1. don't make the bit field a part of declaration, instead add separate entity that is inserted directly after declaration,
2. add support for bitfields in Sphinx's `c` and `cpp` domain declaration parsers.

The second option seems much more sane. Any thoughts @melvinvermeeren?

**Comment by jakobandersen** [comment]
If you open an issue over in Sphinx I'll get it fixed in the C++ domain as soon as I find time (unless someone beats me to it. I believe very few changes are needed).

**Comment by rhssk** [comment]
[Issue over at Sphinx](https://github.com/sphinx-doc/sphinx/issues/6707)
