### ISSUE TITLE
index.xml file not found by doxygenindex directive

### ISSUE THREAD

**Issue by Dhruva-Storz** [michaeljones/breathe#359]
Ive got an index.xml file containing all the documentation, an rst file calling the doxygenindex directive on the index file and I have specified the path in conf.py. However, make html always fails with a MTimerError because it 'cant find index.xml'. index.xml is however most definitely in the specified folder. 

Error below: 

MTimerError : cannot find file: /home/barroth/fork/source/index.xml

I have tried copying index.xml contents to freshly created index.xml as the one generated by doxygen is locked. I have also tried putting the file in a different folder and changing the breathe_projects_source and breathe_projects paths to account for the change. Neither of these worked. I think it might be an issue with the doxygenindex class. 

autodoxygenindex generates something, although it documents things like conf.py and other things but not my code.

**Comment by SylvainCorlay** [comment]
make html should logically place the xml in a peer directory of `source`.

For a good example of a project with sphinx + breathe documentation, you can check out xtensor.

**Comment by Dhruva-Storz** [comment]
Apparently I messed up in specifying the path. When I changed
 
'../../source/doxygen/cpp/xml' 
into 
'doxygen/cpp/xml' 

it worked. So its not an issue with the class. 

Thanks SylvianCorlay for the response.

**Comment by SylvainCorlay** [comment]
ok, thanks
