### ISSUE TITLE
Does Breathe support inheritancegraph displaying inherited members?

### ISSUE THREAD

**Issue by tjacobs** [michaeljones/breathe#364]
I don't see it being used in parser, and the members don't appear listed in my output HTML page.

Is there a flag to enable this or a workaround, or will I need to implement this in Breathe?

**Comment by tjacobs** [comment]
Actually, got it, I just set Doxygen:

INLINE_INHERITED_MEMB = YES

And they come through, closing.

**Comment by SylvainCorlay** [comment]
Thanks.
