### ISSUE TITLE
Unnecessary links in HTML-Output

### ISSUE THREAD

**Issue by skyfmmf** [michaeljones/breathe#374]
As I had an issue with unnecessary links showing up when I tried to use breathe in one of my projects, I tried to build the breathe documentation as a demo. But it shows the same strange behavior (As it is a bit difficult to describe, I attached a screenshot; note all these Nutshell-links).

I had this behavior with Sphinx 1.7.2 and 1.7.3 

<img width="856" alt="bildschirmfoto 2018-04-22 um 20 07 54" src="https://user-images.githubusercontent.com/1775352/39098872-92e506da-4671-11e8-969d-10815fbad60e.png">

**Comment by t-b** [comment]
@skyfmmf Same here. With sphinx 1.6.3 I it looks good.

**Comment by jakobandersen** [comment]
This problem should be fixed when using the 1.7 branch of Sphinx (which becomes version 1.7.5).

**Comment by melvinvermeeren** [comment]
@jakobandersen thank you for your recent work. I will keep this issue open until 1.7.5 is released so the CI can be updated to use it.

**Comment by t-b** [comment]
@melvinvermeeren 1.7.5 of sphinx is out and fixes the problem here.

**Comment by melvinvermeeren** [comment]
@t-b thanks for the feedback! I will update the CI to 1.7.5 soon, have been a bit busy lately. After that the issue can be closed. :)
