### ISSUE TITLE
Problem with doxygengroups on RTD build 

### ISSUE THREAD

**Issue by mgiaco** [michaeljones/breathe#379]
Hi,

Can someone help me? I do have some problems with my doxygengroups see here. https://li-can-slv.readthedocs.io/en/latest/api.html#id2

I really do not understand whats wrong. When I build the docs on the local machine everything is fine. I only have problem on the RTD server. And I do only have errors on the doxygen groups.

Here is the link to the latest RTD  build: https://readthedocs.org/projects/li-can-slv/builds/7262018/

Here is the sphinx conf: https://github.com/liebherrnenzing/li_can_slv/tree/master/docs/sphinx

many thanks

**Comment by melvinvermeeren** [comment]
Hi,

Are you sure the commands running locally are exactly the same as on the RTD server?
If yes, you may also want to check what pkg versions you are using, perhaps the issue lies there.

I also notice:

```
Cannot find enum "lcsa_module_change_voter_state_t" in doxygen xml output
```

So currently I would suspect some different Doxygen version is used, perhaps an old one with some issues?

**Comment by mgiaco** [comment]
Hi, 

I also notice that those are missing and I do not know why:
```
/home/docs/checkouts/readthedocs.org/user_builds/li-can-slv/checkouts/latest/docs/sphinx/api.rst:90: WARNING: doxygengroup: Cannot find namespace "li_can_slv_api_sync" in doxygen xml output for project "li_can_slv" from directory: doxyxml
/home/docs/checkouts/readthedocs.org/user_builds/li-can-slv/checkouts/latest/docs/sphinx/api.rst:97: WARNING: doxygengroup: Cannot find namespace "li_can_slv_api_sync_cbk" in doxygen xml output for project "li_can_slv" from directory: doxyxml
/home/docs/checkouts/readthedocs.org/user_builds/li-can-slv/checkouts/latest/docs/sphinx/api.rst:108: WARNING: doxygengroup: Cannot find namespace "li_can_slv_api_dload" in doxygen xml output for project "li_can_slv" from directory: doxyxml
/home/docs/checkouts/readthedocs.org/user_builds/li-can-slv/checkouts/latest/docs/sphinx/api.rst:119: WARNING: doxygengroup: Cannot find namespace "li_can_slv_api_sync_error" in doxygen xml output for project "li_can_slv" from directory: doxyxml
/home/docs/checkouts/readthedocs.org/user_builds/li-can-slv/checkouts/latest/docs/sphinx/api.rst:170: WARNING: doxygengroup: Cannot find namespace "li_can_slv_api_reconnect_online" in doxygen xml output for project "li_can_slv" from directory: doxyxml
/home/docs/checkouts/readthedocs.org/user_builds/li-can-slv/checkouts/latest/docs/sphinx/api.rst:173: WARNING: doxygengroup: Cannot find namespace "li_can_slv_api_reconnect_startup" in doxygen xml output for project "li_can_slv" from directory: doxyxml
/home/docs/checkouts/readthedocs.org/user_builds/li-can-slv/checkouts/latest/docs/sphinx/api.rst:179: WARNING: doxygengroup: Cannot find namespace "lcsa_api_change_module_nr" in doxygen xml output for project "li_can_slv" from directory: doxyxml
```
So Doxygen..  That was also my very first idea so I have added a doxygen -v output on the RTD server. I got version 1.8.11 so that is the same version I use. 
As you can see I use a requirements.txt you can find it in docs/sphinx/ so I also use the same breathe version. 

No I know it is not the same because RTD is a linux server I think and I am working on an windows 7 host. But I try to do the same as much as possible. 

So now I have added a dump of a file also I will report about that later.

Do you have any other Idea?

**Comment by mgiaco** [comment]
So I have added a dump and it is really different and missing. But why? I do not get any doxygen error or warning.

**Comment by melvinvermeeren** [comment]
With dump you mean the XML output that Doxygen generates? The one of RTD is missing the information in XML, right?

The OS it runs on shouldn't matter to the end result. The only thing I can think of is that somewhere in your project you are perhaps not being case-sensitive. Windows by default isn't case-sensitive but Linux is.

I can try to build locally since I only run Linux, is this the correct repo:
https://github.com/liebherrnenzing/li_can_slv

**Comment by mgiaco** [comment]
Hello, yes that is the repo. Many thanks for your help

**Comment by mgiaco** [comment]
Have you checked it? Did you find anything which looks wrong?

**Comment by melvinvermeeren** [comment]
Hi, sorry for the wait. I had been busy for a bit.

```sh
mkdir ~/tmp
cd ~/tmp

git clone https://github.com/liebherrnenzing/li_can_slv.git

mkdir pypath
pip install -t ~/tmp/pypath --upgrade sphinxcontrib-seqdiag sphinxcontrib-inlinesyntaxhighlight
export PYTHONPATH=':/usr/lib/python36.zip:/usr/lib/python3.6:/usr/lib/python3.6/lib-dynload:/usr/lib/python3.6/site-packages:/home/build/tmp/pypath'

cd li_can_slv/docs/sphinx
doxygen
make html
```

(I don't think this is a complete build, some add-on pages appear to be missing, but it should be ok for this test.)

Then, during the `doxygen` step I see the following output on top.

```
warning: Tag `CLANG_ASSISTED_PARSING' at line 1020 of file `Doxyfile' belongs to an option that was not enabled at compile time.
         To avoid this warning please remove this line from your configuration file or upgrade it using "doxygen -u", or recompile doxygen with this feature enabled.
warning: Tag `CLANG_OPTIONS' at line 1028 of file `Doxyfile' belongs to an option that was not enabled at compile time.
         To avoid this warning please remove this line from your configuration file or upgrade it using "doxygen -u", or recompile doxygen with this feature enabled.
warning: tag INCLUDE_PATH: include path `..\..\source' does not exist
warning: tag INCLUDE_PATH: include path `..\..\source\api' does not exist
warning: tag INCLUDE_PATH: include path `..\..\source\arch' does not exist
warning: tag INCLUDE_PATH: include path `..\..\source\arch\canpie_adapter' does not exist
warning: tag INCLUDE_PATH: include path `..\..\source\async' does not exist
warning: tag INCLUDE_PATH: include path `..\..\source\config' does not exist
warning: tag INCLUDE_PATH: include path `..\..\source\core' does not exist
warning: tag INCLUDE_PATH: include path `..\..\source\error' does not exist
warning: tag INCLUDE_PATH: include path `..\..\source\msg' does not exist
warning: tag INCLUDE_PATH: include path `..\..\source\sync' does not exist
warning: tag INCLUDE_PATH: include path `..\..\source\sys' does not exist
warning: tag INCLUDE_PATH: include path `..\..\source\util' does not exist
warning: tag INCLUDE_PATH: include path `..\..\source\xload' does not exist
Searching for include files...
warning: source ..\..\source is not a readable file or directory... skipping.
warning: source ..\..\source\api is not a readable file or directory... skipping.
warning: source ..\..\source\arch is not a readable file or directory... skipping.
warning: source ..\..\source\arch\canpie_adapter is not a readable file or directory... skipping.
warning: source ..\..\source\async is not a readable file or directory... skipping.
warning: source ..\..\source\config is not a readable file or directory... skipping.
warning: source ..\..\source\core is not a readable file or directory... skipping.
warning: source ..\..\source\error is not a readable file or directory... skipping.
warning: source ..\..\source\msg is not a readable file or directory... skipping.
warning: source ..\..\source\sync is not a readable file or directory... skipping.
warning: source ..\..\source\sys is not a readable file or directory... skipping.
warning: source ..\..\source\util is not a readable file or directory... skipping.
warning: source ..\..\source\xload is not a readable file or directory... skipping.
Searching for example files...
```

I think this is the actual problem. On Windows, you can use both `/` and `\` for directory separator I think. On most other platforms (Linux, BSD, Unixes, Mac) only `/` is supported afaik.

I see in your Doxyfile, line 774 you use `/` for the `INPUT` config, which does work. But for `INCLUDE_PATH` yo use `\`, which doesn't work. Can you try changing everything to `/` and see if that resolves the issue?

**Comment by mgiaco** [comment]
Many thanks I will look into that later

**Comment by mgiaco** [comment]
@melvinvermeeren  many many thanks that was the problem now everything works as expected.

Where can I buy you a beer?

cheers mathias

**Comment by melvinvermeeren** [comment]
@mgiaco good to hear the issue was resolved! Glad to have been of help. :)

I must admit that Breathe does not currently have any "official" donation address, this may be the first time it is being talked about. If you really insist on it you can buy me a beer through PayPal, the email is the same as on my commits and on my GitHub profile.

Of course this is voluntary. Possibly I will discuss with other maintainers/developers to see if we should create some official way to donate.
