### ISSUE TITLE
Table of Contents Support

### ISSUE THREAD

**Issue by nzjrs** [michaeljones/breathe#38]
Hi,

With a large project, I have a catch-all everything API page, generated via

```
.. doxygenindex::
   :project: onboard
```

It would be great if there was an option which generated the correct table of contents for the resulting docs, as the page is very large and hard to navigate.

**Comment by kitizz** [comment]
+1 this would be great! I'm particularly interested in having the member names in the floating Sidebar as you suggested.

I started navigating the source to see if I had any hope of implementing it. Daunting!
I might try to chip away at it over the next few weeks.

**Comment by melvinvermeeren** [comment]
Probably either `breathe-apidoc` or https://github.com/svenevs/exhale do what is desired. If not, #321 will surely be the answer. Closing for now, comment if you disagree.

**Comment by Hirrolot** [comment]
So briefly, how can I generate a TOC for each header file?

**Comment by vermeeren** [comment]
@Hirrolot See the comment above yours, https://github.com/michaeljones/breathe/issues/38#issuecomment-391434474.
