### ISSUE TITLE
Migrate main project management to GitLab

### ISSUE THREAD

**Issue by vermeeren** [michaeljones/breathe#383]
I would like to make several long-term improvements to project management,
automated testing and automated deployment. GitLab would make such work a lot
easier for me as the current active maintainer.

### The plans for the future

* Manage our own docker container images for CI:
	* Vastly decreased build times, especially for LaTeX.
	* More reliable builds, not depending on pkg installation for each job.
	* Any build environment can be used locally by fetching the docker
	  images and running anything inside them.
* Automatically check for security and other code problems with analysis tools.
* Automatically deploy to PyPI when a version is tagged.
* Automatically build and push documentation for feature branches to staging
  area where a reviewer can review changes without building locally.
* Improved workflow and branching model, commits directly to master will not
  happen.
	* From an issue you can click "create merge request", which will setup
	  a branch and WIP MR for feedback and discussion.
	* Enhanced traceability of code changes, everything is tied to a feature
	  branch and thus tied to an issue.

### Why GitLab?

GitLab is a very integrated platform. This means we will not need to depend on
any third-party services or websites for core parts of the development process.
It also means developers have a better overview of the current state of things
as there are no other sites to be checked. The core feature set is very rich.

I also value software freedom and believe using free, libre, open source tools
where possible should be preferred, especially when the project itself shares
those morals. GitLab CE is free software, EE's code is developed in the open.

Should GitLab at any time take a route we do not like, we can migrate to another
or our own self-hosted instance. Export/Import functionality is available. CE
being free also means it can be forked by the community if needed, the software
always has a future.

### What about GitHub?

I intend to keep the GitHub project and still respond to PRs being created
here. Git is decentralised, so this is no problem.

As for issues, I am fine with any of the following. Note that people can always
create issues (and MRs) on GitLab directly. This is intended for those without a
GitLab account or those that would rather not have one. Currently we **require**
people to have a GitHub account to report issues.

* Use GitLab's "service desk" feature so people can email to a specific mail
  address and it can be handled as an issue on GitLab. The user does not need
  a GitLab account for this.
* Use GitLab's "issue by mail" feature, which works similarly to the above and
  will not require the user to have a GitLab account either.
* People create issues on GitHub, I will handle management and keep them in sync
  with GitLab. This is tricky but can still likely be automated. I would prefer
  one of the above solutions.

**Comment by melvinvermeeren** [comment]
The project has been in low-maintenance mode for almost a year by now, big changes like this currently do not make sense.

This should be re-evaluated when significant Breathe development will be done.

**Comment by melvinvermeeren** [comment]
It appears GitHub actions can solve some of the automation, though at the current stage it appears extremely limited. For example you cannot upload your own docker images have only a few available chooses[1]. Other points still stand though, such as workflow and GitHub itself being proprietary. Thanks for the info though.

[1] https://help.github.com/en/articles/virtual-environments-for-github-actions

**Comment by vermeeren** [comment]
Closing as not relevant currently, see the above.
