### ISSUE TITLE
Referencing C functions does not generate a link

### ISSUE THREAD

**Issue by athei** [michaeljones/breathe#386]
I have the following function defined in **api.h:**
`asec_return_t asec_store_secret(...)`

**api.rst:**
```

API Function Reference
==============================================

.. autodoxygenfile:: api.h
```

**index.rst**
```
.. toctree::
   :hidden:
   
   api

:c:func:`asec_store_secret()`
```

The problem now is that no link to the function is generated:
![screenshot from 2018-06-25 13-26-28](https://user-images.githubusercontent.com/2580396/41847755-6e5c318a-787b-11e8-8329-dce3b9c3a931.png)

This is no link. Just verbatim text. The API documentation itself contains the function. Is there anything I forgot to do?

**Comment by melvinvermeeren** [comment]
If I understand correctly, you want to generate a link from index.rst `asec_store_secret()` to the actual API description located in api.rst. Is that correct?

**Comment by athei** [comment]
Correct!

**Comment by melvinvermeeren** [comment]
I am afraid this currently is not possible with Breathe. Issue #321 and #373 both have suggestions to add this functionality, but I am not sure when this will be implemented. Current developers have a shortage of time, though I have heard signals of new activate ones that may arrive this year.

**Comment by athei** [comment]
But isn't it exactly what is described here:
http://breathe.readthedocs.io/en/latest/domains.html#function-examples

Is the documentation wrong or am I misunderstanding  it?

**Comment by melvinvermeeren** [comment]
The namespace parts do indeed become a link, and when you for example have some `void foo(struct data data);` the `struct data` will resolve to the actual struct definition.

But in both cases the directive will fully render the definition of what you pass to it directly where you put the directive in the rst. So you cannot have your full definition in api.rst and automatically generate short-hand name-only links in index.rst that point to the appropriate entry in api.rst.

**Comment by jakobandersen** [comment]
Could it be that the declaration is not ending up in the C domain (same as  #282?)? You can try referencing it with ``:cpp:func:`` or ``:any:`` instead of `:c:func:` to check that. You can also check how the function is listed in the index page.

**Comment by melvinvermeeren** [comment]
I did not consider trying to reference to like that. I am rather curious to see if that works, if it does we should probably do some documentation updates.

**Comment by athei** [comment]
When using :any:
`WARNING: 'any' reference target not found: asec_store_secret()`

:cpp:func: is the same as :c:func: (not working). 

> You can also check how the function is listed in the index page.
I do not understand. I am a sphinx noob? Which is the index page?

**Comment by melvinvermeeren** [comment]
I think the index page is `genindex.html` in this case, but I am not 100% sure.

**Comment by athei** [comment]
Oops after inspecting `genindex.html` I realized they are all in the C++ domain. When using `:cpp:` it does actually work! I did not mousever properly in my previous test because I thought they should be underlined to be a link.

So is it expected or is there a way to change the domain?

**Comment by melvinvermeeren** [comment]
Yes, please see ` breathe_domain_by_extension` on http://breathe.readthedocs.io/en/latest/directives.html#config-values.

Keep in mind the C domain is currently not as complete as the C++ domain and things may actually disappear from that list as noted in #282.

**Comment by athei** [comment]
Thank you for your help! I guess I stick with the cpp domain then for C.

**Comment by melvinvermeeren** [comment]
Assuming issue has been resolved with the above, closing.
