### ISSUE TITLE
verbatim should not be highlighted as code

### ISSUE THREAD

**Issue by t-b** [michaeljones/breathe#387]
The following C declaration

```cpp
/**
* @verbatim return abcd @endverbatim
*
*  @param[out] dest Destination pointer.
*  @param[in]  src  Source pointer
*  @param      n    number of bytes
*/
void *memcpy(void *dest, const void *src, size_t n);
```

outputs the following XML

```xml
<para><verbatim>return abcd </verbatim></para>
```

and if I look into the HTML output I get

```html
<div class="highlight-default notranslate"><div class="highlight"><pre><span></span><span class="k">return</span> <span class="n">abcd</span>
</pre></div>
</div>
```

The documentation of `verbatim` says in [1]

> Starts a block of text that will be verbatim included in the documentation. The block should end with 
>a \endverbatim command. All commands are disabled in a verbatim block.

so I don't expect syntax highlightning in a verbatim block.

A test repo is at [2].

[1]: http://www.stack.nl/~dimitri/doxygen/manual/commands.html#cmdverbatim
[2]: https://github.com/t-b/breathe-doxygen-filter-test

**Comment by t-b** [comment]
@melvinvermeeren Thanks for looking into that. Can you point me to the code location which needs to be fixed?

**Comment by melvinvermeeren** [comment]
@t-b I suspect `visit_verbatim(self, node)`, which is line 843 is `sphinxrenderer.py`.

This is also where current line stripping and embedded RST is handled, documented here: http://breathe.readthedocs.io/en/latest/markups.html#restructuredtext

I do notice that if the `embed:rst` markup is not used a `literal_block` is inserted. So it could be something is going wrong inside that function, since I do not expect a literal block to do highlighting at all.

**Comment by melvinvermeeren** [comment]
I just checked RST docs, but I suspect the problem may be with Spinx or the HTML theme you are using.

According to 
* http://docutils.sourceforge.net/docs/user/rst/quickref.html#literal-blocks
* http://docutils.sourceforge.net/docs/ref/rst/restructuredtext.html#literal-blocks 

>No markup processing is done within a literal block. It is left as-is, and is typically rendered in a monospaced typeface

I suspect Sphinx is trying to be smart: http://www.sphinx-doc.org/en/stable/markup/code.html

You try try setting `highlight_language` to `none` in the Sphinx `conf.py`.

```
::

	int foo(char c)
```

On one of my own projects this too rendered `int` in a colour, I am using default Sphinx settings.

**Comment by t-b** [comment]
@melvinvermeeren That did the trick!

I'm now using

```
highlight_language = "text"
```

and that also works with highlightning code blocks as I always use rst commands for that.

**Comment by melvinvermeeren** [comment]
Assuming fixed with `highlight_language` settting. Please comment if something is still wrong.
