### ISSUE TITLE
Source Code in Sphinx?

### ISSUE THREAD

**Issue by OliverEvans96** [michaeljones/breathe#388]
Hello,

Thanks for the wonderful package! Is it possible to automatically generate a Sphinx documentation page for C++ source files, such as [in Doxygen](http://libusb.sourceforge.net/api-1.0/libusb_8h_source.html)? I'm not sure I've seen anyone do this yet, but it would be very handy!

Thanks,
Oliver

**Comment by melvinvermeeren** [comment]
Hi,

I think either `breathe-apidoc`, included with Breathe itself, or https://github.com/svenevs/exhale will do what you want. For details see #293. Can you confirm this is what you need?

**Comment by OliverEvans96** [comment]
My goal is for the *full source code* of each source file to have it's own page, as in the [above link](http://libusb.sourceforge.net/api-1.0/libusb_8h_source.html). I don't see this mentioned explicitly in #293, nor do I see it mentioned in the documentation or README for breathe. And I don't see any documentation whatsoever for `breathe-apidoc`, so I'm not sure how to use it or whether it will be helpful.

**Comment by melvinvermeeren** [comment]
I believe the actual source code is not included inside the Doxygen XML, so there is no way for Breathe to get it easily.

Easiest solution is probably go write a simple script that globs over `**/*.{c,h}` or similar and outputs RST files with something like:

```rst
foo.c
=====

.. literalinclude:: /path/to/foo.c
	:language: c
	:linenos:
```

See http://www.sphinx-doc.org/en/stable/markup/code.html for details.

**Comment by OliverEvans96** [comment]
Ah, good idea! I'll look into this when I get a bit more time. Thanks!

**Comment by t-b** [comment]
@OliverEvans96 Or enable `SOURCE_BROWSER` in doxygen and then teach breathe to read the location tags.

```
<location file="filepath" line="13" column="1" bodyfile="filepath" bodystart="13" bodyend="15"/>
```

I would say the main feature here is that I can go directly from the function definition to the function code.

**Comment by melvinvermeeren** [comment]
Should I see this issue as resolved with above comments or should I see this issue as a feature suggestion with the `SOURCE_BROWSER` option and `<location/>` elements?

**Comment by melvinvermeeren** [comment]
No comment in a long time, assuming resolved.

**Comment by hellgheast** [comment]
Is there any concrete solution for this issue ? Or manual editing is still required ?

**Comment by jakobandersen** [comment]
I think it would be nice with more elaboration on what is missing.
Including source code can be done in many ways, and people use Breathe/Sphinx in many different ways. A condensed example of what should happen in which cases would help.

**Comment by hellgheast** [comment]
For me it would be the following way:

* When using a breathe directive you could use an additional option called 
  :show-source: 
  
It would automatically be added after the return parameters of the doxygen documented function in the form of a clickable link that would unfold and show the source code of the given function. 
One issue that could happen is the parsing of the source code for syntax highlighting that could slow the build process.

An example of the usage :

.. doxygenfunction:: foobar
  :project: toto
  :show-sources:

**Comment by debemdeboas** [comment]
I agree with @hellgheast.

It would be very nice to have a hyperlink to the source code from the documentation page itself (exactly like what the viewcode Sphinx extension does).

**Comment by 2bndy5** [comment]
Have you ever looked at the xml for the source code that doxygen generates? Its a nightmare I wouldn't wish on my worst enemy. While I would like to see this feature (implemented like the viewcode extension), maintenance and implementation should be a huge concern.
