### ISSUE TITLE
Problem with using breathe as a git submodule

### ISSUE THREAD

**Issue by pkestene** [michaeljones/breathe#391]
Hello,

while cloning breathe works OK, I noticed that when using it as a git submodule in another project, command *git submodule init/update* provides an error. Indeed, e.g. using project ITKExamples (https://github.com/InsightSoftwareConsortium/ITKExamples), I obtain

```
error: Server does not allow request for unadvertised object cff2d83c9b6c51bb92856f9850b4d11bfab69151
Fetched in submodule path 'Utilities/SphinxExtensions/breathe', but it did not contain cff2d83c9b6c51bb92856f9850b4d11bfab69151. Direct fetching of that commit failed.
```

Can anybody help me understand / fix this ?

Thank you.

**Comment by melvinvermeeren** [comment]
History has been rewritten a while ago to fix #340, also see #384. So indeed old hashes up to a certain point no longer exist. Version tags however still point to the correct moment in time.

Let me know if you need more info.

**Comment by pkestene** [comment]
Thanks for your quick answer.

I tried to add 
    branch = v4.10.0
to the breathe section of my .gitmodule file, but I still get the error about the missing commit (even after starting completely from scratch)

Is there something else I need to do ?

**Comment by melvinvermeeren** [comment]
I believe all that is required is to `cd` into the submodile dir and `git checkout` a currently-existing ref after running the submodule init.

**Comment by pkestene** [comment]
It ok now.
`git checkout` inside submodule dir was indeed needed.

Thanks.
