### ISSUE TITLE
Doxygen like function links from :outline:

### ISSUE THREAD

**Issue by Time0o** [michaeljones/breathe#392]
I would like my generated class documentation to look similar to Doxygen's HTML output in that I want to display an overview of all class members at the top of a page with links to the full member descriptions below. Imo this is the only way to make lengthy API documentation readable at all so I was surprised that I could not figure out how to make this happen. Is this even possible without explicitly listing every member function of every class in reStructuredText?

**Comment by Time0o** [comment]
Yes, Exhale seems to be exactly what I'm looking for, thank you.

**Comment by melvinvermeeren** [comment]
You're welcome. Documentation for these kind of questions is TODO, ref #357.
