### ISSUE TITLE
..doxygenpage

### ISSUE THREAD

**Issue by ferdymercury** [michaeljones/breathe#395]
I can include files as ..doxygenfile, but I can not include Doxygen pages.

Would it be possible to include in the future a ..doxygenpage command?

The reason is that I have a cmake.dox file that I have included in my project, that documents my CMake flags. In my XML build, I get the files
xml/cmake_8dox.xml (this file is void)
xml/cmakePage.xml

I would like to include cmakePage.xml, because the other is void. However I cannot.
..doxygenfile:: cmake.dox 
--> This works, but no output cause xml file is void

..doxygenfile:: cmakePage 
--> WARNING: doxygenfile: Cannot find file "cmakePage

Ideally, one would need:
..doxygenpage:: cmake.dox

Thanks for this nice tool!

**Comment by melvinvermeeren** [comment]
Breathe currently depends on Doxygen to output XML. So anything Doxygen can do but cannot output as XML Breathe will not be able to read. If I understand correctly by Doxygen page you refer to a separate .dox file that contains standalone documentation.

I think in nearly all cases when one is using Breathe+Sphinx rst is used for these kind of standalone pages. Using both Sphinx's rst and Doxygen's dox at the same time and integrated into a single Sphinx HTML build is something I have not heard of before, it seems messy to use multiple documentation systems like that.

PRs are welcome but because of the above I think this is a low priority enhancement, unless we find out a way to make doxygen output XML which will make things easier.

**Comment by ferdymercury** [comment]
Another more simple example. When I use /todo flags in Doxygen, they appear as a Page.

![image](https://user-images.githubusercontent.com/10653970/46110361-66a10180-c1b1-11e8-9728-d76e5b7dfb07.png)
![image](https://user-images.githubusercontent.com/10653970/46110453-a8ca4300-c1b1-11e8-94b3-43b53d49a430.png)


Doxygen generates also a todo.xml

A ..doxygenpage command would be useful to include this in sphinx+breathe.

**Comment by t-b** [comment]
@ferdymercury Your last comment is already an open issue, https://github.com/michaeljones/breathe/issues/258.

**Comment by melvinvermeeren** [comment]
I think I understand what you mean now. Depending on the format/contents of `cmakePage.xml` this may be easy or hard to implement. The priority for now does not change though, there are a number of compatibility issues with recent Sphinx and also a bunch of bugs that need fixing.

**Comment by ferdymercury** [comment]
Thanks for the support. Please find attached two examples of XML pages in case it helps.

[doxypage-examples.zip](https://github.com/michaeljones/breathe/files/2425639/doxypage-examples.zip)

**Comment by mwtoews** [comment]
I'm also looking at this issue. For example, a `myfile.dox` file with:
```
/*!

\page general_doc General documentation

\section blah Blah berg

Text.

*/
```
This content gets translated by doxygen to `myfile.xml`, but there is no easy way to get breathe to digest it. A `doxygenpage` directive would be handy!

**Comment by mwtoews** [comment]
Or better yet, see the existing example file [page.doc](https://github.com/michaeljones/breathe/blob/d5486d7e401d0580b073b1e620c7bd92f5e22793/examples/doxygen/page.doc). I don't see how this example is used, and I'm looking for it ...

**Comment by mwtoews** [comment]
The current output from the breathe test suite is partial. Here is the doxygen source:
```
/*! \page page1 A documentation page
  Leading text.
  \section sec An example section
  This page contains the subsections \ref subsection1 and \ref subsection2.
  For more info see page \ref page2.
  \subsection subsection1 The first subsection
  Text.
  \subsection subsection2 The second subsection
  More text.
*/

/*! \page page2 Another page
  Even more info.
*/
```
and breathe's sphinx-rendered HTML [here](https://breathe.readthedocs.io/en/latest/doxygen.html#page):

## Page
_file_ **page.doc**

_page_ **page1**
&nbsp;&nbsp;&nbsp;&nbsp; Leading text.

_page_ **page2**
&nbsp;&nbsp;&nbsp;&nbsp; Even more info.

----

The expected output should look more like doxygen's HTML output:

# A documentation page
Leading text.

## An example section
This page contains the subsections The first subsection and The second subsection. For more info see page Another page.

### The first subsection
Text.

### The second subsection
More text.

**Comment by utzig** [comment]
This was implemented by #596.  To import the todo.xml just use `.. doxygenpage:: todo`. More documentation: https://breathe.readthedocs.io/en/latest/directives.html#doxygenpage

**Comment by vermeeren** [comment]
Indeed not entirely sure of the "page" here is the same as the xrefitem-based page the breathe `doxygenpage` directive now handles. Needs further investigation.

**Comment by utzig** [comment]
> The current output from the breathe test suite is partial. Here is the doxygen source:

Yeah, yesterday I found out that `\section` is not supported. `\section` is only valid inside a `\page` and `\page` has only been supported since #596, so this was not a problem before, but I happen to have bumped into the same issue yesterday (as well as `\table` support), so I will probably implement this.


> Indeed not entirely sure of the "page" here is the same as the xrefitem-based page the breathe `doxygenpage` directive now handles. Needs further investigation.

I am quite sure it is now! ;-)
