### ISSUE TITLE
Support doxygen commands @ref and @anchor

### ISSUE THREAD

**Issue by t-b** [michaeljones/breathe#400]
Both commands can be used in doxygen to create cross references. PR #280 shows that it currently does not work.

**Comment by utzig** [comment]
Commits 14f9581ab7bf8fc6797757cf5addfd31a127c8f2 and fca973205e4fa670cabd0e16ffff86984cce5e36 added some support for parsing `\anchor` at least under some specific circumstance (in the `kind="page"` blocks). Should be straight-forward to update the code to parse them in the more general settings. Also I thought I had used `\ref` successfully already, but I may be wrong. I will double check those.

**Comment by utzig** [comment]
> Commits [14f9581](https://github.com/michaeljones/breathe/commit/14f9581ab7bf8fc6797757cf5addfd31a127c8f2) and [fca9732](https://github.com/michaeljones/breathe/commit/fca973205e4fa670cabd0e16ffff86984cce5e36) added some support for parsing `\anchor` at least under some specific circumstance (in the `kind="page"` blocks). Should be straight-forward to update the code to parse them in the more general settings. Also I thought I had used `\ref` successfully already, but I may be wrong. I will double check those.

I just tested `\ref` and `'\anchor` together and they are working now.

**Comment by t-b** [comment]
@utzig Nice! Is that in v4.24.1 or do I need the git version for that?

**Comment by utzig** [comment]
> @utzig Nice! Is that in v4.24.1 or do I need the git version for that?

v4.24.1
