### ISSUE TITLE
Add role in order to directly link to breathe directives

### ISSUE THREAD

**Issue by SteinHeselmans** [michaeljones/breathe#409]
Breathe directives generates anchor points on the locations where the doxygen documentation is inserted. Could these anchorpoints be linked to using a role?

Example:

```
.. doxygenfunction:: foo

Link to the documentation of :breathe-link:`foo`.
```

Suggestion is to add a role (`breathe-link` in the example) for this. Or is this possible by other means?

**Comment by melvinvermeeren** [comment]
I believe this may be the same issue as #321, although perhaps with a slightly different rendering output.

For now however I read something about how you can link to stuff manually using regular Sphinx references by using the c/cpp domain. This is not as clean as #321 and your proposal, but may get the job done. See #153 and perhaps others.

**Comment by melvinvermeeren** [comment]
Can you verify if this issue is indeed the same as one of the above? In that case this one can be closed.

**Comment by melvinvermeeren** [comment]
No reply, closing.
