### ISSUE TITLE
require a newer version of Sphinx

### ISSUE THREAD

**Issue by alfredodeza** [michaeljones/breathe#416]
The requirement for Sphinx is set to:

    Sphinx>=1.4

But since this commit: https://github.com/michaeljones/breathe/commit/1799bb9d it is no longer possible to use Sphinx that is 1.8.4 or older (see https://github.com/sphinx-doc/sphinx/commit/6d52b63eee) 

If an environment with anything 1.8.4 or older will break with:

    AttributeError: 'module' object has no attribute 'CPPUnionObject'

**Comment by melvinvermeeren** [comment]
Yeah, it appears this should be changed to `Sphinx>=1.8`. I'll do this soon, thanks for reporting!

**Comment by t-b** [comment]
@melvinvermeeren While you are at it, why not add a `requirements.txt` for pip?

**Comment by alfredodeza** [comment]
what would the `requirements.txt` provide that `setup.py` doesn't @t-b  ?

**Comment by t-b** [comment]
@alfredodeza With a requirements.txt developers can just do `pip install -r requirements.txt` to install the dependencies, setup.py does not help here. See also https://stackoverflow.com/a/43659126.

**Comment by melvinvermeeren** [comment]
the `requirements.txt` appears to be inside `requirements/production.txt`, though it is also outdated, will fix this too while I'm at it

**Comment by melvinvermeeren** [comment]
could you review the PR and see if this is fine?
