### ISSUE TITLE
support for `internal` modifier in c#

### ISSUE THREAD

**Issue by noname77** [michaeljones/breathe#422]
First, thanks for this great project.

I am aware that breathe (and sphinx) does not support c#, but apart from some quirks with properties (as in #249 ) i have been using it with good results for public members so far.

I am now trying to build internal documentation for my project which would require generating documentation for `internal` members.

I know this is language specific, but would it be possible, by any chance, to have something similar to `:protected-members:` directive, i.e. `:internal-members:` or `:package:members:`, that would enable to show these correctly?

slightly eddited sample xml:

```xml
<codeline lineno="123">
    <highlight class="normal"><sp/><sp/><sp/><sp/></highlight>
    <highlight class="keyword">internal</highlight>
    <highlight class="normal"><sp/></highlight>
    <highlight class="keywordtype">void</highlight>
    <highlight class="normal"><sp/><ref refid="class_foo_bar" kindref="member">Boo</ref>()</highlight>
</codeline>

<sectiondef kind="package-func">
    <memberdef kind="function" id="class_foo_bar" prot="package" static="no" const="no" explicit="no" inline="yes" virt="non-virtual">
    </memberdef>
</sectiondef>

<listofallmembers>
    <member refid="class_foo_bar" prot="package" virt="non-virtual">
        <scope>Foo::Bar</scope>
        <name>Boo</name>
    </member>
</listofallmembers>
```

For now i am replacing:
  - `internal` keyword with `protected`,
  - `kind="package-func"` with `kind="protected-func"` and
  - `prot="package"` with `prot="protected"`

after the xml is generated and using `:protected-members:`, which apart from misleading header `Protected Functions` works fine. 

Could you maybe suggest something better?

python from my conf.py for reference:

```python
read_the_docs_build = os.environ.get('READTHEDOCS', None) == 'True'

if not read_the_docs_build:
    subprocess.call('pwd; cd ./doxygen; doxygen', shell=True)

    # change internal members into protected members
    directory = './doxygen/doxyxml'
    for file in os.listdir(directory):
        with open("{}/{}".format(directory,file)) as f:
            newText=f.read() \
                     .replace('>internal<', '>protected<') \
                     .replace('kind="package-func"', 'kind="protected-func"') \
                     .replace('prot="package"', 'prot="protected"')

        with open("{}/{}".format(directory,file), "w") as f:
            f.write(newText)
```

Best,
nnm

**Comment by melvinvermeeren** [comment]
To properly implement this probably some kind of real support for c# is needed instead of the current hack. Sphinx has no C# domain but someone else has made one, though I have no experience with it. See #249 for more info.

**Comment by melvinvermeeren** [comment]
General C# support will be tracked under #249, closing this one in favour of it.
