### ISSUE TITLE
Option to remove namespace scopes from index entries

### ISSUE THREAD

**Issue by spflueger** [michaeljones/breathe#426]
Hi,

I would like to show entries in the `genindex` generated by sphinx without the namespace scope, and rather add the namespace information at the end in parenthesis.

Example: I want a class `Foo::Bar::HelloWorld` to appear in the index under `H` as `HelloWorld (in namespace Foo::Bar)`

Using the `add_module_names = False` option in sphinx had no effect.

Is this currently possible?

**Comment by jakobandersen** [comment]
I think the ``add_module_names`` config option is only used in the Python domain of Sphinx. You can instead use [``cpp_index_common_prefix``](https://www.sphinx-doc.org/en/master/usage/configuration.html#confval-cpp_index_common_prefix). There is however not yet an option to mention the stripped prefix on the item. You are welcome to open a feature request on the Sphinx repo.

**Comment by spflueger** [comment]
Thanks! That's what I was looking for. I close this issue then.
