### ISSUE TITLE
going wrong with doxygen + sphinx

### ISSUE THREAD

**Issue by ArrowYL** [michaeljones/breathe#430]
Here is my conf.py(**partial**)

extensions = [
    'sphinx.ext.mathjax',
    'sphinx.ext.imgmath',
    'sphinx.ext.todo',
    'breathe'
]

breathe_projects = {
    "QPanda2 - Core":"../../xml/",
    }

sys.path.append("C:\ProgramData\Anaconda3\Lib\site-packages\breathe")`

**I want the final result like this**
![image](https://user-images.githubusercontent.com/40817741/56280711-5ba5c280-613d-11e9-9de7-987136f9c8d4.png)

So i set doxygen xml =yes
here is my doxygen config
DOXYFILE_ENCODING      = GB2312
PROJECT_NAME           = "QPanda2 - Core"
OUTPUT_DIRECTORY       = C:\Users\QuantumBYLZ061902\Desktop\Docs
CREATE_SUBDIRS         = YES
ALLOW_UNICODE_NAMES    = YES
OUTPUT_LANGUAGE        = Chinese
EXTRACT_ALL            = YES
EXTRACT_PACKAGE        = YES
EXTRACT_STATIC         = YES
HIDE_UNDOC_MEMBERS     = YES
INPUT                  = D:\QPanda2\include\Core
INPUT_ENCODING         = GB2312
RECURSIVE              = YES
EXCLUDE                = QPanda2/include/Core/VirtualQuantumProcessor/SingleAmplitude/TensorEngine.h \
                         QPanda2/include/Core/VirtualQuantumProcessor/SingleAmplitude/TensorNode.h \
                         QPanda2/include/Core/VirtualQuantumProcessor/SingleAmplitude/QuantumGates.h
EXCLUDE_PATTERNS       = *.h
SOURCE_BROWSER         = YES
GENERATE_HTMLHELP      = YES
CHM_FILE               = test.chm
HHC_LOCATION           = "C:/Program Files (x86)/HTML Help Workshop/hhc.exe"
CHM_INDEX_ENCODING     = GB2312
TOC_EXPAND             = YES
GENERATE_LATEX         = NO
MACRO_EXPANSION        = YES
EXPAND_ONLY_PREDEF     = YES
INCLUDE_FILE_PATTERNS  = PROTECT=PRIVATE
CLASS_DIAGRAMS         = NO
CALL_GRAPH             = YES
CALLER_GRAPH           = YES
DOT_PATH               = "C:\Program Files (x86)\Graphviz2.37\bin"

Then i add doxygenindex in index.rst 
**.. doxygenindex:: module**
But the wrong message is 
![image](https://user-images.githubusercontent.com/40817741/56281162-817f9700-613e-11e9-9b63-f4b849c13a23.png)

How to solve this problems? thanks.

**Comment by svenevs** [comment]
Please try pinning `Sphinx==1.8.5` in your docs setup. This error arose with Sphinx 2.x, unfortunately I haven't had time to get to the bottom of where it comes from and produce a meaningful error report here to begin trying to fix it.

**Comment by jakobandersen** [comment]
I think it is fixed with #411.

**Comment by svenevs** [comment]
I am closing this now that #411 is merged (thanks @jakobanderson!).

@ArrowYL please reopen if the latest breathe (4.13 at this time) does not fix your problem. Please use Sphinx 2+.
