### ISSUE TITLE
AttributeError: 'str' object has no attribute 'node_type' 

### ISSUE THREAD

**Issue by alfredodeza** [michaeljones/breathe#433]
Starting today (Apr 22nd) we've are seeing issues building the Ceph docs using breathe's master tip. The error in our build logs are not very good:

    reading sources... [ 56%] rados/api/librados
    
    Exception occurred:
      File "/home/jenkins-build/build/workspace/ceph-pr-docs/build-doc/virtualenv/local/lib/python2.7/site-packages/breathe/renderer/filter.py", line 320, in __call__
        raise e
    AttributeError: 'str' object has no attribute 'node_type'

Stepping through the build, I can see that it is `[in ]`:

    ipdb> data_object
    '[in] '
    ipdb> data_object.node_type
    *** AttributeError: 'str' object has no attribute 'node_type' 

I suspect it has to do with this commit https://github.com/michaeljones/breathe/commit/ffe227a5c9f79a4f9cd3571795bcf10ee6f903e3 but I am not 100% sure.

In any case, what would be a good way to fix this on our end? We will probably pin to the previous release (and stop using master!).

Any pointers would be great.

**Comment by melvinvermeeren** [comment]
I think this may effectively be the same as #431. Breathe v4.13.0 is now compatible with Sphinx 2, which could mean it is not compatible with Sphinx 1. Sphinx 2 in turn requires python>=3.5.

The fact that pip will pull in v4.13.0 for a python2 and/or sphinx 1 build in a packaging error in Breathe which PR #432 should fix within 24hours. v4.12.0 will then be the last version for python2 and/or sphinx 1.

If you have some experience with python packaging a quick review or 432 would help, I am not very familiar with Wheels myself.

**Comment by melvinvermeeren** [comment]
See comment in #431, feedback would be useful.

**Comment by alfredodeza** [comment]
If non-backwards compatibility is being proposed for v4.13.0 it might make sense to bump the major version to v5.0.0 ?

**Comment by melvinvermeeren** [comment]
Breathe itself has not changed any commands, logic or configuration options, meaning it is backwards compatible with previous versions. Because of this I believe the major version should stay the same.
