### ISSUE TITLE
Support for C++/CLI: Someone is tripping on special characters '!', '%', '^'

### ISSUE THREAD

**Issue by Mitch9192** [michaeljones/breathe#434]
I currently use breathe to document our C and C++ API's.  Additionally we have a python API that is also generating in this same environment (sphinx directly).  We are currently in the process of adding a C++/CLI API for our .NET users and I would like to keep all of our documentation in the same environment.

I am aware that there is no documentation stating that breathe supports C++/CLI, **but it is soooo close.**  Documentation is generated however, any function that contains one of the following special characters ('!', '%', '^') is not linked appropriately.  Would anyone care to point me to the right place in this project so that I can contribute by adding this functionality?  Should I start in the Parser?  or in the Render section? Is it even possible?

```
namespace fooSpace {
    public ref class FooBarClassWrapper
    {
        public:

        /// Constructor.
        FooBarClassWrapper(FooBarClass& timer);

        /// Destructor
        ~FooBarClassWrapper();

        /// Finalizer
        !FooBarClassWrapper();

        /// Gets the bar
        /// \param bar Bar of which to get
        err getBar(UInt32% bar);

        /// Sets the bar
        /// \param bar Bar of which to set
        err setBar(const Int32 bar);

        private:
            FooBarClass& _foobar;
    }; 
}
```

Each class produces rolling error starting with the finalizer ! (FYI: these were copy and pasted so the -----^ likely are not in the correct locations.

FooBarClassWrapper.rst:6: WARNING: Error when parsing function declaration.
If the function has no return type:
Error in declarator or parameters and qualifiers
Invalid definition: Expected identifier in nested name. [error at 43]
FooBarClassWrapper::!FooBarClassWrapper()
  -------------------------------------------^
If the function has a return type:
Invalid definition: Expected identifier in nested name. [error at 43]
FooBarClassWrapper::!FooBarClassWrapper()
  -------------------------------------------^
FooBarClassWrapper.rst:6: WARNING: Error when parsing function declaration.
If the function has no return type:
Error in declarator or parameters and qualifiers
Invalid definition: Expecting "(" in parameters_and_qualifiers. [error at 5]
err FooBarClassWrapper::getBar(Int32 % bar)

My rst.
```
=======================================================================
FooBar Class
=======================================================================

    .. doxygenclass:: fooSpace:: FooBarClassWrapper
        :project: fooBarCLI
        :members:
        :private-members:
        :protected-members:
```

What have I done?
 * Setup Doxygen to produce html output.  All linking is correct.  No errors with special characters.
 * Did a find of all '%' characters and replaced them with '*' in the xml output of Doxygen.  This produces the correct affect after running Sphinx with breathe. (returning them to '%' brings the errors back).  This is just to prove the xml is correct
 * Inspecting the html output of sphinx it is easy to tell that they blocks containing the special characters are not formed the same.  They lack the linkage the others have.
 * Hacking up one of the unit test (test_param-decl) in the breathe project shows that it can in fact handle the '%' (in this limited scope at least).  So is this a sphinx problem?`self.assertEqual(get_param_decl(memberdef.param[3]), 'int % d')` 
   ```
   <param>
       <type>int %</type>
       <declname>d</declname>
   </param>
   ```

I know this is mainly a place for issues, but I have been banging my head for weeks and I could use just a little help.  Thanks.

**Comment by rowanG077** [comment]
This is a Sphinx issue. What Breathe does is create cpp domain objects based on the XML output of doxygen. You can still create these domain objects manually in your restructured text like this:

```
.. cpp:function:: err getBar(UInt32% bar)

   A function with parameters and types.
```

Doing it like this throws the warnings your are talking about. See http://www.sphinx-doc.org/en/master/usage/restructuredtext/domains.html#directive-cpp:function for how to manually create the domain objects.

**Comment by jakobandersen** [comment]
As @rowanG077 rightly points out, the first (only?) problem is that C++/CLI is not supported in Sphinx. If you open an issue over there we can discuss what would be needed.

**Comment by Mitch9192** [comment]
@rowanG077 @jakobandersen 
Thank you so much!  Just knowing where I need to focus is a HUGE help.  

Closing as my problem resides with Sphinx.
