### ISSUE TITLE
Cross-referencing from doxygenfile to Sphinx

### ISSUE THREAD

**Issue by williamjamir** [michaeljones/breathe#456]
I would like to generate a link from the `file.h` into a `myfile.rst`m how can I do that?

Example, which tag/command from doxygen is necessary to create link for the following section:

```
.. _link_to_section

Section
=======

Some text
```

I've tried `@ref` but it's not working =/

```
 /*!
    Some nice title

    @ref plugin-by-example-section

    @param[in] int Hi
*/
int my_func(int)
```

**Comment by dbkinder** [comment]
Use verbatim rst content in the doxygen comment and you can reference the document label using ``:ref:`link_to_section` ``.  You'll need to fix a typo in the example above ``.. _link_to_section:`` (missing the colon at the end).

**Comment by melvinvermeeren** [comment]
I also think the above is a good way (among many) to handle this. Assuming OP's problem has been solved by now.
