### ISSUE TITLE
"Permalink to this definition" is missing with C++ overloaded functions.

### ISSUE THREAD

**Issue by bkaradzic** [michaeljones/breathe#458]
I noticed that C++ overloaded functions in my documentation are missing permalinks.

You can see example here:

https://bkaradzic.github.io/bgfx/bgfx.html#_CPPv4N4bgfx9getResultE20OcclusionQueryHandleP7int32_t

At the bottom you can see that function:

`void bgfx::destroy(OcclusionQueryHandle _handle)`

doesn't have "Permalink to this definition".

I tried looking at documentation and issues here, but I couldn't find anything to fix this issue.

**Comment by jakobandersen** [comment]
Which version of Sphinx and Breathe are you using?

**Comment by bkaradzic** [comment]
sphinx-apidoc 2.2.1
Breathe (breathe-apidoc) 4.13.1

**Comment by vermeeren** [comment]
This might be fixed in v4.18.1, could you test again @bkaradzic ?

**Comment by bkaradzic** [comment]
@vermeeren This is fixed. Thanks!
