### ISSUE TITLE
Process doxygen comments both in the header and the source of a function

### ISSUE THREAD

**Issue by SebastienBocquet** [michaeljones/breathe#460]
I am documenting a C++ project with Sphinx+breathe and it went well, thanks for maintaining this useful tool.
I am using the doxygen groups and the doxygengroup command to obtain a given granularity in the documentation. In addition, I would like to place some doxygen comments both in the header files and in the source of the functions. An example is given below. It is mostly based on the examples/specific/group example in breathe arbo.
Processing this with doxygen allows to see the comment "doc in source of publicFunction" in the member function documentation. However, using breathe with the following command

.. doxygengroup:: mygroup    
  :project: group    
  :content-only:    
  :members:

I cannot see this comment. Only the comments in the .h are visible. Is there any way to obtain the documentation for both the header comments and source comments?
Regards,
Sebastien

group.h:
/** @defgroup mygroup My Group    
   *  This is the first group    
   *  @{    
   */    
  //! \brief first class inside of namespace
  class GroupedClassTest {    
  public:    
      //! \brief namespaced class function    
      virtual void publicFunction() const = 0; 
  }

group.c:
#include "group.h"                                  
void GroupedClassTest::publicFunction(){    
    //! doc in source of publicFunction    
}

group.cfg:
PROJECT_NAME     = "Group Test"               
OUTPUT_DIRECTORY = group                     
GENERATE_LATEX   = NO    
GENERATE_MAN     = NO                           
GENERATE_RTF     = NO         
CASE_SENSE_NAMES = NO                         
INPUT            = group.h, group.c, reproducer.h    
QUIET            = YES    
JAVADOC_AUTOBRIEF = YES    
GENERATE_HTML = YES    
GENERATE_XML = YES

Sphinx conf.py:
breathe_projects = {
      "group": "doxygen/group/xml"
  }

**Comment by melvinvermeeren** [comment]
I believe this comes down to alias support in the end as parsing both headers and sources will result in duplicate declarations. Can you check #405?

**Comment by melvinvermeeren** [comment]
No reply, assuming fixed.
