### ISSUE TITLE
How to reference to generated docs

### ISSUE THREAD

**Issue by MaJerle** [michaeljones/breathe#464]
It seems I do not understand or it is not possible, how to do it.

I have a .rst with directive `.. doxygengroup:: MYGROUP` and it nicely generates all the functions, typededs, etc in this file => very nice.

Now I have second .rst file and I would like to reference from there to description of my function in first .rst file.

`api.rst`: Doxygen generated description
```
.. doxygengroup:: MYGROUP

# part of MYGROUP is function "input" and its description is well generated
```

`how-to.rst`: Here I want to reference to function `input`
```
..
Please check function :ref:`input` for more information.
..
```

How do I properly reference function `input` in *how-to.rst* file to generate a link to its description in *api.rst* file?

**Comment by melvinvermeeren** [comment]
Have you tried the sphinx c/cpp family of directives? Don't know where the docs are, though #463 has an example.

**Comment by jakobandersen** [comment]
There are both object-specific roles for cross referencing, e.g., for functions it is ``:cpp:func:`input` ``, and a generic role for referencing any kind of object: ``:cpp:any:`input` ``.

See also http://www.sphinx-doc.org/en/master/usage/restructuredtext/domains.html#cross-referencing

**Comment by MaJerle** [comment]
Thanks to both of you, it magically works with *c:any:`input`*.

Is there a way to output sphinx warning if there is no item with specified name?
