### ISSUE TITLE
readthedocs.org Out of sync 

### ISSUE THREAD

**Issue by AlbertMietus** [michaeljones/breathe#475]
The docs of breathe on RTfD look very old 

See:
https://readthedocs.org/projects/breathe/builds/

**Comment by vermeeren** [comment]
@michaeljones do you have any idea what is up with RTD and how it works? I assume it is tied to some sort of account in some way?

**Comment by vermeeren** [comment]
@michaeljones Can you check the above and see what the problem is in RTD? Only your name is in the maintainers profile of RTD, see https://readthedocs.org/projects/breathe/.

If you don't have time that's also fine, could you leave a reply in that case too? I intend to move official Breathe docs to one of my (self-maintained) webservers in that case, as I am not familiar with RTD.

**Comment by michaeljones** [comment]
@vermeeren - sorry, I have been in the habit of dismissing Breathe notifications. I certainly have time to explore this. I'll have a look.

**Comment by michaeljones** [comment]
@vermeeren - not that I wish to put more responsibility on your shoulders but I can add you to the readthedocs project if you sign up there? At least then I'm not a single point of failure.

**Comment by vermeeren** [comment]
@michaeljones Yeah that's probably a good idea, just created an account, username is vermeeren as usual.

**Comment by vermeeren** [comment]
@michaeljones Checking the page at https://readthedocs.org/dashboard/breathe/integrations/ it currently gives a 400 bad request, from the exchange log:

```json
{
  "detail": "Payload not valid, invalid or missing signature"
}
```

I cannot see the GitHub side of things but I suspect something isn't setup properly there or there needs to be a "resync webhook" action on RTD side. Could you check a bit further?

**Comment by michaeljones** [comment]
Thanks for the heads up. I'll look into it.

**Comment by michaeljones** [comment]
The advice seems to be to delete the re-create the integrations on both sides. I've done that. Oddly Github seems to create two so I've deleted the one that seemed to be unnecessary.

I've attempted to test it by pushing a "test-rtd" branch and that seems to have triggered 200 (success) on the ReadTheDocs side. I'm afraid we're going to have to once more wait and see if it behaves itself for the `master` branch but I think it is looking more hopeful.

**Comment by vermeeren** [comment]
I just found it still fails, notably RTD does the following:

```
 /home/docs/checkouts/readthedocs.org/user_builds/breathe/envs/latest/bin/python -m pip install --upgrade --no-cache-dir Pygments==2.3.1 setuptools==41.0.1 docutils==0.14 mock==1.0.1 pillow==5.4.1 alabaster>=0.7,<0.8,!=0.7.5 commonmark==0.8.1 recommonmark==0.5.0 sphinx<2 sphinx-rtd-theme<0.5 readthedocs-sphinx-ext<1.1 
```

I noticed the `.readthedocs.yml` just needs to be updated to fix this, using our project's `requirements.txt` properly. https://docs.readthedocs.io/en/stable/config-file/v2.html

I will create patch for this within a few hours hopefully.

**Comment by michaeljones** [comment]
Thank you for handling it, @vermeeren.
