### ISSUE TITLE
Improve parameter formatting in output

### ISSUE THREAD

**Issue by michaeljones** [michaeljones/breathe#48]
Currently they all go on one line which doesn't help much. Probably put each one on a new line for functions with more than one argument. Also investigate outputting non-breaking spaces through restructuredText.

**Comment by vitaut** [comment]
I suggest leaving the question of formatting parameters to Sphinx, because if we try doing it ourselves it will be inconsistent with the formatting produced by standard Sphinx directives. IMHO the current formatting looks fine for reasonable number of arguments (<= 5).

**Comment by michaeljones** [comment]
Good call mate. Sound logic. Thanks for digging through the back log a little :)
