### ISSUE TITLE
Error parsing UDLs

### ISSUE THREAD

**Issue by mpusz** [michaeljones/breathe#481]
The code as below

```cpp
namespace units::si {

inline constexpr auto planck_constant = 6.62607015e-34q_J * 1q_s;

}
```

causes the following error:

```
WARNING: Invalid definition: Expected end of definition. [error at 58]
[build]   constexpr auto units::si::planck_constant = 6.62607015e-34q_J * 1q_s
[build]   ----------------------------------------------------------^
```

**Comment by jakobandersen** [comment]
I'm very sure this is a Sphinx issue as UDLs in expressions are simply not yet supported (https://github.com/sphinx-doc/sphinx/blob/3.x/sphinx/domains/cpp.py#L4770). It would be great if you could open an issue over there, thanks.

**Comment by mpusz** [comment]
Done sphinx-doc/sphinx#7294.

**Comment by jakobandersen** [comment]
Fixed in the 3.x branch of Sphinx (future v3.1).
