### ISSUE TITLE
Bug in generated HTML when using function pointer inside a struct

### ISSUE THREAD

**Issue by pdrtrifork** [michaeljones/breathe#489]
We have noticed a bug in the documentation generated for structs containing function pointers.

I have created a repository showcasing the issue here: https://github.com/pdrtrifork/breathe-struct-with-fp

An example of the output we get - notice the missing `(*`:

![alt output](https://github.com/pdrtrifork/breathe-struct-with-fp/blob/master/output.png?raw=true "Sphinx Output")

**Comment by vermeeren** [comment]
Should be fixed with #512, released in Breathe v4.17.0. Note that you also need Sphinx 3.x for recent Breathe versions.
