### ISSUE TITLE
C "#define" does not expend the macros

### ISSUE THREAD

**Issue by WuYingzheng** [michaeljones/breathe#493]
Hi all,

if i have macro in c header file,
`#define MIN(a, b)   ((a)>(b)? (b):(a))`

it seems that breathe won't expend it for me, it generate the following:
```
Define
        MIN(a, b)
```
However, i would like to show the expansion, just like the doxygen's output:
```
Define
        MIN(a, b) ((a)>(b)? (b):(a))
```
Is that possible or can you add this feature to breathe?

Thank you.

**Comment by WuYingzheng** [comment]
sorry, 
    it is already supported.
    i watched the source code,  then set the
`breathe_show_define_initializer = True`
it works.

but is there any method to insert extra whitespace between define name and initializer?
`MIN(a, b)   <----    more whitespace     ---->       ((a)>(b)? (b):(a))
`
Thank you.

**Comment by vermeeren** [comment]
> but is there any method to insert extra whitespace between define name and initializer?

I suspect whitespace like this is ignored and/or stripped, you could try with Sphinx 3 and #491, perhaps the new C domain has different behaviour but I very, very much doubt so.

**Comment by jakobandersen** [comment]
The macro definition is appended by Breathe (for now (perhaps Sphinx should be able to record the definition as well)). Generally, formatting is done by some combination of docutils nodes and then things specific for output formats (e.g., CSS for html, or extra macros for Latex). I don't know if there is a docutils node for doing this particular thing.

**Comment by vermeeren** [comment]
I suppose the conclusion is that this is up to the theme or at the very least outside of Breathe's scope, as it is about rendering. Closing this because of this, comment if you disagree.
