### ISSUE TITLE
Workaround for lack of @file filter

### ISSUE THREAD

**Issue by lshamis** [michaeljones/breathe#499]
Hey folks,

I'd like to structure a page somewhat like
```rst
Packets
=====================================

.. doxygenfile:: packet.h
   :file-only:

C API
-------------------------------------

.. doxygenstruct:: a0_packet_header_t
   :members:

.. doxygenstruct:: a0_packet_payload_t
   :members:

C++ API
-------------------------------------

.. doxygenclass:: a0::PacketHeader
   :members:

.. doxygenclass:: a0::PacketPayload
   :members:
```

Since `file-only` doesn't exist, I tried to be clever:
```rst
Packets
=====================================

.. doxygenfile:: packet.h

C++ API
-------------------------------------

.. doxygenclass:: a0::PacketHeader
   :members:

.. doxygenclass:: a0::PacketPayload
   :members:
```

Adding 
```cc
/**
 * /rst
 * C Api
 * -------------------------------------
 * /endrst
 */
```
to `packet.h`

Note: The documentation lives with the C API. There is another file that provides a minimal C++ wrapper.

This, of course, failed with:
```
<breathe>:1: WARNING: Unexpected section title.

C Api
-------------------------------------
```

For code readability reasons, I'd like to keep the overall description with the C API and would prefer not to duplicate it.

I haven't found any way to name & reference a standalone comment block...

Is there another approach, or is this not supported?

**Comment by vermeeren** [comment]
I am not entirely sure what you are trying to achieve here, can you elaborate?
