### ISSUE TITLE
cannot reference overloaded/class members

### ISSUE THREAD

**Issue by rdiankov** [michaeljones/breathe#5]
How would we reference overloaded member functions? Perhaps it is possible to do this by adding the number of arguments, and a string hint for the type of each argument..

In addition to that, it would really help if we can specify the class name the member function belongs to.

**Comment by vitaut** [comment]
It is possible to reference overloaded member functions now:

```
class C {
  /** Test function. */
  void f(int);

  /** Another test function. */
  void f(char);
};

.. doxygenfunction:: C::f(char)
```

Closing?

**Comment by michaeljones** [comment]
I think so. It can be reopened if it seems to be missing something. Cheers for checking these older tickets and sweeping up!
