### ISSUE TITLE
Error in declarator or parameters

### ISSUE THREAD

**Issue by StrikerRUS** [michaeljones/breathe#500]
Now that https://github.com/sphinx-doc/sphinx/issues/7423 is merged and Sphinx `3.0.1` is released, we can say that breathe `4.15.0` has a regression problem with some function definitions which worked well before.

Repro can be taken from my comment in Sphinx repo: https://github.com/sphinx-doc/sphinx/issues/7423#issuecomment-610668512.

The problem is in the following functions.

```
LIGHTGBM_C_EXPORT int LGBM_BoosterFree(int handle);
```

```
Warning, treated as error:
/home/travis/build/microsoft/LightGBM/docs/C-API.rst:4:Error in declarator or parameters
Invalid C declaration: Expected identifier in nested name, got keyword: int [error at 21]
  LIGHTGBM_C_EXPORT int LGBM_BoosterAddValidData(BoosterHandle handle, const  DatasetHandle valid_data)
  ---------------------^
Makefile:20: recipe for target 'html' failed
```

Or is it a bug at Sphinx side?

**Comment by jakobandersen** [comment]
This is something that should be enhanced on the Sphinx side. The problem is that it is not a valid function declaration, though I guess ``LIGHTGBM_C_EXPORT`` expands to an an attribute for symbol visibility? I have opened an issue to track the feature.

**Comment by StrikerRUS** [comment]
@jakobandersen Thank you very much for that prompt response!

Here is the `LIGHTGBM_C_EXPORT` definition: https://github.com/microsoft/LightGBM/blob/master/include/LightGBM/export.h

**Comment by jakobandersen** [comment]
This should be fixed in Sphinx 3.0.2 once it is released (you can try with the 3.0.x branch). You will need to put
```python
c_id_attributes = ['LIGHTGBM_C_EXPORT']
```
in ``conf.py`` to tell the parser to recognize the custom attribute.

**Comment by StrikerRUS** [comment]
Thanks a lot for the prompt fix! I'll try it on RTD site right after the 3.0.2 release.

**Comment by StrikerRUS** [comment]
@jakobandersen Everything works fine with Sphinx 3.0.2! Thank you very much for the awesome support!
