### ISSUE TITLE
Latex Math results in empty formulas

### ISSUE THREAD

**Issue by maximiliank** [michaeljones/breathe#502]
I tried to test the example from the documentation https://github.com/michaeljones/breathe/blob/master/documentation/source/latexmath.rst.

In the current version with Sphinx 3.0.1 both formulas are empty:
```html
<p>A class. </p>
<p>A inline formula: <span class="math notranslate nohighlight">\(\)</span></p>
<p>A display style formula: <div class="math notranslate nohighlight">
\[\]</div>
 </p>
```

With Sphinx 2.4.4 and breathe 14.4.2 the inline formula is working but the other formula is still missing:
```html
<p>A class. </p>
<p>A inline formula: <span class="math notranslate nohighlight">\( f(x) = a + b \)</span></p>
<p>A display style formula: <div class="math notranslate nohighlight">
\[\]</div>
 </p>
```
The generated xml by doxygen looks fine:
```xml
<briefdescription>
    <para>A class. </para>    
</briefdescription>
<detaileddescription>
    <para>A inline formula: <formula id="0">$ f(x) = a + b $</formula></para>
    <para>A display style formula: 
        <formula id="1">\[ \int_a^b f(x) dx = F(b) - F(a) \]</formula>
    </para>
</detaileddescription>
```

A minimal example is as follows:
`cat Source/mathhelper.h`:
```cpp
/**
 * @brief A class
 *
 * A inline formula: \f$ f(x) = a + b \f$
 *
 * A display style formula:
 * @f[
 * \int_a^b f(x) dx = F(b) - F(a)
 * @f]
 */
class MathHelper
{
public:
  MathHelper() {}
  ~MathHelper() {}
}
```

`cat Doxyfile`:
```
PROJECT_NAME           = "latexmath"
GENERATE_HTML          = NO
GENERATE_LATEX         = NO
GENERATE_XML           = YES
INPUT                  = "Source"
OUTPUT_DIRECTORY       = "doxygen"
```

`cat conf.py`:
```python
project = 'Test Latex Math'
extensions = ['breathe', 'sphinx.ext.mathjax']
breathe_projects = {  "latexmath": "doxygen/xml/" }
```

`cat index.rst`:
```rst
.. cpp:namespace:: @ex_latexmath

.. doxygenclass:: MathHelper
   :project: latexmath
   :members:
   :undoc-members:
```

Run it with:
```bash
doxygen Doxyfile
sphinx-build -b html . sphinx_html
```

**Comment by vermeeren** [comment]
From https://github.com/michaeljones/breathe/blob/master/documentation/source/latexmath.rst:

> Breathe uses a internal reStructuredText node provided by sphinx.ext.mathbase which is then picked up and rendered by the extension chosen in the conf.py.

Sphinx mathbase has been moved to core, which caused warnings, see #451. This was then fixed by PR #469. This PR is small, but it can be noted `math_nodes` has been removed and the RST node has been changed to `math_block()`.

The chance is high this is a bug on Breathe's side not passing things correctly to Sphinx or an extension. If you have some time could you try to experiment a bit based upon the diff in #469? Not sure how to fix this myself.

**Comment by maximiliank** [comment]
Thank you for pointing out where to look.

**Comment by vermeeren** [comment]
Just uploaded v4.16.0 containing the fix, thanks again.
