### ISSUE TITLE
Link from function to enum is missing when the enum is inside a group

### ISSUE THREAD

**Issue by eldadr** [michaeljones/breathe#507]
Assume the following header file:

```c++
/** @defgroup my_group This is a group
 *  @{
 */

/** My enum */
typedef enum {
    SUCCESS = 0, 
    ERROR = 1, 
} my_enum_t;

typedef struct {
    int x;
} my_struct_t;

/** @} */

/** My function */
my_enum_t my_function(my_struct_t data);
```

And the following RST code:

```rst
.. doxygengroup:: my_group
   :project: example_project
   :members:
   :undoc-members:

.. doxygenfunction:: my_function
    :project: example_project
```

When looking at the generated HTML, a link from the function definition to the struct definition is created, but a link to the enum definition is not created:

![breathe](https://user-images.githubusercontent.com/30600380/79635956-eb30e780-817c-11ea-97a9-c3ae78f6ba15.png)

(BTW, without the `members` and `undoc-members` options, both links are missing.)

Doxygen version 1.8.11
Python version 3.5.2

docutils==0.16
Sphinx==3.0.1
breathe==4.15.0

**Comment by vermeeren** [comment]
Breathe v4.16.0 was just released containing the fix you provided.

**Comment by eldadr** [comment]
Thanks!
