### ISSUE TITLE
Invalid token error on doxygen generated XMLs

### ISSUE THREAD

**Issue by Patrick5088** [michaeljones/breathe#510]
Breathe doesn't seem to parse german letters such as umlaut u in the xmls generated by doxygen.I bet that it is an error caused by encoding ,but i don't know how to fix it or where to fix it.What should I configure.

**Comment by Patrick5088** [comment]
Solved

**Comment by vermeeren** [comment]
You might want to post how you solved it in case anyone else encounters this issue. Perhaps locale wasn't set to something unicode or similar?

**Comment by Patrick5088** [comment]
The error is not from Breathe. The error comes from the fact that Doxygen outputs XML files encoded in ANSI (even though INPUT_ENCODING and DOXYFILE_ENCODING are set to UTF-8 ).I verified the encoding of the xml in Notepad++ ,converted the xml file from ANSI to UTF-8 ,than it worked (until parsing the next xml file that was encoded in ANSI).
The issues was finally solved by manually converting all the xml files generated by Doxygen to UTF-8.I used Powershell commands:

`Set-Variable -Name "DIR" -Value "My Doxygen Xml Directory"
Set-Variable -Name "DIR2" -Value "My Output Directoy"
foreach($i in ls -name $DIR/*.xml) { get-content $DIR/$i | out-file -encoding utf8 -filepath $DIR2/$i }`

**Comment by vermeeren** [comment]
Thanks for posting the details.

At least on GNU/Linux this works without any encoding hacks or Doxygen encoding settings out of the box, with a system locale that is UTF-8. I would guess this is either a Doxygen Windows-specific bug or a result of the Windows locale somehow not being an unicode variant, though I don't know much about Windows locales.
