### ISSUE TITLE
Enum itens are not referenced

### ISSUE THREAD

**Issue by colombojrj** [michaeljones/breathe#515]
Hello,

I can not reference my enum class items using any of these:

- :cpp:any:
- :cpp:class:
- :cpp:struct:
- :cpp:func:
- :cpp:member:
- :cpp:var:
- :cpp:type:
- :cpp:concept:
- :cpp:enum:
- :cpp:enumerator:

It is worth noting I can reference the enum itself. What should I do?

**Comment by jakobandersen** [comment]
Either ``:cpp:any: `` or ``:cpp:enumerator:`` role should be the right one to use (assuming it's a C++ declaration). Do you have an example of where it is not working?

**Comment by vermeeren** [comment]
Assuming this is fixed.
