### ISSUE TITLE
friend struct not handled since 4.17

### ISSUE THREAD

**Issue by msimberg** [michaeljones/breathe#521]
We have code which uses `friend struct x;` (note: not `friend class`). Breathe does not like this since 4.17.0 because of https://github.com/michaeljones/breathe/commit/fa6df5ae8d83eb6fed51f1456ca94919eb3fa7b2, with the assertion here failing: https://github.com/michaeljones/breathe/blob/fa6df5ae8d83eb6fed51f1456ca94919eb3fa7b2/breathe/renderer/sphinxrenderer.py#L1519. I tried both 4.16.0 which still works, and 4.18.0 by changing `friend struct` to `friend class` which also works.

**Comment by vermeeren** [comment]
Probably a function should be added among the lines of `visit_friendstruct`, which would be rather similar to `visit_friendclass`. And then just call that one if we are dealing with a struct. I probably won't have time to properly handle this myself anytime soon though.

**Comment by vermeeren** [comment]
Released fix in v4.18.1, should be resolved now.

@msimberg Can you confirm?

**Comment by msimberg** [comment]
Really sorry about the silence here. The error is indeed gone, thank you! There is a new error which all the way to 4.22.0 (still leaving 4.16.0 as the last working version for us), which I'm quite sure is unrelated but I'll post it here just in case: https://gist.github.com/msimberg/2c55a1bfffedd5d05d11cb533069d4d1. I have not yet dug into what exactly is triggering it. Does that look familiar? I'll do some digging and open another issue unless that looks immediately familiar to you.

**Comment by jakobandersen** [comment]
I looks like it could be https://github.com/sphinx-doc/sphinx/issues/7763, fixed in Sphinx 3.1.

**Comment by msimberg** [comment]
> I looks like it could be [sphinx-doc/sphinx#7763](https://github.com/sphinx-doc/sphinx/issues/7763), fixed in Sphinx 3.1.

Ah, thanks a lot for that pointer! Will give that a try and report back.

**Comment by msimberg** [comment]
@jakobandersen Again, that particular error is gone with 3.1.0 but there is more: https://gist.github.com/msimberg/00d99cbf0996ce41fe9a1030d06b4999. Again, if it doesn't look familar I'll look into what's triggering it and open a separate issue. I found a few older issues with a similar assertion firing, but they were all closed as fixed, so I assume this is new.

**Comment by jakobandersen** [comment]
Indeed, that particular assertion triggers once in a while, but it is basically always a symptom of something going wrong somewhere else. Do you have some example code that triggers the problem?

**Comment by msimberg** [comment]
> Indeed, that particular assertion triggers once in a while, but it is basically always a symptom of something going wrong somewhere else. Do you have some example code that triggers the problem?

Not yet, I'll do some digging :) Thanks!
