### ISSUE TITLE
Regression on 4.17 (and 4.18) with compound union

### ISSUE THREAD

**Issue by nveljkovic** [michaeljones/breathe#523]
For a compound type:
```C
union bdf {
        struct {
                uint32_t function :      3;
                uint32_t device   :      5;
                uint32_t bus      :      8;
                uint32_t domain   :     16;
        };
        uint32_t as_uint;
};
```
Doxygen reports additional value entry for anon. inner struct:
```xml
...
      <memberdef kind="variable" id="unionbdf_1abe9f874edd051b858b2240db86c98861" prot="public" static="no" mutable="no">
        <type>struct bdf::@0</type>
        <definition>struct bdf::@0 bdf::@1</definition>
        <argsstring></argsstring>
        <name>@1</name>
       ...
        <location file="dummy.h" line="7" column="1"/>
      </memberdef>
      <memberdef kind="variable" id="unionbdf_1a7388dd8b4156ae1a3c4f32f439484604" prot="public" static="no" mutable="no">
        <type>uint32_t</type>
        <definition>uint32_t bdf::as_uint</definition>
        <argsstring></argsstring>
        <name>as_uint</name>
        ...
        <location file="dummy.h" line="8" column="1" bodyfile="dummy.h" bodystart="8" bodyend="-1"/>
      </memberdef>
...
```

Since version 4.17, instead of ignoring it, Sphinx reports an error when parsing this anon value:
```
reading sources... [100%] index                                                                                                                                                                           
index.rst:7: WARNING: Error in declarator or parameters
Invalid C declaration: Expected identifier in nested name. [error at 10]
  struct bdf::@0 @1
  ----------^
```

It also generates it in the documentation:
union bdf
    Public Members
    uint32_t function
    uint32_t device
    uint32_t bus
    uint32_t domain
    *struct bdf::@0 @1*
    uint32_t as_uint

**Comment by nveljkovic** [comment]
If this is not trivial to fix, I am willing to spend some time on it, as I really like Breathe, but would appreciate a nudge in the right direction (where to look, which code could be at fault...).

**Comment by vermeeren** [comment]
Recent Breathe versions pass a lot more to Sphinx than they did previously. At a glance I suspect this edge case may currently simply not be supported yet in Sphinx's C domain, as that is where the error comes from. See https://github.com/sphinx-doc/sphinx/blob/3.x/sphinx/domains/c.py#L2451.

You could try experimenting a bit around this region to see what is going wrong. Breathe also obtained some debug tracing capabilities recently, though you have to enable them in the sources, see https://github.com/michaeljones/breathe/blob/master/breathe/renderer/sphinxrenderer.py#L17.

**Comment by jakobandersen** [comment]
Which version of Sphinx are you using?
When I tried your example it seems to work as good as it can from the Doxygen XML. The ``struct bdf::@0 @1`` definition gets rendered as ``struct bdf::[anonymous] [anonymous]`` which technically is correct.

**Comment by nveljkovic** [comment]
I can confirm that with newer version of Sphinx (v3.2.1) and Breathe (4.23.0) I do get `struct bdf::[anonymous] [anonymous]`. 
It's not ideal but it's a big improvement from `struct bdf::@0 @1`, so I am closing as fixed.
