### ISSUE TITLE
Error parsing XML files

### ISSUE THREAD

**Issue by LudovicGuerra** [michaeljones/breathe#542]
[drv__timer__bf_8c.txt](https://github.com/michaeljones/breathe/files/4765056/drv__timer__bf_8c.txt)

Hi all.
I generated a XML file of my project with Doxygen.
But when I launch sphinx, i got this error:

> Exception occurred:
>   File "c:\users\ludovic.XXX\appdata\local\programs\python\python38\lib\site-packages\breathe\parser\__init__.py", line 81, in parse
>     raise ParserError(e, filename)
> breathe.parser.ParserError: file C:\Users\ludovic.XXX\Desktop\Code\f1\doc\internal/ula/doxygen/xml\drv__timer__bf_8c.xml: not well-formed (invalid token): line 650, column 102
> The full traceback has been saved in C:\cygwin64\tmp
> [sphinx-err-5qz6_dtg.log](https://github.com/michaeljones/breathe/files/4765038/sphinx-err-5qz6_dtg.log)
> \sphinx-err-5qz6_dtg.log, if you want to report the issue to the developers.

Attached the log file

I am with sphinx 3.1.0
Windows 10 64 bits
Breathe 4.19.1
Python 3.8.3 64 bits

Thank you !

**Comment by vermeeren** [comment]
@LudovicGuerra Can you upload the XML file that is not well-formed? I doubt this is a Breathe issue.

**Comment by LudovicGuerra** [comment]
@vermeeren I did but in TXT cause the XML file is not supported

**Comment by vermeeren** [comment]
@LudovicGuerra My bad. The character it complains about is `µ`. I suspect your system's locale is not set to something UTF-8 and/or Unicode. I will do a quick little test on my machine, give me a few minutes.

**Comment by vermeeren** [comment]
Works fine here with `µ` character spammed in few places in a random function's Doxygen description and argument descriptions. Can you check your locale?

**Comment by LudovicGuerra** [comment]
Cygwin (where i launch all my script) give me this:

> LANG=fr_FR.UTF-8
> LC_CTYPE="fr_FR.UTF-8"
> LC_NUMERIC="fr_FR.UTF-8"
> LC_TIME="fr_FR.UTF-8"
> LC_COLLATE="fr_FR.UTF-8"
> LC_MONETARY="fr_FR.UTF-8"
> LC_MESSAGES="fr_FR.UTF-8"
> LC_ALL=

**Comment by vermeeren** [comment]
Yeah on a second look opening the file in `vim` indeed shows `latin1` as the character set, so as you say character encoding is likely the problem here.

**Comment by LudovicGuerra** [comment]
Do you think adding more encoding to breathe would be a good idea ?

**Comment by vermeeren** [comment]
I think it is up to the environment to have correct locale and/or file encoding settings, many utilities expect these to be set correctly. Breathe overriding the environment will likely cause many issues for users that use non-standard locale's and/or encodings.

You would probably encounter similar issues in many CLI tools and of course Python with the `fr_FR.cp1252` locale when special symbols are used, just happened Breathe was first to explode this time.

Thank you too for the proper report and all the details, cheers.

**Comment by lSabrinel** [comment]
Hello @LudovicGuerra, I faced the same issue. Could you please explain how did you fix it. Thank you.
