### ISSUE TITLE
Breathe parsing XML slow

### ISSUE THREAD

**Issue by LudovicGuerra** [michaeljones/breathe#544]
Hi guys.
After some test and trying to launch  Breathe for my full project, it is not possible to use it.
With doxygen I have 6500 XML file generated, and it takes way too much time to analyse for Breathe all of this, the build take longer than 10 min.
Except if you have any advice to reduce it to 10 sec, I'm gonna have to abandon the idea of Breathe.
Thank you for your support

**Comment by vermeeren** [comment]
I believe this is very similar, if not the same, as #439 and possibly #315. In short it appears that replacing minidom with lxml should net significant performance gain.

As always patches are very welcome, I don't have the time to actively develop Breathe at this point in time (I only maintain it, in a rather minimal sense unfortunately).

**Comment by LudovicGuerra** [comment]
Well yes it corresponds to othhers reports. We made the decision to not use Breathe. Thank you for your time and kind help, hope the best to this repository.

**Comment by AnthonyDiGirolamo** [comment]
If anyone is still interested in lxml I started a PR for it https://github.com/breathe-doc/breathe/pull/891 It's not complete but unit tests are passing.
