### ISSUE TITLE
:no-link: doesn't seem to work in my project

### ISSUE THREAD

**Issue by Shamino0** [michaeljones/breathe#549]
I haven't been able to reproduce this in a small project, so please bear with me and let me know of any tests I can run to help you diagnose this problem.

I'm developing a pretty large document set (documenting an SDK), consisting of 221 rst files.  Breathe is processing Doxygen output generated from 104 header files.

Each header file's Doxygen generates a page of the API reference using a per-header rst file of the form:

    header_name.h
    =============

    High-level description of the header

    Usage
    =====

    .. code-block:: c

       #include <header_name.h>

    Contents
    --------

    .. doxygenfile:: header_name.h
       :project: PROJECTNAME

In various other (non-reference-manual) pages, I include links to the Doxygen-generated symbols using standard Sphinx markup of the form:

    :c:func:`funcname`

These seem to work OK.  But if I decide to include a copy of the function in one of those pages, using Breathe directives of the form:

    .. doxygenfunction:: funcname
       :project: PROJECTNAME
       :outline:
       :no-link:

Then links to the function end up pointing to the page where the "doxygenfunction" directive was used, even though I'm using the no-link option.  There is no anchor on the page for the link, but the generated links end up pointing there anyway.  And the anchor on the reference manual page goes away for the function.

I'm attaching a text file showing the diffs in the generated output with and without the "doxygenfunction" directive.  The files in the "working_output" directory don't use it and generate links as they should, while the files in the "broken_output" directory do use it and generate incorrect links.

The diffs for books/guide/concepts/event.html is a non-reference-manual page where I'm including (broken_output) or not including (working_output) a doxygenfunction directive for the function "jsom_event_queue_create".

The diffs for books/guide/event.html is another non-reference manual page that simply links to the function.

The diffs for reference/misc/jsom_event.html is the reference-manual page generated from a single header's Doxygen output.

[diff.txt](https://github.com/michaeljones/breathe/files/4838917/diff.txt)

As I wrote at the top of this message, I tried to reproduce this problem with a small example (one C header with two structs and two functions) but I could not reproduce the problem with it.  All the links worked as expected in that example.

I understand that the diffs I present may not be enough to diagnose the problem.  Feel free to suggest tests for me to run, or contact me off-line if you like.  I won't be able to send you my project source files, but maybe we can figure out enough so I can produce a test case that I can send you.

**Comment by jakobandersen** [comment]
I believe this is a 'problem' in Sphinx and not Breathe. The ``no-link`` option is translated by Breathe into the ``noindex`` option in Sphinx. However, ``noindex`` has not been fully working in the C and C++ domains previously, and it seems that through various changes the option is now completely ignored.
It it rather tricky to implement correctly due to the need for making cross-references inside signatures, which requires some kind of reference to existing symbols.

In the C++ domain there is an alias directive which can be used insert a copy of a declarations. Sphinx 3.2 will have a similar directive for C. With that you could simply write
```rst
.. c:alias:: funcname
```
instead of the ``doxygenfunction`` directive with ``no-link``.

**Comment by Shamino0** [comment]
Thanks much for a quick response.

What will be the future of Breathe?  Will no-link be changed to use aliases?  Or should I directly put aliases in my document?

For now, I've commented-off the no-link blocks in my documentation in order to avoid breaking the HTML output.  I'll go back and fix it up when Sphinx 3.2 is released.

**Comment by jakobandersen** [comment]
> What will be the future of Breathe? Will no-link be changed to use aliases? Or should I directly put aliases in my document?

I don't think there is anything to process on the Breathe-side, so I suggest writing the alias directives directly.
