### ISSUE TITLE
Enum rendering broken after update

### ISSUE THREAD

**Issue by gavv** [michaeljones/breathe#554]
Hi, thanks for this great project! I'm using it to create API reference and am happy with it.

Sorry if it's a duplicate, but I didn't find similar issue.

Recently my system upgraded to breathe 4.14.1 and sphinx 2.4.4, and enum values are now rendered with their numerical values instead of names.

Before:

![image](https://user-images.githubusercontent.com/8436629/86906653-8900d680-c11c-11ea-8ec3-105e4a0b046a.png)

After:

![image](https://user-images.githubusercontent.com/8436629/86906747-aa61c280-c11c-11ea-8f37-130ae55abcde.png)

(And also "enum" word disappeared, which is not cool too.)

The source code and sphinx code didn't change:

```
/** Forward Error Correction code. */
typedef enum roc_fec_code {
    /** No FEC code.
     * Compatible with \ref ROC_PROTO_RTP protocol.
     */
    ROC_FEC_DISABLE = -1,

    /** Default FEC code.
     * Current default is \ref ROC_FEC_RS8M.
     */
    ROC_FEC_DEFAULT = 0,

    /** Reed-Solomon FEC code (RFC 6865) with m=8.
     * Good for small block sizes (below 256 packets).
     * Compatible with \ref ROC_PROTO_RTP_RS8M_SOURCE and \ref ROC_PROTO_RS8M_REPAIR
     * protocols for source and repair endpoints.
     */
    ROC_FEC_RS8M = 1,

    /** LDPC-Staircase FEC code (RFC 6816).
     * Good for large block sizes (above 1024 packets).
     * Compatible with \ref ROC_PROTO_RTP_LDPC_SOURCE and \ref ROC_PROTO_LDPC_REPAIR
     * protocols for source and repair endpoints.
     */
    ROC_FEC_LDPC_STAIRCASE = 2
} roc_fec_code;
```

```
.. doxygentypedef:: roc_fec_code
   :outline:

.. doxygenenum:: roc_fec_code
```

The typedef stuff doesn't matter. If I remove typedef from source and sphinx, nothing changes.

Links:

* https://github.com/roc-streaming/roc-toolkit/blob/86c78426818cc9275a1c030314f833ea964f2651/src/library/include/roc/config.h#L176-L201
* https://raw.githubusercontent.com/roc-streaming/roc-toolkit/develop/docs/sphinx/api/reference.rst

This problem affects all enums. All of them are now rendered without names.

Let me know if I can provide more information or make some tests.

**Comment by gavv** [comment]
Also, note that even numeric rendering is not quite correct: the first value renders as "1", but the real value is "-1".

**Comment by vermeeren** [comment]
Can you try with latest Breathe 4.19.2 and a recent Sphinx? At least 3.0 but if possibly latest 3.1.2. There were some regressions in previous versions that should already be fixed in newer versions, especially with Sphinx having a vastly improved C and C++ domain in version 3.

**Comment by gavv** [comment]
Thanks, it is fixed on breathe 4.19.2 + sphinx 3.1.2:

![image](https://user-images.githubusercontent.com/8436629/86932128-9da39580-c141-11ea-9712-579efdd27843.png)

BTW, these new `enumerator` prefixes are a bit annoying when there are many enum values.

**Comment by jakobandersen** [comment]
> BTW, these new `enumerator` prefixes are a bit annoying when there are many enum values.

This is something Sphinx makes. If one documents an enumerator independently of the enum they make a bit more sense, e.g.,
```rst
... enum:: roc_fec_code

   some documentation

some other documentation

.. enumerator:: roc_fec_code.ROC_FEC_DISABLE = -1

   the enumerator documentation
```
In your context, which is probably the most common, they can indeed be a bit distracting in high quantities.
How about adding a directive option to enums on whether nested enumerators have the prefix?

**Comment by gavv** [comment]
> How about adding a directive option to enums on whether nested enumerators have the prefix?

Yep, I'd use it!

Thought, if the prefix returned by sphinx is always the same for enum values, maybe it makes sense to hide it unconditionally, since it doesn't add any information... If different prefixes are possible, an option makes more sense.

**Comment by gavv** [comment]
Though someone may prefer to have the prefix for consistency with standalone enumerators, if they use both, so maybe an option is a better idea.
