### ISSUE TITLE
Doxygen inner groups are not supported

### ISSUE THREAD

**Issue by utzig** [michaeljones/breathe#555]
In Doxygen inner groups can be created by adding groups inside groups, or by using the \ingroup keyword. A few examples to clarify the possibilities:

```
/** @defgroup groupA
 *  @ingroup nonDeclaredGroup
 * {
  ...
```

This generates a new group `groupA` but unless a `\defgroup nonDeclaredGroup` is added somewhere it has no effect it is not added to any group. The only reason for this example is to state this "weird" behavior. No warning are generated.

Examples of how it works (in Doxygen):

```
/** @defgroup groupA
  * @{
  */

/* Some code... */

/** @defgroup groupB
  * @{
  */

/* Some more code... */

/**
 * @}   <- this closes groupB
 */

/* Even more code... */

/**
 * @}   <- this closes groupA
 */
```

In this example inside the `groupA` XML there will be an `innergroup` element with a reference to `groupB`, because `groupB` is inside `groupA` by scope.

```
/** @defgroup groupA
  * @{
  */

/* Some code... */

/**
 * @}   <- this closes groupA
 */

/** @defgroup groupB
 *  @ingroup groupA
  * @{
  */

/* Some more code */

/**
 * @}   <- this closes groupB
 */
```

In this example inside the `groupA` XML there will be an `innergroup` element with a reference to `groupB`, because `groupB` is has an `@ingroup` command.

In those examples the inner groups are currently not automatically "loaded" by breathe, and any references to them is unresolved unless there is a explicity directive adding them, eg, `.. doxygengroup:: groupB` added in a rST filie.

**Comment by vermeeren** [comment]
Version 4.20.0 was just released, adding support for innergroups.
