### ISSUE TITLE
Performance issues in C domain after scoped rendering changes

### ISSUE THREAD

**Issue by utzig** [michaeljones/breathe#559]
While working on upgrading Sphinx/breathe versions for building Zephyr's docs (https://docs.zephyrproject.org/latest/) I found out some real slow-downs when running builds on C domain with newer versions. Those docs are currently built with `Sphinx==2.4.4` and `breathe==4.14.2`, and I am trying to switch to `Sphinx==3.0.4` (or newer) and `breathe==4.19.2`.

Currently there is no `breathe_domain_by_extension`, which means it uses the CPP domain. Here are the numbers:

1) `sphinx==2.4.4` / `breathe==4.14.2`
make html  753.11s user 10.48s system 99% cpu 12:47.00 total

2) `sphinx==3.0.4` / `breathe==4.19.2`
make html  809.96s user 10.10s system 99% cpu 13:45.28 total

Which is not too bad, but if I add a `breathe_domain_by_extension = {"h": "c", "c": "c"}` config I now get this numbers:

1) `sphinx==2.4.4` / `breathe==4.14.2`
make html  682.54s user 11.16s system 99% cpu 11:39.24 total

2) `sphinx==3.0.4` / `breathe==4.19.2`
make html  1389.20s user 7.88s system 99% cpu 23:20.49 total

Going from 682s to 1389s seems a bit excessive. Running with cProfile I see the slowdowns result from calls to `CObject._add_enumerator_to_parent()` -> `ASTBaseBase.clone()` -> `deepcopy()`. Not sure this is helpful or correct, and I wonder why `deepcopy()` calls would slow everything down. The specific commit where the issue starts to happen is this one: https://github.com/michaeljones/breathe/pull/512/commits/a2a1085e24022aececd2b93b46ade684f59d6ec0

**Comment by jakobandersen** [comment]
Is it possible that you can post (a link to) the full cProfile output and/or detailed instructions to replicate the benchmark locally?

**Comment by utzig** [comment]
> Is it possible that you can post (a link to) the full cProfile output and/or detailed instructions to replicate the benchmark locally?

I modified `sphinx-build` to read like this:

```
#!/home/utzig/.pyenv/versions/3.7.4/bin/python3.7
# -*- coding: utf-8 -*-
import re
import sys
from sphinx.cmd.build import main
import cProfile
if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])
    pr = cProfile.Profile()
    pr.enable()
    rc = main()
    pr.disable()
    pr.dump_stats('out.profile')
    sys.exit(rc)
```

I uploaded the output of building the Zephyr documentation with `Sphinx==3.0.4` / `breathe==4.19.2` / `doxygen==1.8.18` here: https://paste.c-net.org/MoistThrown. As I've never used this bin paste service before, I'm leaving a sha256sum just in case: `9a19254821ce6721440ed6fb313b96ff8ace6d883f192b1844a9680bc337857d`!

**Comment by jakobandersen** [comment]
sphinx-doc/sphinx#7960, should fix this. I looks basically all C domain data got copied every time an enumerator was encountered. Locally I got ~2200s on branch 3.1.x and ~890s on the PR based on the profile dumps. @utzig, can you confirm that the PR fixes the problem?

**Comment by utzig** [comment]
> [sphinx-doc/sphinx#7960](https://github.com/sphinx-doc/sphinx/pull/7960), should fix this. I looks basically all C domain data got copied every time an enumerator was encountered. Locally I got ~2200s on branch 3.1.x and ~890s on the PR based on the profile dumps. @utzig, can you confirm that the PR fixes the problem?

Yes, that was awesome @jakobandersen. On the branch I am currently working on:

sphinx==3.1.2 / breathe==4.19.2
make html  1518.26s user 10.07s system 99% cpu 25:36.34 total

sphinx==3.1.3.dev20200714 / breathe==4.19.2
make html  709.51s user 8.19s system 99% cpu 12:00.10 total

Where this last Sphinx version is built from your PR, and there were no changes in the final output html! :+1:

**Comment by jakobandersen** [comment]
Great! I will be in either v3.1.3 or v3.2.
