### ISSUE TITLE
breathe_projects_source source path (windows version) is not parsed correctly

### ISSUE THREAD

**Issue by Patrick5088** [michaeljones/breathe#562]
I am trying to use **autodoxygenindex** directive. The problem occurs when the source path contains empty spaces. For example, if the path for **breathe_projects_source** in **conf.py** is "**C:\Users\User\Document\Example 1\Subdirectory Example 1**", then after executing "_**make html**_", in command prompt, the output will be:
warning: tag INPUT: input source 'C:\Users\User\Document\Example' does not exist
warning: tag INPUT: input source '1\Subdirectory' does not exist
warning: tag INPUT: input source 'Example' does not exist
warning: tag INPUT: input source '1' does not exist

No source code files will be found because of that. I tried using **r'C:\Users\User\Document\Example 1\Subdirectory Example 1'** and **r"C:\Users\User\Document\Example 1\Subdirectory Example 1"** for formating. This type of path formatting worked for **breathe_projects** directive, after generating the xml using doxygen, because I used  **r'C:\Users\User\Document\Example 1\Subdirectory XML Source'** for the path of the xml source.

**Comment by vermeeren** [comment]
Recently there was another bug reported with spaces in paths (on a *NIX OS though), see #478. I am not sure if this is a bug in breathe at this point or something related to the environment, I would say the latter has a higher chance.

@Patrick5088 Can you post full configuration snippet of the `breathe_projects_source` option, formatted in a literal block as is typical? And/or perhaps provide additional steps to reproduce?

As I don't do any development on Windows I don't think I can help further though.

**Comment by vermeeren** [comment]
Assuming fixed.
