### ISSUE TITLE
Release breathe compatible with Sphinx>=3.2

### ISSUE THREAD

**Issue by utzig** [michaeljones/breathe#565]
Breathe was made compatible with Sphinx >3.2 with commit: https://github.com/michaeljones/breathe/commit/8d07f406105c8196ac01519c770dd87c09d54465. This still requires publishing a new version of Breathe; there were so far two Sphinx releases on the 3.2 lineage.

**Comment by vermeeren** [comment]
Just released v4.20.0 containing the fix, see dd4ff4e4f30640e231eb4cea0d8c2f659e3266b4. Thanks for the issue!
