### ISSUE TITLE
doxygenclass for a template specialization not found

### ISSUE THREAD

**Issue by cary-ilm** [michaeljones/breathe#569]
I'm trying to reference a C++ template specialization in a doxygenclass directive:

    /// Foo<T>
    template <class T> class Foo
    {
      public:
        Foo() {}
    };

    /// Foo<std::vector<T>>
    template <class T> class Foo<std::vector<T>>
    {
      public:
       Foo() {}

        /// bar
        void bar();
    };

In rst, this works fine:

    .. doxygenclass:: Foo

but is there syntax to reference the Foo<std::vector<T>> specialization? No incarnation like this seems to work:

    .. doxygenclass: Foo<std::vector>

    .. doxygenclass:: Foo<std::vector<T>>

This gives: WARNING: doxygenclass: Cannot find class "Foo<std::vector<T>>" in doxygen xml output"

Is this supported? What is the syntax? Thanks for any guidance.

[foo.tar.gz](https://github.com/michaeljones/breathe/files/5133348/foo.tar.gz)

**Comment by utzig** [comment]
You have to use: `.. doxygenclass:: Foo< std::vector< T > >` (correct spacing here is important!)

**Comment by vermeeren** [comment]
On a side note, issue itself seems a lot like #442. Based upon the above by @utzig I think it's safe to resolve that one too if this is confirmed to be ok by @cary-ilm .

**Comment by cary-ilm** [comment]
That works like a charm, with the proper spacing inside the <>, it correctly processes the class. Thanks for the speedy response! I submitted #570 to add a note to the documentation about the spacing requirements.
