### ISSUE TITLE
How to display description of doxygenclass

### ISSUE THREAD

**Issue by steffenroeber** [michaeljones/breathe#575]
Hi, is there any way to get something like doxygenfile:: :sections: in a doxygen class?
What I need is to print only the description of a class without any further things.
Unfortunately doxygenfile:: also doesn't work, because it prints all classes of a file if there are more than one.
Or can I filter a specific class with doxygenfile::??

Best reagards

**Comment by vermeeren** [comment]
@steffenroeber  The `:sections:` was only added rather recently in #501 and indeed only for `doxygenfile` directive. I don't think there is a way to do what you want currently with something like `:sections:`.

Can you post the RST in use? I believe the default is to only display the class description itself unless `:members:` option is passed. https://breathe.readthedocs.io/en/latest/class.html#basic-example

**Comment by steffenroeber** [comment]
Ok. Thank you.
