### ISSUE TITLE
How to link in doxygen generated docu

### ISSUE THREAD

**Issue by steffenroeber** [michaeljones/breathe#577]
Hi,
I found that breathe creates/uses links within the doxygen generated xml files. But only partly. For example, function parameter types have working links to other elements.
I I use 
```
.. doxygenclass:: cipp::cCornerHarrisFunctor
   :members:
```
in one .rst and
```
************
harrisCorner
************

Registerd Name: ipp/image/computerVision/harrisCorner

.. doxygenclass:: cipp::cHarrisCornerStation

```
in another .rst: Then, links from cHarrisCornerStation to cCornerHarrisFunctor (in brief description part) are not resolved. Is this by design ow how I can I solve that? Doxygen resolved it properly in .xml.

Best regards

**Comment by vermeeren** [comment]
@steffenroeber Can you check if #566 applies to your project? Do you have have `SEPARATE_MEMBER_PAGES` set in Doxygen config?

**Comment by steffenroeber** [comment]
Hi, no SEPARATE_MEMBER_PAGES is set no 'NO'.
The entry is my .xml is following:
```
<para>This station serves as a wrapper around <ref refid="classcipp_1_1c_corner_harris_functor" kindref="compound">cipp::cCornerHarrisFunctor</ref>. </para>
    </briefdescription>
    <detaileddescription>
<para><bold>Parameters</bold><itemizedlist>
<listitem><para>threshold: This value serves as a filter for output corners. Only pixel values &gt; this values are sent. Default is 0.5. </para>
</listitem></itemizedlist>
</para>

```

The generated html looks like:
```
    This station serves as a wrapper around cipp::cCornerHarrisFunctor.

    Parameters

        threshold: This value serves as a filter for output corners. Only pixel values > this values are sent. Default is 0.5.

```
I' sure fully sure but I would expect cipp::cCornerHarrisFunctor is a link, right?

**Comment by steffenroeber** [comment]
Seems to be solved. Don't know exactly. But now it works. Thanx for help.

**Comment by vermeeren** [comment]
@steffenroeber Maybe something was wrong with caching, sometimes deleting doc build dir or using sphinx `-E` to avoid cache can help. Thanks for letting me know.
