### ISSUE TITLE
breathe_show_enumvalue_initializer

### ISSUE THREAD

**Issue by yamt** [michaeljones/breathe#578]
i want to use something like breathe_show_define_initializer, but for enum values.
the following patch is just to demonstrate what i want to use.
if it's acceptable, i can submit a patch to implement the configuration knob.

    --- sphinxrenderer.py.bak	2020-09-15 11:22:58.000000000 +0900
    +++ sphinxrenderer.py	2020-09-15 11:23:33.000000000 +0900
    @@ -1447,7 +1447,8 @@ class SphinxRenderer:
            return self.handle_declaration(node, declaration, content_callback=content)
    
        def visit_enumvalue(self, node) -> List[Node]:
    -        declaration = node.name + self.make_initializer(node)
    +        #declaration = node.name + self.make_initializer(node)
    +        declaration = node.name
            return self.handle_declaration(node, declaration, obj_type='enumvalue')
    
        def visit_typedef(self, node) -> List[Node]:

**Comment by vermeeren** [comment]
@yamt Good idea, it's definitely ok to add a feature like this! I am actually thinking we should default it to `False` too, just like `breathe_show_define_initializer`, so values are hidden by default. If you can submit patch I will check asap, thanks!
