### ISSUE TITLE
The contents of the \deprecated tag do not appear in output

### ISSUE THREAD

**Issue by JamesRandom** [michaeljones/breathe#579]
The annotation appears in the XML and doxygen-generated HTML for the function, bit not in the sphinx output generated by breathe.

**Comment by utzig** [comment]
This was implemented by #596. To import the deprecated.xml (generated from `\deprecated` commands) just use ``.. doxygenpage:: deprecated``. More documentation: https://breathe.readthedocs.io/en/latest/directives.html#doxygenpage
