### ISSUE TITLE
Unknown directive type "doxygenindex"

### ISSUE THREAD

**Issue by duncanrhamill** [michaeljones/breathe#586]
Hi, I've just started using sphinx and breathe and I'm running into a directive issue that's bugging me.

As far as I can tell I've registered breathe with sphinx, but none of the breathe directives are working.

`conf.py`:
```python
import sys
import breathe
sys.path.append(breathe.__path__[0])

# ...

extensions = [
    'breathe'
]

# ...

# Breathe project path
breathe_projects = { 'my_project': '../../doxygen/xml' }

# Default breathe project
breathe_default_project = "my_project"
```

`index.rst`:
```rst
My Project Documentation
===============================

.. toctree::
   :maxdepth: 2
   :caption: Contents:

.. doxygenindex::

Demos
=====

.. doxygenfile:: demo/demo_cmake_test.c
.. doxygenfunction:: main


Indices and tables
==================

* :ref:`genindex`
* :ref:`modindex`
* :ref:`search`

```

sphinx `make html` output:
```shell
Running Sphinx v3.2.1
making output directory... done
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 1 source files that are out of date
updating environment: [new config] 1 added, 0 changed, 0 removed
reading sources... [100%] index
<MY_PROJECT>/docs/sphinx/source/index.rst:13: WARNING: Unknown directive type "doxygenindex".

.. doxygenindex::

<MY_PROJECT>/docs/sphinx/source/index.rst:20: WARNING: Unknown directive type "doxygenfile".

.. doxygenfile:: demo/demo_cmake_test.c

<MY_PROJECT>/docs/sphinx/source/index.rst:21: WARNING: Unknown directive type "doxygenfunction".

.. doxygenfunction:: main
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... done
writing output... [100%] index
generating indices...  genindexdone
writing additional pages...  searchdone
copying static files... ... done
copying extra files... done
dumping search index in English (code: en)... done
dumping object inventory... done
build succeeded, 3 warnings.

The HTML pages are in build/html.
```

I installed breathe using `pip install breathe`, and am using doxygen 1.8.17. Any help would be appreciated!

**Comment by vermeeren** [comment]
@duncanrhamill Can you clone the breathe repo and run `make html`? This should dump documentation into `documentation/build/html`. (You may get quite some warnings doing the build, that is normal.)

If that doesn't work, there is likely something wrong with your Python environment/setup. Perhaps check your `PYTHONPATH` or similar. For local pip installations without root (which is recommended) `PYTHONPATH` is usually something like `/home/user/.local/lib/python3.7/site-packages`.

**Comment by duncanrhamill** [comment]
Ok so I cloned breathe and built the docs, no problems. I can serve and view them and nothing seems different from the online docs, no "unknown directive type" errors or warnings either.

I did check my `PYTHONPATH`, it wasn't set but after setting it and trying again I'm having the same problems.

**Comment by vermeeren** [comment]
@duncanrhamill Try removing/commenting all of these in your `conf.py`:

```
import sys
import breathe
sys.path.append(breathe.__path__[0])
```

On a typical setup you only need to add `breathe` to the `extensions` array, as long as your paths etc are all correct. If you still have trouble try to verify that Sphinx is actually using your `conf.py` and not something else. It seems like Breathe is not loaded at all currently.

**Comment by duncanrhamill** [comment]
No luck, removed them and added a print statement to check that `conf.py` is actually being used, and looks like it is.

I made sphinx more verbose and couldn't see any mention of breathe in the log output, I'm not certain if this is expected but it seems odd to me.

**Comment by vermeeren** [comment]
@duncanrhamill That's rather confusing then, are you able to share the sources in question? All I can think of at this point is diffing the config files (`vimdiff` or whatever) or perhaps running it with `strace` to see if Breathe's files are being opened at all during the build.

**Comment by vermeeren** [comment]
No reply, assuming fixed.
