### ISSUE TITLE
Separate member function

### ISSUE THREAD

**Issue by steffenroeber** [michaeljones/breathe#588]
Hi,
is there any way to separate member functions of .. doxygenclass::?
Currently all member functions are rendered without any separation.
I'd like to have something like: https://doc.qt.io/qt-5.9/qcolor.html#setNamedColor
Where a line separates the functions.

Best regards Steffen

**Comment by vermeeren** [comment]
@steffenroeber I think you can fix this in the Sphinx theme used with some styling, which I think is also the best place to make such modifications.

**Comment by steffenroeber** [comment]
Thanx a lot. That works.
