### ISSUE TITLE
empty `kind` property causes multiple errors

### ISSUE THREAD

**Issue by psifertex** [michaeljones/breathe#592]
Version: Breathe 4.22.1

Doxygen can produce `sectiondefs` like:
```
<sectiondef kind="">
```
most notably I'm seeing it for https://github.com/Vector35/binaryninja-api/blob/dev/ui/flowgraphwidget.h#L283-L332

As shown in the attached xml on line `3280`
[breathe-repo.zip](https://github.com/michaeljones/breathe/files/5412362/breathe-repo.zip)

There's several places in the code where this falls over. In the meantime, I'm working around it with a regular expression to replace `""` with `"none"` as I saw somewhere that breathe can handle custom kind values, just assumes that there is /some/ value there or else you get a property error. Not sure if this can be fixed generically in the XML parsing such that the property is created with an empty string, but that seems the easiest fix.

**Comment by psifertex** [comment]
This might be a doxygen bug? I think the sections should actually be: 
`<sectiondef kind="signal">`
and
`<sectiondef kind="slot">`

However, it looks like slots are missing from: https://github.com/michaeljones/breathe/blob/0bc9ba73723cb5c1f626c94962a55c56919592da/breathe/renderer/sphinxrenderer.py#L1099

Would a PR be acceptable to add it?

**Comment by utzig** [comment]
> However, it looks like slots are missing from:
> 
https://github.com/michaeljones/breathe/blob/0bc9ba73723cb5c1f626c94962a55c56919592da/breathe/renderer/sphinxrenderer.py#L1099
> 
> Would a PR be acceptable to add it?

There are `public-slots`, `protected-slots` and `private-slots` all are properly declared in `sections`.

**Comment by psifertex** [comment]
Thanks. Yeah, that works for a workaround. I'm still trying to figure out why my particular doxygen setup created the empty kind in the section.

**Comment by vermeeren** [comment]
@psifertex Is it, at this point, safe to say this was/is a problem in Doxygen or some configuration issue? If so this issue can be closed, unless there is something Breathe can do of course.

**Comment by psifertex** [comment]
I'm not entirely sure honestly, I never did finish running it down but rather switched my config. I'll go ahead and close it for now and re-open it if I go back and get any more info. Thanks.
