### ISSUE TITLE
Parsing Error on typedef that Uses a Macro

### ISSUE THREAD

**Issue by iguessthislldo** [michaeljones/breathe#595]
Using Breathe 4.23 and Doxgyen version 1.8.13. Can try with newer version of Doxygen if that matters.

Breathe emits these warnings during the sphinx build:

```
OpenDDS/docs/index.rst:27: WARNING: Error when parsing function declaration.
If the function has no return type:
  Error in declarator or parameters-and-qualifiers
  Invalid C++ declaration: Expected identifier in nested name, got keyword: typedef [error at 7]
    typedef OPENDDS_MAP (Discovery::RepoKey, Discovery_rch) RepoKeyDiscoveryMap
    -------^
If the function has a return type:
  Invalid C++ declaration: Expected identifier in nested name, got keyword: typedef [error at 7]
    typedef OPENDDS_MAP (Discovery::RepoKey, Discovery_rch) RepoKeyDiscoveryMap
    -------^
```

[Here is the code in full context if needed](https://github.com/objectcomputing/OpenDDS/blob/a9a20c7e357323e84030942b8fcbd6d4fdd91c76/dds/DCPS/Service_Participant.h#L339)

`OPENDDS_MAP` is defined with `#define OPENDDS_MAP(K, V) std::map<K, V >` in this case.

**Comment by jakobandersen** [comment]
I don't think Breathe is to blame as it "just" passes the data along to Sphinx.
Neither Breathe nor Sphinx does macro expansion, so Sphinx complains because it's not valid C++.
Without changing code, perhaps you can get Doxygen to expand the macro?
A more robust solution may be to abstract ``OPENDDS_MAP`` using C++ instead of the preprocessor. For example:
```c++
// >= C++11
template<typename Key, typename Value>
using OpenDDSMap = std::map<Key, Value>;
// use: OpenDDSMap<k, v>

// < C++11
template<typename Key, typename Value>
struct OpenDDSMap {
    typedef std::map<Key, Value> type;
};
// use: OpenDDSMap<k, v>::type
```

**Comment by vermeeren** [comment]
@iguessthislldo Indeed handling expansion in Doxygen should fix this, as @jakobandersen suggests. There are a few options available to control how exactly Doxygen behaves.

* https://www.doxygen.nl/manual/preprocessing.html
* https://www.doxygen.nl/manual/config.html#cfg_macro_expansion
* https://www.doxygen.nl/manual/config.html#cfg_expand_only_predef
* https://www.doxygen.nl/manual/config.html#cfg_expand_as_defined

**Comment by iguessthislldo** [comment]
Although we're trying to reduce macro usage, I don't think I can justify changing code just for this. I'm just exploring Breathe right now and that macro and many like it are being used in many places .

Thanks for pointing me towards the Doxygen config though. Ours had `EXPAND_ONLY_PREDEF = YES` and changing that to `NO` fixed the warnings.
