### ISSUE TITLE
Cross referencing in brief description

### ISSUE THREAD

**Issue by Lucide** [michaeljones/breathe#598]
Doxygen autolink feature doesn't get translated by Breathe, so reStructuredText's [cross references](https://www.sphinx-doc.org/en/master/usage/restructuredtext/roles.html#ref-role) has to be used instead.
Breathe uses the `\verbatim` command to write rst directly in the code, that, unfortunately, is considered a sectioning command.
Doxygen's `\brief` command [terminates when a sectioning command is found](https://www.doxygen.nl/manual/commands.html#cmdbrief#:~:text=A%20brief%20description%20ends%20when%20a%20blank%20line%20or%20another%20sectioning%20command%20is%20encountered.), and the link gets dumped in the long description, in the following paragraph.
`embed:rst:inline` doesn't help here because it's a Doxygen-side behaviour.
Even the [special C++ style comment approach](https://www.doxygen.nl/manual/docblocks.html#specialblock#:~:text=A%20third%20option%20is%20to%20use%20a,than%20one%20line.%20Here%20are%20two%20examples%3A) (with [`MULTILINE_CPP_IS_BRIEF`](https://www.doxygen.nl/manual/config.html#cfg_multiline_cpp_is_brief) set to `YES`) doesn't work!
I have *a lot* of situations where a brief description would benefit from a cross-reference, is there any trick/workaround I'm not aware of, to do this?

Examples:

```c
/**
 * @brief Represents a read-only array of VTStr.
 *
 * ...
 */
typedef uint8_t const *const *VTStrs;

/**
 * @brief A helper macro to cast a literal string to a VTStr
 */
#define LTSTR (VTStr)
```

Where `VTStr` is a documented `typedef`.

**Comment by vermeeren** [comment]
@Lucide Do you know if this autolinking by Doxygen in part of the XML of the brief description? In other words, does the XML output contain some form of linkage for `VTStr`?

If this is the case it should be possible to add autolink to Breathe by using the XML data. If it isn't in the XML it's gonna be a lot trickier though.

**Comment by Lucide** [comment]
I was waiting to get some time to investigate, but in the meantime I've seen the similar situations referenced and in already existing issues: #400, #438. (even with potential workarounds). I'm closing this one.👍
