### ISSUE TITLE
Doxygen \mainpage is not showing up

### ISSUE THREAD

**Issue by sekargovindarajan** [michaeljones/breathe#619]
Hi, First of all thank you for this amazing tool.

I see that indexpage.xml containing \mainpage is being generated by Doxygen. I was expecting that sphinx would render this through breathe, but it does NOT. Should I do something special to capture the contents of \mainpage?

Thanks.

**Comment by svenevs** [comment]
Added comment on the exhale issue https://github.com/svenevs/exhale/issues/100#issuecomment-756786806 it seems like it's more appropriate to solve with exhale or discourage usage of `\mainpage` in lieu of transcribing to a custom `.rst` doc in sphinx.

It has some potential overlap here with either `.. doxygenindex::` and what to do about `\ref index` when encountered in breathe e.g. from a class or function documentation etc.  AKA not sure where to discuss what so just linking both for now :slightly_smiling_face:

**Comment by sekargovindarajan** [comment]
I realized my misunderstanding after I posted the issue. As @svenevs points out, and I have confirmed, the XML file for main page is getting generated, and this issue can be handled by exhale, if at all.

So, I am closing the issue.
