### ISSUE TITLE
Descriptions not visible.

### ISSUE THREAD

**Issue by AlexandreFoley** [michaeljones/breathe#620]
I tried to setup doxygen+breathe+sphinx following this [tutorial](https://devblogs.microsoft.com/cppblog/clear-functional-c-documentation-with-sphinx-breathe-doxygen-cmake/).

It seems to almost work. The only one (rather big) problem: none of the documentation string shows up in the resulting sphinx website.

I took a glance at doxygen's generated XML: the information is present, although i have no clue if it has the format expected by breathe.

The output I get looks like the following:
![Capture](https://user-images.githubusercontent.com/16018747/104369070-ebcb9400-54ea-11eb-9dc6-d29bb0b87c08.PNG)
The relevent c++ code with comment is
    
    /**
     * 
     * long description --
     * 
     */
    class this_is_a_test
    {
    	public:
    	/**
    	 * @brief member brief
    	 * 
    	 * member long description
    	 * 
    	 */
    	int a;
    
    	/**
    	 * @brief add to a
    	 * 
    	 * add the argument to a
    	 * 
    	 * @param x value to add
    	 * 
    	 * @return original value of a
    	 */
    	int add(int x);
    
    	void not_documented(double Ah);
    };

It doesn't matter wheither it is a class, a freestanding function or a member, no docstring is visible, enven though they are detected as documented.

I have sphinx 3.1.4, docutils 0.16, breathe 4.26, doxygen 1.8.20-6

Here's the relevent configuration, xml and rst files:
[index.rst.txt](https://github.com/michaeljones/breathe/files/5804608/index.rst.txt)
[index.xml.txt](https://github.com/michaeljones/breathe/files/5804592/index.xml.txt)
[classthis__is__a__test.xml.txt](https://github.com/michaeljones/breathe/files/5804597/classthis__is__a__test.xml.txt)
[conf.py.txt](https://github.com/michaeljones/breathe/files/5804604/conf.py.txt)

Thanks in advance for whatever help you can provide.

**Comment by vermeeren** [comment]
@AlexandreFoley Looks like you are passing `:outline:` to all the directives, from documentation https://breathe.readthedocs.io/en/latest/directives.html 

> Results in Breathe only outputting the raw code definitions without any additional description information.

Can you try removing that flag?

**Comment by AlexandreFoley** [comment]
lol, I thought I had tried that.

That was the problem. Wihtout the :outline: directive I get the ouput I desired. Thank you.
