### ISSUE TITLE
Use breathe to convert doxygen docs to rst 

### ISSUE THREAD

**Issue by awsteiner** [michaeljones/breathe#621]
Thank you for breathe. Whew!

Normally, AFAIK, breathe uses the doxygen XML output to generate HTML, and one can use, e.g. doxygenfunction directive to generate the HTML documentation for a particular function. Is there a way to configure breathe to generate rst output instead, so that I can manually edit the rst source and then regenerate the documentation?

**Comment by jakobandersen** [comment]
Not at this time, Breathe directly produces Docutils nodes that Sphinx then renders to output formats, e.g., HTML.
Perhaps some of the edits can be done by Breathe with extra options to the directives. Do you have some specific edit schemes in mind?

**Comment by awsteiner** [comment]
No thank you. I was just experimenting with different ways to update my documentation workflow.
