### ISSUE TITLE
Qt Signals & Slots

### ISSUE THREAD

**Issue by fizzyade** [michaeljones/breathe#626]
I'm trying to generate documentation using doxygen, sphinx and breathe.  When it parses the XML documentation, I get errors like:

`/Users/adriancarpenter/Documents/Development/pingnoo/docs/sphinx/documentation.rst:5: WARNING: Error when parsing function declaration.
If the function has no return type:
  Error in declarator or parameters-and-qualifiers
  Invalid C++ declaration: Expecting "(" in parameters-and-qualifiers. [error at 9]
    Q_SIGNAL void valueChanged (LatencyType type, double value)
    ---------^
If the function has a return type:
  Error in declarator or parameters-and-qualifiers
  If pointer to member declarator:
    Invalid C++ declaration: Expected identifier in nested name, got keyword: void [error at 13]
      Q_SIGNAL void valueChanged (LatencyType type, double value)
      -------------^
  If declarator-id:
    Invalid C++ declaration: Expected identifier in nested name, got keyword: void [error at 13]
      Q_SIGNAL void valueChanged (LatencyType type, double value)
      -------------^
`

I'm guessing this is due to using Q_SIGNAL instead of signals:

I've searched, tried every option I could think of, but breathe just doesn't like my code.

Am I doing something wrong or does breathe not know about this style of signals & slots, the example code uses the signals: form?

**Comment by vermeeren** [comment]
@fizzyade You should post your C++ and RST code so I can check further. Also code block uses triple backticks ```` ``` ````.

Recently there was something related to Qt signals in #592, there is seemed like a Doxygen issue, possibly misconfiguration somehow. As far as I know signals and slots should work properly with Breathe. I don't have any experience with them though, so I cannot advise further.

**Comment by fizzyade** [comment]
> @fizzyade You should post your C++ and RST code so I can check further. 
> 
> Recently there was something related to Qt signals in #592, there is seemed like a Doxygen issue, possibly misconfiguration somehow. As far as I know signals and slots should work properly with Breathe. I don't have any experience with them though, so I cannot advise further.

Literally all you have to do is instead of having a class defined like:


```c++
class MyClass : public QObject {
    public slots:
        void myFunction();
}
``` 

you define it like this:

```c++
class MyClass : public QObject {
    public:
        Q_SLOT void myFunction();
}
``` 

Breathe throws the following error.  It's reproducible by taking the example Qt class in the breathe repo and just replacing the signals:/slots: with Q_SIGNAL or Q_SLOT on each signal/slot (or just one, as soon as it comes across this format of slot/signal definition it fails.

It looks like breathe is seeing Q_SLOT and thinks that is the return type.

```/Users/adriancarpenter/Documents/Development/pingnoo/docs/sphinx/documentation.rst:5: WARNING: Error when parsing function declaration.
If the function has no return type:
  Error in declarator or parameters-and-qualifiers
  Invalid C++ declaration: Expecting "(" in parameters-and-qualifiers. [error at 7]
    Q_SLOT void onPingResult (Nedrysoft::Core::PingResult result)
    -------^
If the function has a return type:
  Error in declarator or parameters-and-qualifiers
  If pointer to member declarator:
    Invalid C++ declaration: Expected identifier in nested name, got keyword: void [error at 11]
      Q_SLOT void onPingResult (Nedrysoft::Core::PingResult result)
      -----------^
  If declarator-id:
    Invalid C++ declaration: Expected identifier in nested name, got keyword: void [error at 11]
      Q_SLOT void onPingResult (Nedrysoft::Core::PingResult result)
      -----------^
```

**Comment by jakobandersen** [comment]
The error is actually from Sphinx because there is no macro substitution. However, in this case the ``Q_SLOT`` macro is basically acting as an attribute, so if you in ``conf.py`` inserts ``cpp_id_attributes = ["Q_SLOT"]`` it should parse.
(https://www.sphinx-doc.org/en/master/usage/configuration.html#confval-cpp_id_attributes)

**Comment by fizzyade** [comment]
Thanks for the reply. I will talk a look!

I’ll let you know how I get on, but thanks for the quick response and pointer, it's much appreciated.

This is the first time I've used sphinx or breathe or RTD, so it's a bit of a learning curve!

**Comment by fizzyade** [comment]
> The error is actually from Sphinx because there is no macro substitution. However, in this case the `Q_SLOT` macro is basically acting as an attribute, so if you in `conf.py` inserts `cpp_id_attributes = ["Q_SLOT"]` it should parse.
> (https://www.sphinx-doc.org/en/master/usage/configuration.html#confval-cpp_id_attributes)

Ok many thanks, that solved that issue, but now I've hit another one (I'm guessing it's also sphinx so feel free to tell me to go ask them about it - I just figured asking here with regards to the "Q_" macros that if somebody else hits the same issue then the solution will all be in one place )

Q_PROPERTY

This is causing the following error:

```  File "/usr/local/lib/python3.8/site-packages/breathe/renderer/sphinxrenderer.py", line 219, in create
    cls, name = DomainDirectiveFactory.cpp_classes[args[0]]  # type: ignore
KeyError: 'property'```

if I edit sphinxrenderer.py and add "property" to cpp_classes then it parses.

**Comment by jakobandersen** [comment]
Nice. The ``Q_PROPERTY`` issue superficially looks similar to #574.

**Comment by fizzyade** [comment]
> Nice. The `Q_PROPERTY` issue superficially looks similar to #574.

Ha.  They did the same fix as me, adding property as a macro does at least allow the parsing to complete.

I guess this is the answer for now!

**Comment by vermeeren** [comment]
I think the original problem has been solved with the `cpp_id_atributes` option, closing this one as the remainder is already tracked in #574. Thanks!

**Comment by hasselmm** [comment]
Seems breathe also shivers on Qt specific attributes like Q_INVOKABLE, and on Windows specific export attributes.
