### ISSUE TITLE
Html tables are not rendered in Sphinx

### ISSUE THREAD

**Issue by ollehu** [michaeljones/breathe#629]
Hi,

HTML tables, for example
`<table cellspacing= 20><tr><th>First String</th><th>Second String</th></tr><tr><td>Hello</td><td>there</td></tr></table>"`,
are properly generated in the Doxygen HTML output - but not at all in the Sphinx output.

I am more than happy to implement this, but I can not manage to get Breathe to read the table-node from the XML (and yes, the table is present in the xml-output, see example below.).

```
<para><table rows="2" cols="2"><row>
<entry thead="yes"><para>First String</para>
</entry><entry thead="yes"><para>Second String</para>
</entry></row>
<row>
<entry thead="no"><para>Hello</para>
</entry><entry thead="no"><para>there</para>
</entry></row>
</table>
</para>
```
Can someone perhaps push me in the right direction?

**Comment by utzig** [comment]
A big coincidence but I found this out today while importing some Doxygen documentation into a project. I think I'll do a bit of work on it... I'll let you know if I make any progress.

**Comment by ollehu** [comment]
@utzig Sounds great, let me know if I can help.
