### ISSUE TITLE
C++ #define 's not showing their initialised values

### ISSUE THREAD

**Issue by Tucker11** [michaeljones/breathe#633]
I'm trying to use breathe, doxygen and sphinx to document a c++ project, and it all seems to be working fine except for displaying the initialised value of the #define statement. It displays the name and description fine, but leaves out the initialised value. Looking at the generated doxygen html, it displays correctly. The generated xml also has the initialised value.

So it looks like my problem is happening going from the doxygen xml to sphinx html.
I would appreciate any pointers towards what I'm doing wrong.

Thanks

![Screenshot from 2021-02-05 14-15-35](https://user-images.githubusercontent.com/15341151/106985152-024cce80-67bd-11eb-8068-fb55f18b1e6d.png)
![Screenshot from 2021-02-05 14-16-10](https://user-images.githubusercontent.com/15341151/106985161-0842af80-67bd-11eb-9ee5-ade30ea42a47.png)
![Screenshot from 2021-02-05 14-17-25](https://user-images.githubusercontent.com/15341151/106985165-0a0c7300-67bd-11eb-99ef-dba5c2aca945.png)

**Comment by vermeeren** [comment]
@Tucker11 Did you check https://breathe.readthedocs.io/en/latest/directives.html#confval-breathe_show_define_initializer?

**Comment by Tucker11** [comment]
I hadn’t come across this page. 
Thank you
