### ISSUE TITLE
Declarations in super class should be made available in subclasses

### ISSUE THREAD

**Issue by mquinson** [michaeljones/breathe#643]
Hello,

I would like to document in a subclass methods that are defined in a super-class, but breathe complains that the method cannot be found in the XML.

For example, given the following C++ code:
```c++
class A {
public:
   /** useful method */
   bool meth();
};
class B : public A {};
```

I would like the following RST excerpts to work:
```rst
.. doxygenmethod:: B::meth()
```

This should be changed to 
```rst
.. cpp:func:: bool B::meth()

  useful method
```

**Comment by vermeeren** [comment]
@mquinson Do you mean `doxygenfunction`, there is no `doxygenmethod` in Breathe.

Could you check the Doxygen XML? Maybe you need to set `INLINE_INHERITED_MEMB = YES` in your doxygen configuration. https://www.doxygen.nl/manual/config.html#cfg_inline_inherited_memb

**Comment by mquinson** [comment]
Yes and yes. Yes there was a typo in my RST example, and yes I'm unable to read the Doxygen documentation :(

Sorry for the noise, and thanks for this great tool.
Mt
