### ISSUE TITLE
Spurious error with function pointer as template argument

### ISSUE THREAD

**Issue by wintersteiger** [michaeljones/breathe#652]
**Describe the bug**

For this:

    /// @brief A template class
    template <void (*F)()>
    class C {};

Sphinx complains thusly:

    | [(DefinitionError('Invalid C++ declaration: Expected "," or ">". [error at 19]\n  template<void(*)() F> C\n  -------------------^'), 'If no parameter')]
    |/data/cwinter/breathe/source/index.rst:11: WARNING: Error in template parameter list.
    Invalid C++ declaration: Expected "," or ">". [error at 19]
      template<void(*)() F> C
      -------------------^

**To Reproduce**

Copy source snippet above into .h file and run Sphinx with Breathe extension enabled (see project files)

    $ sphinx-autobuild source build

**Expected behavior**

Don't throw an error and produce the right type names. (When the error is thrown some types are assigned names with `PhonyNameDueToError`.)

**Your project**

[sphinx-templates.zip](https://github.com/michaeljones/breathe/files/6078319/sphinx-templates.zip)

**Environment info**
- OS: Ubuntu 18.04
- Python version: 3.8.0
- Sphinx version: 3.5.1
- Sphinx extensions:  breathe
- Extra tools: doxygen 1.9.2

(From https://github.com/sphinx-doc/sphinx/issues/8953)

**Comment by jakobandersen** [comment]
This is quite an icky bug. The XML for ``C`` is
```xml
<compounddef id="classC" kind="class" language="C++" prot="public">
  <compoundname>C</compoundname>
  <includes refid="test_8hpp" local="no">test.hpp</includes>
  <templateparamlist>
    <param>
      <type>void(*)()</type>
      <declname>F</declname>
      <defname>F</defname>
    </param>
  </templateparamlist>
  ...
</compounddef>
```
I don't see a generic way of getting the parameter name ``F`` in the correct part of the type ``void (*)()`` without parsing the type, in the general case.
I suggest using the Sphinx C++ parser to get the AST to assemble the paramter the right way.

**Comment by wintersteiger** [comment]
Yes, I think it's impossible to do this without parsing the type. I'm not familiar with the Sphinx C++ parser - is that in some way configurable by the end-user or would this require changes to the parser implementation?
