### ISSUE TITLE
Comma out of place in functions that take function pointers as arguments

### ISSUE THREAD

**Issue by ropg** [michaeljones/breathe#653]
I have a function that is prototyped as follows:

``` c++
void addHandler (void(*fn)(), uint16_t eventMask=E_ALL, bool offspring=false);
```

Doxygen has no problems and renders:

![Screenshot 2021-03-04 at 18 37 21](https://user-images.githubusercontent.com/343196/110005389-b4be7580-7d18-11eb-8b33-f0b0716a3937.png)

But when I do:

``` rst
.. doxygenclass:: Eventful
```

in breathe (4.27.0) with sphinx 3.5.1, it renders:

![Screenshot 2021-03-04 at 18 40 17](https://user-images.githubusercontent.com/343196/110005841-357d7180-7d19-11eb-861a-dec0cba085b6.png)

(Ignore the funky colors, that's some custom CSS I'm playing with. Just note the missing comma and the erroneous addition of the last comma...)

The HTML there is:

``` html
<dl class="cpp function">
   <dt id="_CPPv4N8Eventful10addHandlerEPFvvE8uint16_tb">
      <span id="_CPPv3N8Eventful10addHandlerEPFvvE8uint16_tb"></span>
      <span id="_CPPv2N8Eventful10addHandlerEPFvvE8uint16_tb"></span>
      <span class="target" id="class_eventful_1a687985a550e45579092dff3d791ac319"></span>
      <span class="pre">void</span>
      <code class="sig-name descname">
        <span class="pre">addHandler</span>
      </code>
      <span class="sig-paren">(</span>
      <span class="pre">void</span>
      <span class="pre">(</span>
      <span class="pre">*</span>
      <em><span class="pre">fn</span></em>
      <span class="pre">)</span>
      <span class="sig-paren">(</span>
      <span class="sig-paren">)</span>
      <span class="pre">uint16_t</span>
      <em><span class="pre">eventMask</span></em>
      <span class="pre">=</span>
      <span class="pre">E_ALL</span>
      , 
      <span class="pre">bool</span>
      <em><span class="pre">offspring</span></em>
      <span class="pre">=</span>
      <span class="pre">false</span>
      ,
      <span class="sig-paren">)</span>
      <a class="headerlink" href="#_CPPv4N8Eventful10addHandlerEPFvvE8uint16_tb" title="Permalink to this definition">¶</a
      <br>
   </dt>
   <dd></dd>
</dl>
```

So the comma really ends up in the wrong place in the HTML. As everything else is fine, this seems connected to having the `(*fn)()` function pointer as first argument. It does not act up if the same function pointer is the last argument.

**Comment by ropg** [comment]
This may well be be connected to issue #652, just based on that also having to do with function pointers as arguments.

**Comment by jakobandersen** [comment]
Thanks for reporting. It turns out this is a Sphinx issue, so I have opened sphinx-doc/sphinx#8960.

**Comment by ropg** [comment]
Thank you... I'll close it here then...
