### ISSUE TITLE
Data/return type concatenated to variables/function name

### ISSUE THREAD

**Issue by RazailaAlexandra** [michaeljones/breathe#655]
Hello!
I tried to generate documentation file for a C++ project using breathe, but on the .html page the returned type is concatenated to the function name and so are the type of parameters and their name.
Version used: Breathe=4.27.0, Sphinx=3.5.1, Python=3.6.7, Doxygen=1.9.1
Here is a short example:
![docFunc](https://user-images.githubusercontent.com/49149499/110463165-3d069700-80da-11eb-8df1-180a75617d10.PNG)
I would like it to look like this:
void  say_hello(std:string  message)const

I attached an example of project to can see the problem:
[exampleProject.zip](https://github.com/michaeljones/breathe/files/6108424/exampleProject.zip)

**Comment by jakobandersen** [comment]
There are two other spaces missing in the declaration as well, rather annoying. I have previously seen this issue, but only with the readthedocs theme. It seems like they have an open issue with this readthedocs/sphinx_rtd_theme#694.

**Comment by RazailaAlexandra** [comment]
Thank you for your answer.
Do you know about any workaround for this issue?

**Comment by jakobandersen** [comment]
As discussed in https://github.com/michaeljones/breathe/pull/628, this issue seems to accidentally be resolved (for C++) if https://github.com/sphinx-doc/sphinx/pull/9023 gets merged.

**Comment by vermeeren** [comment]
Going to close this one at the Breathe side in an attempt to tidy up the issue tracker a bit, thanks for upstream work as always @jakobandersen !
