### ISSUE TITLE
Error: Expected identifier in nested name

### ISSUE THREAD

**Issue by Amaya-aisi** [michaeljones/breathe#664]
### Problem
I use ```extention=['breathe','exhale']``` and during programming it reports this error
I find the error is this line
```
.. doxygenfunction:: a::b::c::d("12345")
```
a,b,c,d,12345 is just replaced the real name because it is a private code. Breathe seems cannot support this kind of function?

### Env info
 breathe ==4.27.0
 exhale == 0.2.3

**Comment by jakobandersen** [comment]
You need to specify the function parameters for the overload you would like to insert documentation for. That is, ``"12345"`` should be a type instead of an expression.

**Comment by Amaya-aisi** [comment]
Cool. Are there any methods in Exhale or Sphinx, or do I need to change my code?

**Comment by jakobandersen** [comment]
I'm not exactly sure what you mean, and my knowledge of Exhale is rather limited.
If you want to document a function manually, use the Sphinx directive ``cpp:function``.
If you want to document a function semi-automatically by insert documentation from Doxygen-generated XML, use the Breathe directive ``doxygenfunction``.
If you want to typeset an expression or type you can use the Sphinx role ``cpp:expr``.

**Comment by Amaya-aisi** [comment]
Thank you so much. I didn't make it clear. What I mean is how to fix this line and make it can compile, because Sphinx will report an error and stop running because of it. Or Is there any way that Sphinx can bypass this error or could explain this kind of code? I have a lot of lines in my code, and it would be cumbersome to change them manually.

**Comment by vermeeren** [comment]
@Amaya-aisi I think at the minimum we would need more information and a reproducible example would very much help out. If the code is private creating a mock-up should be fine. Without function signature details, backtraces and a reproduction case there isn't much we can do.
