### ISSUE TITLE
Breathe 4.29.0 fails when using [in] parameter attribute on Doxygen

### ISSUE THREAD

**Issue by gmarull** [michaeljones/breathe#673]
It looks like the latest release of Breathe, 4.29.0 fails to build Doxygen documentation containing the `[in]` parameter attribute.

Example file causing build problems (it did not before): 
https://github.com/zephyrproject-rtos/zephyr/blob/master/include/debug/coredump.h#L210

Ref.
https://github.com/zephyrproject-rtos/zephyr/pull/34181/checks?check_run_id=2309412465

**Comment by CareF** [comment]
I'm having the same issue

**Comment by utzig** [comment]
Quite a weird one, considering that Doxygen directions like `[in]`, `[out]` are not even in the output XML, or are not supposed to be.

**Comment by jakobandersen** [comment]
This is due to #670 where the parameters are now interpreted by Sphinx instead of being literal text. Though, I completely forgot about the parameter directions. I think I'm close to a fix.

**Comment by jakobandersen** [comment]
PR posted (#675).

**Comment by jakobandersen** [comment]
> Quite a weird one, considering that Doxygen directions like `[in]`, `[out]` are not even in the output XML, or are not supposed to be.

It is indeed strange. It looks like the XML parser/converter in Breathe at some point creates those. In the AST in the renderer, they are already formatted like this.
