### ISSUE TITLE
How to select between multiples functions having the same name 

### ISSUE THREAD

**Issue by hellgheast** [michaeljones/breathe#677]
Hello,
I would like to know how I should proceed to select a specific function to be shown using ..doxygenfunction directive for the following case:
suppose we got

`void func(int arg)`
in file folder_1/a.c and folder_2/a.c

how should I proceed to select specifically the function definition from a given file.
Ideally it should have this form.

.. doxygenfunction func
   :source-path: folder_1
or either
.. doxygenfunction folder_1/func

If there's any workaround using separate xml folder I would be interested.

Thanks in advance,
Ismail

**Comment by jakobandersen** [comment]
If I remember correctly, then such duplicates must be in separate 'projects'. In ``conf.py`` you can then add these separate projects via ``breathe_projects``. For the ``doxygenfunction`` directive you can then give the option ``:project: someProject``, to narrow the XML search to that particular project.

**Comment by hellgheast** [comment]
okey !
Thank you very much.

Solution is then : adopt multiples doxygen projects which each of them having a specific xml folder output and modify the conf.py to be able to select the correct xml through the breath project directive.
