### ISSUE TITLE
Creating cross-ref targets in doxygen text

### ISSUE THREAD

**Issue by JamesRandom** [michaeljones/breathe#680]
Is there a way of generating a target to arbitrary text in the Doxygen comment that can be linked to by `:ref:`?

A common use case is a class or function that has an `options` parameter: the description includes a list of option values. I would like to link to that list from elsewhere in the documentation.

For example, I would like to be able to link to the "Engine creation options" line, in the following:

```
/** A graph compute engine.
 *
 *  The Engine class provides the ability to execute a graph program. 
 *  ...
 *
 * **Engine creation options**
 *
 *    * `opt.maxCompilationThreads` Integer [=0]
 *    * `opt.maxLinkerThreads` Integer [=0]
```

**Comment by jakobandersen** [comment]
I don't think there is a good solution for that at the moment for the general case.
Doxygen has the [``\anchor``](https://www.doxygen.nl/manual/commands.html#cmdanchor) and [``\ref``](https://www.doxygen.nl/manual/commands.html#cmdref) commands which Breathe translates. But I'm not sure how to use a raw ``:ref:`` in rst to point to the anchor. It also seems that the anchor name is prefixed internally in Doxygen with the name of the entity the comment is at. E.g., an anchor ``myAnchor`` in the documentation of a class ``C`` becomes ``classC_1myAnchor`` in the Doxygen XML.

**Comment by JamesRandom** [comment]
Thanks for the tip. I ended up using `<a id="anchor_name"></a>` as that worked with `:ref:` (using `\anchor` doesn't for some reason) and is less decorated (the anchor becomes `_1anchor_name`).
