### ISSUE TITLE
breathe-apidoc does not list members by default

### ISSUE THREAD

**Issue by twodrops** [michaeljones/breathe#691]
When ``breathe-apidoc`` is used to generate classes (with ``-g class``), it writes the following into the generated rst files.

```
.. doxygenclass:: <class name>
   :project: <project name>
```
With the above, no members are listed which makes it not so useful. It will be good if members are listed by default.

```
.. doxygenclass:: <class name>
   :project: <project name>
   :members:
```

**Comment by vermeeren** [comment]
@twodrops I think we should add `-m, --members` option to `breathe-apidoc`. It's fairly standalone at https://github.com/michaeljones/breathe/blob/master/breathe/apidoc.py so this should be easy to do.

I'll give this a quick try and ask you to test it.

**Comment by twodrops** [comment]
@vermeeren cool! That works simply great. Thanks a lot for that quick implementation.
Do you plan to make a release with that?

**Comment by vermeeren** [comment]
@twodrops Yeah I will merge it in a sec, hopefully CICD is working again today as the failure so far is very odd considering patch does not touch Breathe itself in any way.

When that's all working again I'll make a release.
