### ISSUE TITLE
retval value is duplicated

### ISSUE THREAD

**Issue by gmarull** [michaeljones/breathe#692]
The following docstring:

```c
/**
 * @brief Foo.
 *
 * @retval 0 success.
 * @retval -1 error.
 */
int foo(void);
```

Renders as:
![image](https://user-images.githubusercontent.com/25011557/117117614-0b374700-ad90-11eb-8c87-1cbbec14f91a.png)

Breathe version: 4.29.2

**Comment by K3WLBUDDY** [comment]
This seems to be a duplicate of https://github.com/michaeljones/breathe/issues/684

**Comment by gmarull** [comment]
Ok, I see it's now fixed on master. Let's wait for the next fix release.
