### ISSUE TITLE
doxygenfunction generates "WARNING: c:identifier reference target not found: int32_t"

### ISSUE THREAD

**Issue by SchindlerTo** [michaeljones/breathe#696]
Hi,

we are starting to use doxygen->breathe->sphinx pipeline for documenting a C project. This is a really nice project, thanks a lot for creating this (!) and everything works  quite well, e.g.,

`/**
 * @brief C=A*B
 * 
 * @param A Parameter
 * @param B Parameter
 * @return int32_t Returns the result
 */
int32_t multiply(int32_t A, int32_t B);
`

Using

`.. doxygenfunction:: multiply`

generates a nice API documentation. However, building the documentation with `make html SPHINXOPTS="-W --keep-going -n"` generates the following warnings:
`WARNING: c:identifier reference target not found: int32_t`

I tried the `:no-link:` option but am struggling to find any google results/documentation for this. Any pointers to a solution would be greatly appreciated!

**Comment by vermeeren** [comment]
@SchindlerTo For the return there is no need to prefix it with the type, as Doxygen itself knows this by parsing.

I am not sure if this is caused the reference warning, as something might be trying to create a reference automagically based upon type name. Can you try with:

```
@return Returns the result
```

See also examples on https://www.doxygen.nl/manual/docblocks.html .

**Comment by SchindlerTo** [comment]
Thanks for the quick response! :) 
I followed your advice but I am not sure if this is related. Tested the following:
```
/**
 * @brief C=A*B
 * 
 * @param A Parameter
 * @param B Parameter
 * @return Returns the result
 */
int32_t multiply(int32_t A, int32_t B);

/**
 * @brief Multiply float by int to test docs pipeline
 * 
 * @param A 
 * @param B 
 * @return  
 */
float multiply2(float A, int B);
```

Which results in the following warnings:
```
WARNING: c:identifier reference target not found: int32_t
WARNING: c:identifier reference target not found: int32_t
WARNING: c:identifier reference target not found: int32_t
```

I tested different combinations and this warning is only present if the types are not the base types int/float/.. but a typedef such as defined length types or our own typedefs.

**Comment by jakobandersen** [comment]
I don't think this is a Breathe issue, but at most a Sphinx issue. However, these warnings are expected in nitpicky mode: the type ``int32_t`` is neither a fundamental type nor documented, so Sphinx can't find anywhere to link the identifier.
In your configuration you can add [filters](https://www.sphinx-doc.org/en/master/usage/configuration.html#confval-nitpick_ignore_regex) to ignore specific missing targets.
In this case it should work either by adding ``('c:identifier', 'int32_t')`` to ``nitpick_ignore`` or more generally adding ``(r'c:.*', 'int32_t')`` to ``nitpick_ignore_regex``. Though the latter requires using the Sphinx branch 4.x which will become v4.1 in a month or so.

**Comment by SchindlerTo** [comment]
Thanks for the input! Consider this solved since your links provide nice solutions.

I also came to the conclusion that this is not related to breathe. I do not know why, but I just sort of assumed that standard header types are treated the same way as the fundamental types.
I tested the following with the c:directive :

```
.. c:type:: int32_t

.. c:function:: int32_t testfunction(int A)
```

And this get's rid of the warning and even the links work. The same is true for typedefs with `.. doxygentypedef::` (though not for the standard headers since they are not documented [in our] doxygen xml).
I'll look into your suggestions @jakobandersen or just create a docs page with all the fixed-length types.

Thanks :+1:

**Comment by SchindlerTo** [comment]
Added to `conf.py`:

```
nitpick_ignore = [
    ('c:identifier', 'int32_t'),
    ('c:identifier', 'uint32_t'),
    ('c:identifier', 'bool'),
]
```

**Comment by jakobandersen** [comment]
Indeed these types are almost always indistinguishable from the fundamental types. Perhaps we should add a configuration variable in Sphinx to optionally ignore them for cross-referencing. If you open an issue over there I'll take a look at it at some point.
