### ISSUE TITLE
Multi-line code include going wrong

### ISSUE THREAD

**Issue by michaeljones** [michaeljones/breathe#70]
The latest gh-pages has a broken code include in the doxygen test area. The formatting is putting each line into its own text box rather than all in one.

**Comment by michaeljones** [comment]
Still an issue, though not happening to every code block. It seems that lines with a link on it result in a new code block. 

eg. https://breathe.readthedocs.org/en/latest/doxygen.html#include

**Comment by vitaut** [comment]
This looks like a parser problem. In `DocParaTypeSubRenderer.render` all the content nodes are in `self.data_object.content` and program listing nodes are in `self.data_object.programlisting` while they should alternate.

**Comment by vitaut** [comment]
An easy fix is to change

```python
        elif child_.nodeType == Node.ELEMENT_NODE and nodeName_ == 'programlisting':
            obj_ = supermod.listingType.factory()
            obj_.build(child_)
            self.programlisting.append(obj_)
```
to 
```python
        elif child_.nodeType == Node.ELEMENT_NODE and nodeName_ == 'programlisting':
            obj_ = supermod.listingType.factory()
            obj_.build(child_)
            self.content.append(obj_)
```

in `docParaTypeSub.buildChildren` but I'm not sure if it's the right thing to do since this is a generated code.

**Comment by vitaut** [comment]
#251 implements a tentative fix. It will work unless `compound.py` is re-generated.
