### ISSUE TITLE
Parsing issues with Sphinx 4.0.1

### ISSUE THREAD

**Issue by outoftardis** [michaeljones/breathe#700]
With Sphinx 4.0.1, `breathe` parses Doxygen xml output in a way that results in incorrect markup.

**Common configs:**
- ``breathe==4.30.0``
- ``sphinx-book-theme==0.1.0``

## HTML

Here's the html code for the element containing the name of the class:

1) Correct parsing (``Sphinx==3.5.4``):

```
<code class="sig-name descname"><span class="pre">Nutshell</span></code>
```

2) Incorrect parsing (``Sphinx==4.0.1``):

```
<span class="sig-name descname"><span class="n"><span class="pre">Nutshell</span></span></span>
```

So basically with the latest version of Sphinx what used to be rendered as inline code is now treated as plain text.

## Screenshots

1) Correct parsing (``Sphinx==3.5.4``):

![image](https://user-images.githubusercontent.com/17865025/118640133-4d757500-b7e1-11eb-89bc-8177ea8977e9.png)

2) Incorrect parsing (``Sphinx==4.0.1``):

![image](https://user-images.githubusercontent.com/17865025/118640075-3f275900-b7e1-11eb-97c7-f5b596cc560b.png)

The example (rst/header) is taken [directly from the breathe documentation](https://breathe.readthedocs.io/en/latest/#in-a-nutshell).

**Comment by jakobandersen** [comment]
This is due to a change in Sphinx, and is intentional. The previous code generation was inconsistent in styling and didn't offer options for themes to customize all elements. See https://github.com/sphinx-doc/sphinx/pull/9023 for more details.
From the screenshots it looks like your are using the sphinx_rtd_theme. I guess they might overwrite the default styles provided by Sphinx.

**Comment by outoftardis** [comment]
Thanks for the explanation. I'm using `sphinx-book-theme`, but I also tried `furo`, and there's the same problem. So this should be fixed on the theme side, right?

**Comment by jakobandersen** [comment]
I'm not familiar with those themes, but yes, the main point of the change was exactly to make it possible to customize completely on the theme side. You can find the relevant CSS in the basic theme at https://github.com/sphinx-doc/sphinx/blob/4.x/sphinx/themes/basic/static/basic.css_t#L511. Note that it was only the C and C++ domains that got updated with new code generation this time, so there is CSS for both the previous and new style of code.

**Comment by vermeeren** [comment]
Thanks for all the references @jakobandersen , based upon the above this is not specifically a Breathe issue so I will close it to keep the issue tracker a bit neat. Do feel free to continue posting here though if it is deemed useful.
