### ISSUE TITLE
Introduce formatter for the code base

### ISSUE THREAD

**Issue by michaeljones** [michaeljones/breathe#736]
To my understanding we don't use a formatter for the python code in this project? I'm become quite used to autoformatted code through elm-format and prettier. 

Are we happy to introduce one? Is there a strong preference? I've used [Black](https://github.com/psf/black) on some other python projects and am happy enough with that. It seems to be under the python software foundation github organisation but I don't know if it is in some way official. Would that suit?

**Comment by jakobandersen** [comment]
I'm not too familiar with formatters for Python, but sometimes there are code fragments where the automatic formatting doesn't fit. Though I don't know if there some of these in Breathe, I usually just make ``flake8`` happy manually :-).

**Comment by michaeljones** [comment]
I can't see it in the documentation but `black` does seem to support disabling formatting for certain sections using comments before and after: https://github.com/psf/black/issues/451#issuecomment-412977023

I realise that can be useful in certain situations though I like leaning into the autoformatted style as much as possible generally.

**Comment by t-b** [comment]
I'm using black in some of my projecs and it works nicely.
