### ISSUE TITLE
Directives doc links are broken

### ISSUE THREAD

**Issue by KipHamiltons** [michaeljones/breathe#740]
Links to the examples on [this page](https://github.com/michaeljones/breathe/blob/master/documentation/source/directives.rst) seem to be broken. For example, if you go to the section for `doxygenfunction`, then click the link in the text that says
```
Checkout the :ref:`example <function-example>` to see it in action.
```
It doesn't work.

**Comment by 2bndy5** [comment]
I haven't noticed any dead links. I even tried the link mentioned in the OP, and it works as expected.

@michaeljones @jakobandersen Maybe this was a problem at some point, but it seems to be fixed now.

**Comment by jakobandersen** [comment]
The linked page is just the source code, in which I wouldn't expect much to work. It is rendered however Github likes.
The compiled equivalent is at https://breathe.readthedocs.io/en/latest/directives.html which shouldn't have any unintentional dead links.
I'll close it for now, but please reopen if the compiled version has the problem.
