### ISSUE TITLE
PGP key expired

### ISSUE THREAD

**Issue by dbermond** [michaeljones/breathe#742]
The PGP key `A72F627716EA9D96` used for signing the commits/tags/tarballs have expired and needs renewal:

```
gpg: pub  rsa4096/A72F627716EA9D96 2019-09-26  Melvin Vermeeren (vermware) <vermeeren@vermwa.re>
gpg: Note: signature key A72F627716EA9D96 expired Wed Sep 15 11:08:36 2021 -03
```

**Comment by vermeeren** [comment]
@dbermond I have renewed it recently and submitted it to the openpgp.org keyserver (default in Debian, not sure in other distros). I used to also submit it to the SKS pool, but it seems to have been shut down recently.

https://keys.openpgp.org/search?q=8AED+5802+1FEA+CDD5+F27B++A0E6+A72F+6277+16EA+9D96

I just submitted it the MIT keyservers also, are there any others that are widely used currently that you know of?

Cheers

**Comment by dbermond** [comment]
Thank you for the reply.

The Arch Linux Wiki lists common used key servers: [https://wiki.archlinux.org/title/GnuPG#Key_servers](https://wiki.archlinux.org/title/GnuPG#Key_servers)

I use the first one on the list (Ubuntu key server), as it was one of the most reliable servers a short while ago. It's also used on the [Arch Wiki example for renewing keys](https://wiki.archlinux.org/title/GnuPG#Extending_expiration_date).

My output was generated by using the Ubuntu key server and it was giving me the expired key.

By using `keys.openpgp.org` as mentioned by you I could retrieve the renewed key. Thank you.

**Comment by dbermond** [comment]
By the way, I would like to thank you for providing PGP signatures for commits, tags and tarballs. This is very good for improving package security. :)

**Comment by vermeeren** [comment]
@dbermond Thanks for the details, uploaded the public key to the other services mentioned in the wiki, will keep that in mind for future key renewals as well to avoid troubles.

Cheers
