### ISSUE TITLE
Documentation is wrong about Doxygen alias for "verbatim embed:rst"

### ISSUE THREAD

**Issue by arwedus** [michaeljones/breathe#768]
**Problem description:**

The breathe manual suggests to create ALIASES for `\verbatim embed:rst`, including `\verbatim embed:rst:leading-slashes`, but that won't work due to a bug (or let's say, undocumented behavior) in doxygen.
An executable example project is contained in the [doxygen issue](https://github.com/doxygen/doxygen/issues/8907).

**Solution suggestion:**

Just propose to use the following Doxyfile config option if the project convention is to have leading comment characters (upside of the bug in Doxygen: This works with ANY leading comment character, be it `* `, `///` or `//!`).

```
ALIASES = rst="^^\verbatim embed:rst:leading-asterisk"
ALIASES += endrst="\endverbatim"
```

**Comment by jakobandersen** [comment]
I'm not really familiar with the ``ALIASES`` feature, but it sounds reasonable. Do I understand it correctly that then there would only be a need for 1 type of alias, the ``rst``, and not both ``rst``and ``rststar``?
Could you make a pull request with an update to the documentation?

**Comment by arwedus** [comment]
@jakobandersen : Exactly, that's why I told them that I am actually not much interested in a fix ;-).
We have now set the \rst alias as I have described in PR #770 and it works no matter which comment style (all our projects use a comment style with some leading comment character on each line).
