### ISSUE TITLE
assertion fails with fundamental type in template param

### ISSUE THREAD

**Issue by kaamos1** [michaeljones/breathe#771]
Following assertion is thrown when using a fundamental type in template parameter:
https://github.com/michaeljones/breathe/blob/26844b77d805a93bd0df3e14a289d23adcf8ab19/breathe/renderer/sphinxrenderer.py#L2183

example:
```
template <uint64_t MaxNumberVertices>
class Polygon {
  uint64_t count{MaxNumberVertices};
};

template <long unsigned int N>
void foo(Polygon<N> poly){
    // do stuff
};
```

**Comment by jakobandersen** [comment]
Thanks for reporting! It turns out this is a problem in Sphinx >= 4.2. See https://github.com/sphinx-doc/sphinx/issues/9917. I planning to have it fixed for the next Sphinx release.
