### ISSUE TITLE
Tag and release breathe v4.32

### ISSUE THREAD

**Issue by hidmic** [michaeljones/breathe#774]
Would it be possible to get another release in the near term? 4.31 came out in September.

**Comment by hidmic** [comment]
FYI @clalancette

**Comment by vermeeren** [comment]
@michaeljones @jakobandersen Anything specific that would prevent a release from current master, or something that should still be done?

(Side note: other Breathe-related things from my end planned for this weekend, finally!)

**Comment by jakobandersen** [comment]
@vermeeren, I think #780 would be good to merge first, but otherwise please go ahead.

**Comment by michaeljones** [comment]
@vermeeren, @jakobandersen - are you happy to do a release? @vermeeren do you have time to do one? Even if there are things we might like to get in, I think there is benefit to doing one with what is already there.

**Comment by jakobandersen** [comment]
> @vermeeren, @jakobandersen - are you happy to do a release? @vermeeren do you have time to do one? Even if there are things we might like to get in, I think there is benefit to doing one with what is already there.

Yes, I completely agree. As soon as time allows, please go ahead.

**Comment by vermeeren** [comment]
Yeah I agree, should have been done a while ago but busy times still going on unfortunately. I had to fix black up quickly for CICD to pass in #791, you may want to have a look at that if you have a newer black than 21.10b0.

Changelog updated and release made in the usual way. Really a lot of entries this version very glad to see all the changes, many thanks!

cc @michaeljones @jakobandersen
