### ISSUE TITLE
Templated class support with :cpp:class domain?

### ISSUE THREAD

**Issue by lp35** [michaeljones/breathe#777]
Hi,

I have a templated class like this:

```
namespace toto
{
  template<typename T>
  class MyClass
  {
  ....
  }
}
```

In sphinx, I'm trying to use the domain directive:

```
:cpp:class:`toto::MyClass`
```

but no link is generated. Are template are supported for domains?

Thanks for your time!

**Comment by jakobandersen** [comment]
Yes, that should definitely work. I suspect there is some namespacing stuff going on when the class declaration is transformed in Breathe into a Sphinx directive.
What i tried was:
``test.hpp``:
```c++
namespace toto {
	template<typename T>
	class MyClass {};
}
```
``index.rst``:
```rst
.. doxygenfile:: test.hpp

:cpp:class:`toto::MyClass`
```
which resolves as expected.

How are you inserting the declaration of ``MyClass``?
To help debug this, try adding the following in your ``conf.py``:
```py
breathe_debug_trace_directives = True
breathe_debug_trace_qualification = True
```
That should give quite a lot more information on which directives Breathe effectively ends running in Sphinx.

**Comment by vermeeren** [comment]
As far as we know it does indeed work. @lp35 I will assume resolved for now and close issue, comment if you still need help.
