### ISSUE TITLE
Invalid declaration on `constexpr static` member

### ISSUE THREAD

**Issue by pitrou** [michaeljones/breathe#787]
When building the Apache Arrow docs we get such warnings:
```
/home/antoine/arrow/dev/docs/source/cpp/api/compute.rst:51: WARNING: Invalid C++ declaration: Expected identifier in nested name, got keyword: static [error at 23]
  static constexpr static char const kTypeName []  = "CastOptions"
  -----------------------^
```

Note the original C++ declaration is as follows:
```c++

class ARROW_EXPORT CastOptions : public FunctionOptions {
 public:
  constexpr static char const kTypeName[] = "CastOptions";
  // ...
```

Amusingly, switching the keyword order is enough to suppress the warning:
```c++
  static constexpr char const kTypeName[] = "CastOptions";
```

**Comment by jakobandersen** [comment]
Which version of Breathe did you use?
It very much looks like the problem fixed in https://github.com/michaeljones/breathe/pull/720, which should be in v4.31.0.

**Comment by pitrou** [comment]
I'm already using 4.31.0.

**Comment by jakobandersen** [comment]
Doh, #720 only fixed it for functions.

**Comment by jakobandersen** [comment]
Should now be fixed in master.
