### ISSUE TITLE
Cross-referencing to a doxygenfunction from Sphinx

### ISSUE THREAD

**Issue by Tarek-Git** [michaeljones/breathe#790]
I also have a problem with C++ domain. in my index.rst I have **:cpp:func:`Hello()`**  in my in hallo.rst I have the following lines:

**.. cpp:function:: Hello** 
**.. doxygenfunction:: Hello**

The line with **doxygenfunction** works and I get the documentation generated for my function.

but the line with **cpp:function** doesn't work(i do not know if it is right to use this in my case). Instead, I'm trying to generate a link for the Hello() function in the documentation.

I generated my C++ documentation with Sphinx, Doxygen and Breathe.

**Comment by Tarek-Git** [comment]
Thanks for the answer.
My goal is to create a link with **:cpp:func:`Hello`**.

As soon as you click on the link, you are taken to the documentation for the Hello() function.

But I have to generate the documentation with **.. doxygenfunction:: Hello**. This is the only way that the Doxygen-specific comments of the Hello() function appear.



You're right. **:cpp:func: Hello** and **.. cpp:function: void Hello()** I see the documentation but without the Doxygen-specific comments of the Hello() function.

**Comment by jakobandersen** [comment]
Right, as mentioned, ``.. doxygenfunction::`` will eventually do the equivalent of ``.. cpp:function::`` with data from the Doxygen XML. (If you insert ``breathe_debug_trace_directives = True`` in your ``conf.py`` you can get a peak at which underlying Sphinx domain directives Breathe is invoking)
But I'm unsure if you have a specific issue now? Can you clarify, perhaps with a concrete example of what isn't working as you expect?

**Comment by Tarek-Git** [comment]
For example, I would like to document the function "void registerEvent(IEventListener* listener, IEvent* e)" and a cross-referencing to it in my documentation.

I have tried the following:

in my index.rst :
                            :cpp:func:'registerEvent' #this should be the clickable link

in my EventManager.rst:
 
                             .. cpp:function: registerEvent         #the identification of the places to which the 
                                                                                    #program should jump after clicking on the link (I don't think that's correct)

                              .. doxygenfunction:: registerEvent   #Here is the documentation of the function with the Doxygen comments


the problem is that the link appears but it is not clickable

I want that after clicking the link:

![image](https://user-images.githubusercontent.com/63059099/152750576-ce3eea3a-73d9-414f-b721-d1d7eb1a32c8.png)


it jumps to this point:

![image](https://user-images.githubusercontent.com/63059099/152750710-c51c0f56-10da-421a-854d-bb1b08411378.png)


But that is unfortunately not the case, because the link is not clickable

**Comment by Tarek-Git** [comment]
Thanks! you are the highlight of my day :)

**Comment by Tarek-Git** [comment]
How can i how can I avoid conflicts between because of ambiguity?

for Example if i have to Functions:

void registerEvent(IEventListener* listener, IEvent* e)

and 

unsigned int sendNotification(IDataEvent<T>* e)

so this:

:cpp:func:`EventManager::registerEvent`

create always a cross-reference to the first function.

**Comment by jakobandersen** [comment]
Well, ``:cpp:func:`EventManager::registerEvent` ``, will look for that function, and ``:cpp:func:`EventManager::sendNotification` `` would look for the other function. Did you mean to ask for overloaded functions? In that case you can write a full function signature, see https://www.sphinx-doc.org/en/master/usage/restructuredtext/domains.html#overloaded-member-functions.

**Comment by Tarek-Git** [comment]
Sorry, I made a mistake.  I mean:

void registerEvent(IEventListener* listener, IEvent* e)

and

unsigned int registerEvent(IDataEvent<T>* e)

**Comment by jakobandersen** [comment]
Right, then it's the overload situation, and you will need to specify the full signature for `:cpp:func:` instead of just the name.

**Comment by jakobandersen** [comment]
As this doesn't look like an issue with Breathe I'll close this for now.
