### ISSUE TITLE
Can doxygenindex generate a table of contents?

### ISSUE THREAD

**Issue by red8888** [michaeljones/breathe#798]
I'm curious about how people actually use breathe because I can't find examples of how to auto generate a table of contents. Is everyone manually describing every individual construct with directives like doxygenclass? Because to me that would kind of defeat the purpose of auto generated documentation.

What I would expect is for doxygenindex to generate a table of contents for all its object/anchors. I would be even better of there were parameters to modify and filter it (to only include classes and interfaces in the toc for example).

I still like the big dump (hehe) that doxygenindex does for ctrl+f purposes, but is there a way to at least have a toc generated for all of its anchors or something?

**Comment by vermeeren** [comment]
@red8888 There are some tools to auto generate ToC, see issue #293, which should answer your question. Sphinx also generates some `genindex.html` file or similar that is not linked in the tree, that might also be what you look for.

I will close this issue as duplicate, if you have further question feel free to post there.
