### ISSUE TITLE
doxygenfunction: Order of sections

### ISSUE THREAD

**Issue by 9EOR9** [michaeljones/breathe#800]
I am currently evaluating the switch from an internal documentation format to Sphinx (using breathe and Doxygen) and encountered the following problem using doxygenfunction:

Source:

```
/**
 @brief  short txt

 @details  long txt with some more details

 @param[in] param1
 @param]in] param2

 @return    zero on success, non zero on error

 @note     some notes
 @version   1.0

 @see
            - func1
            - func2
*/
```
After running doxygen, Sphinx and breathe the rendered output from doxygenfunction has the following order:

```
@brief
@details
@see
@params
@return
@note
```

If possible I want to keep the same order as in source code. Is there a way to specify order of sections?

Info:
Doxygen 1.9.3
Sphinx 4.4.0
Breathe 4.32.0

**Comment by vermeeren** [comment]
@9EOR9 There are some settings for the order of things, but it will output in Breathe-defined order (sorted) and not the original XML order always. There is also `:sections:` option, but I believe it's currently implemented only for `doxygenfile`-type directive. Patches welcome to make that more widely usable or as global config setting.

* https://breathe.readthedocs.io/en/latest/directives.html#config-values
* https://breathe.readthedocs.io/en/latest/directives.html#doxygenfile
* https://breathe.readthedocs.io/en/latest/file.html

**Comment by 9EOR9** [comment]
Thanks for your answer - if order of sections is not configurable then using breathe is not an option at the moment.

**Comment by vermeeren** [comment]
Sure, closing this then. Patches welcome.
