### ISSUE TITLE
XML tags break when building with Doxygen 1.9.3 (with traceback)

### ISSUE THREAD

**Issue by lcsmuller** [michaeljones/breathe#817]
Suppose the following aliases, the first one utilizes XML tags and breaks the build, the second one works as expected and is only there for control:
```
ALIASES = "test_with_xml=@xmlonly <verbatim> hello^^world ^^<endverbatim> @endxmlonly" \
          "test_no_xml=@verbatim hello^^world ^^@endverbatim"
```
with the following C header file:
```c
/** @test_with_xml */
struct foo {
    int a;
};
```
this is the resulting traceback when attempting to build Sphinx from the doxygen generated XML:
[sphinx_err.log](https://github.com/michaeljones/breathe/files/8147361/sphinx-err-kr0kg3cx.log)

Its worth noting that this error only began happening after I switched to Doxygen 1.9.3, faced no issues when using 1.8.17. I'm running on Linux Mint 20 (ulyana).

**Comment by 2bndy5** [comment]
I think `<endverbatim>` should actually be `</verbatim>`. This technique is actually noted in the docs' [supported markups page (at the very bottom)](https://breathe.readthedocs.io/en/latest/markups.html)

**Comment by lcsmuller** [comment]
I see, in that case I will be closing this PR!
