### ISSUE TITLE
Does breathe read in `Doxyfile`, and does breathe use pre-generated `XML` files? 

### ISSUE THREAD

**Issue by iquah1** [michaeljones/breathe#826]
As in title. 

1) Does breathe read in `doxygen` configs? 

Behavior between my `doxygen` build command and my `sphinx` build command have vastly different behavior. The `doxygen` command correctly reads my `Doxyfile` and (for example) doesn't output messages when I've set it to `quiet` mode. However, `breathe` will still spit out all the error messages. I've determined that it's `breathe` also because when I comment out the `breathe` line on my extensions, I see no errors.

2) Does `breathe` use pre-generated `XML` files and if not can I make it do so? So that it does not generate `XML` files on its own?

**Comment by vermeeren** [comment]
@iquah1 Breathe reads the Doxygen generated XML files as specified by configuration option `breathe_projects`. It is up to you (or your build system) to invoke Doxygen to generate XML before running Sphinx/Breathe.

Only the `autodoxygen` family of directives will invoke Doxygen for you, but this has many limitations and is not recommended for most use cases.

See also docs https://breathe.readthedocs.io/en/latest/#in-a-nutshell

**Comment by iquah1** [comment]
> Only the autodoxygen family of directives will invoke Doxygen for you, but this has many limitations and is not recommended for most use cases.

Hmm, okay. I'm using `autodoxygenindex`, which I suppose means that it will run `Doxygen` on its own. Do you know how I might make it read in the `Doxygen` file? To make a long story short, I'm muting some of Doxygen's warnings. When I run doxygen manually the output is as expected, muted. However, when I use breathe, it is outputting a lot of warnings (`X is not documented` or `warning: no matching class member found...` and I'm fine with those errors.) which is indicating to me that it is not reading in the doxygen file (but I might be wrong)

**Comment by iquah1** [comment]
NVM :) I figured it out! I just had to set 

```
breathe_doxygen_config_options = {
   "...": "..."
}
```

which did it. I was confused because I was under the impression that if you didn't provide those values that it would read directly from the `Doxyfile` but that appeared to not be the case.

**Comment by vermeeren** [comment]
@iquah1 I think we had some miscommunication, I should have been clearer. What I meant is that if you use a Breathe directive starting with `autodoxygen` then Breathe invokes Doxygen instead of using pre-generated Doxygen XML.

So concretely you would use not `autodoxygenindex` but instead `doxygenindex` directive so it uses pre-generated XML with custom settings. This is more flexible then the limited config and preprocessing you can do through Breathe `autodoxygen` directives.

Good to know you got it to work however!

Cheers
