### ISSUE TITLE
Autodoxygen source option not known

### ISSUE THREAD

**Issue by scopatz** [michaeljones/breathe#83]
As of the current master v1.2 (b30dee9b4d83), I am now seeing a lof of breakage with the autodoxygenindex directive:

``` bash
/home/scopatz/pyne/docs/cppapi/rxname.rst:4: ERROR: Error in "autodoxygenindex" directive:
unknown option: "source".
```

I don't know when this snuck in, but now breathe doesn't work at all with automatic tools.

**Comment by leimao** [comment]
Could you please verify this is still working? It seems that it is broken at my side.
```
/home/leimao/GitHub/Sphinx-CPP-TriangleLib/docs/source/api.rst:9: WARNING: Error in "autodoxygenfile" directive:
unknown option: "source".

.. autodoxygenfile:: triangle.h
   :source: auto
```

**Comment by SooluThomas** [comment]
Was this fixed? I'm getting the same error: 

```
ERROR: Error in "autodoxygenfile" directive:
unknown option: "source".
```

**Comment by vermeeren** [comment]
@leimao @SooluThomas The option is called `:project:` nowadays, not `:source:`. This has been the case for years, I don't personally remember a time where it was `:source:`. #551 updated some docs for this in 2020.
