### ISSUE TITLE
Is there a way to automatically generate all the pages I may need? 

### ISSUE THREAD

**Issue by iquah1** [michaeljones/breathe#836]
Hey there! 

So, I've got a lot of functions (the below screenshot is a subset)

![2022-04-28-133713_1920x2160_scrot](https://user-images.githubusercontent.com/97902382/165841467-6839f096-8e8b-4250-93a8-b20da9722af8.png)

I'm currently using `autodoxygenindex` because it seems rather tedious to manually write everything out. i use a simple Python script to glob files based on the folder structure and then spit out the values e.g

```python
accumulator = []

def scan_dir(prefix, append_print, fixed):

    fmt_path = lambda a: a
    files = []
    horizon = []
    all_files = []
    for el in os.listdir(prefix):
        all_files.append(el)
        if el.endswith(".h"):
            files.append(el)
        elif os.path.isdir(prefix + "/" + el):
            horizon.append(el)

    accumulator.append((append_print, fmt_path(prefix), files))

    for el in horizon:
        scan_dir(prefix + f"/{el}", append_print + f"_{el}", fixed)

# Location of the modules
for module in MODULE_LIST:
    scan_dir(f"../src/{module}/include", module, module)

breathe_projects_source = {k: (v1, v2) for (k, v1, v2) in accumulator}
```

and `accumulator` looks like:

```
{'pke': 
    ('../src/pke/include', ['metadata.h', 'constants.h', 'cryptocontextgen.h', 'cryptocontext.h', ...,  'ciphertext.h']), 
'pke_encoding': ('../src/pke/include/encoding', ['coefpackedencoding.h', 'stringencoding.h', ..., 'encodings.h']),
....
}
```

**However**, it's rather messy and is tedious in some places. For example [OpenFHE Boolean FHE Documentation](https://openfhe-development.readthedocs.io/en/latest/assets/sphinx_rsts/modules/binfhe.html#boolean-fhe-generated-docs) where all the file contents are dumped.

# Ideal Scenario

Ideally, I'd have something that looks like Pytorch's automatic differentiation module:

![2022-04-28-133936_1920x2160_scrot](https://user-images.githubusercontent.com/97902382/165841867-1ca12668-fa45-4319-b686-1879780462e1.png)

Looking at the [documentation page](https://pytorch.org/docs/stable/autograd.html) I see that the relevant rst portion is 

```
.. role:: hidden
    :class: hidden-section

Automatic differentiation package - torch.autograd
==================================================

.. automodule:: torch.autograd
.. currentmodule:: torch.autograd

.. autosummary::
    :toctree: generated
    :nosignatures:

    backward
    grad
```

and clicking on `backward` I see the following:

![2022-04-28-133947_1920x2160_scrot](https://user-images.githubusercontent.com/97902382/165843650-1a46478f-43c4-4640-a656-b1396102c173.png)

which was generated via 

```
torch.autograd.backward
=======================

.. currentmodule:: torch.autograd

.. autofunction:: backward
```

but I'd ideally not have to do that for every single function/class/enum. Is there a good way to do this? 

# Note:

I opened an issue here as I think it's more relevant to `breathe` than `Sphinx`

**Comment by vermeeren** [comment]
@iquah1 Could you check #293 ? I think breathe apidoc or exhale could be of use here. I believe docs are not yet updated still and there are various other things that ideally need some improvement.

**Comment by iquah1** [comment]
I ended up using exhale to solve the problem! Thank you!
