### ISSUE TITLE
Empty fulllineitems environment in LaTeX output

### ISSUE THREAD

**Issue by danielmatz** [michaeljones/breathe#90]
When I use the ``doxygenclass`` directive, the generated LaTeX output won't compile, due to several empty ``fulllineitems`` environments.

Seems that I'm to blame, as this was introduced in 21d4767350e92714e8baad295ac41ff31e122a5d.  Oops...

**Comment by vitaut** [comment]
This has been fixed and [PDF docs](https://media.readthedocs.org/pdf/breathe/latest/breathe.pdf) are generated correctly.
